### ISSUE TITLE
Submitting pbs-torque scheduler

### ISSUE THREAD

**Issue by gadepallivs** [maxplanck-ie/snakepipes#101]
Hi, We submit jobs via pbs scripts for our NGS pipeline jobs. I came across these snakemake pipelines and interested to try the same on our cluster, but submit jobs via pbs rather than slurm. How should I do this, do you have any support in this regard. 
So far, I tried to setup up this [Snakemake-Profiles](https://github.com/Snakemake-Profiles/pbs-torque). But, ran into errors while submitting the same ( opened an [issue](https://github.com/Snakemake-Profiles/pbs-torque/issues/8). 

Just wondering if you have any documentation/example to run your snakemake pipelines via pbs-torque scheduler. Appreciate any help on this. 
Thank you

**Comment by dpryan79** [comment]
At the moment out `SlurmEasy` script is hard-coded in the various wrapper scripts (e.g., `RNA-seq`). What you'll need to do is remove that and add `qsub` or whatever command is appropriate for your cluster.

**Comment by vivekbhr** [comment]
we only have experience with SGE and slurm (although slurm is hardcoded in the snakepipes). curious to see if it could be adapted to pbs-torque :thinking:

**Comment by dpryan79** [comment]
At the end of the day the scheduler should be an essentially replacable component, presuming it works with Snakemake.

**Comment by gadepallivs** [comment]
Thank you for pointing in the right direction. My experience with python is minimal. I modified the part where slurmEasy is called. Threads probably should be OK, even though I general specify nodes and processs per node. But, not which paths you suggested to modify. 
```
snakemake_cmd += ["--cluster-config ",
                   os.path.join(this_script_dir, "cluster.yaml"),
                   " --cluster 'qsub --mem {cluster.memory}
    		     --nodes {nodes}
		     --walltime {walltime}
		     --ppn {ppn}
		     --A {A}
		     --log", args.cluster_logs_dir,
		    "--name {rule}.snakemake'"]
```

**Comment by gadepallivs** [comment]
Thank you vivek. Ryan mentioned about modifying paths , I did not understand where this needs to be changed. 
How are the submitted jobs configured? I assume the pipeline submits a chain of jobs of various size, and parallelly. For instance, alignment may require more computing power and parallel submissions, may be another step in the pipelines would not really require that power. I don't know if this variability could be controlled in snakemake workflows ?

**Comment by dpryan79** [comment]
The paths are in `shared/paths.yaml`. If you need to `module load` stuff on your cluster then you can use `module load whatever && ` there.

**Comment by vivekbhr** [comment]
@gadepallivs the number of jobs can be specified during snakemake execution using --jobs params. The number of cores per jobs can be specified using the cluster config (although we have if currently hard-coded in rules but we plan to move this to the cluster config in near future)

**Comment by mictadlo** [comment]
I would like to run the HI-C pipeline and just wonder whether there is any documentation for PBS pro?

**Comment by dpryan79** [comment]
@mictadlo I assume your command would then be something like `qsub -u "{rule}" -lncpus {threads} -lmem {cluster.memory}` rather than our `SlurmEasy` command. You can change this in `cluster.yaml` file mentioned in the output of `snakePipes info`. I should note that the `cluster.memory` parameter will be something like "3G" or "3200M", since that's what slurm understands. If PBS pro needs per-core memory requirements in a different format then I suggest writing a wrapper script ([ours](https://github.com/dpryan79/Misc/blob/master/MPIIE_internal/SlurmEasy) does a bunch of additional things, but it's Slurm rather than PBS pro).
