### ISSUE TITLE
[Question] where to find the exact command issued?

### ISSUE THREAD

**Issue by sunta3iouxos** [maxplanck-ie/snakepipes#1012]
Hi all,
Where can I find the commands issued for each step of the analysis? I do not see them in any  log file and apparently the sbatch commands are deleted (?).
Thank you

**Comment by katsikora** [comment]
Hi,

if you run the workflow with `--verbose`, it will be logged to the main log in the output folder.
Otherwise, some of the commands get logged into the *.err files in the `cluster_logs` folder upon error, assuming you're running snakePipes on a cluster.

Best wishes,

Katarzyna

**Comment by sunta3iouxos** [comment]
Perfect,
Thank you
