### ISSUE TITLE
illegal regex - 3.0.0

### ISSUE THREAD

**Issue by WardDeb** [maxplanck-ie/snakepipes#1029]
createIndices.snakeFile has an illegal regex, evoking a warning:
https://github.com/maxplanck-ie/snakepipes/blob/cb28234d48852b502b0b61818efd170ceecf2e80/snakePipes/shared/rules/createIndices.snakefile#L57

This is changed (but not tested, as it's not clear to me what the exact functionality is):
https://github.com/maxplanck-ie/snakepipes/blob/5a0abec2e436af26c76c7e72942bff457a67cf5f/snakePipes/shared/rules/createIndices.snakefile#L57

 - [ ] Make sure this change doesn't break anything

Similarly, three_prime_seq evokes the same warning:

`snakePipes/shared/rules/three_prime_seq.snakefile:8: SyntaxWarning: invalid escape sequence '\/'  `

which is triggered by:
https://github.com/maxplanck-ie/snakepipes/blob/cb28234d48852b502b0b61818efd170ceecf2e80/snakePipes/shared/rules/three_prime_seq.snakefile#L8

https://github.com/maxplanck-ie/snakepipes/blob/cb28234d48852b502b0b61818efd170ceecf2e80/snakePipes/shared/rules/three_prime_seq.snakefile#L222

 - [ ] fix the regex, or drop the constraint

**Comment by katsikora** [comment]
> createIndices.snakeFile has an illegal regex, evoking a warning:
> 
> https://github.com/maxplanck-ie/snakepipes/blob/cb28234d48852b502b0b61818efd170ceecf2e80/snakePipes/shared/rules/createIndices.snakefile#L57
> 
> This is changed (but not tested, as it's not clear to me what the exact functionality is):
> 
> https://github.com/maxplanck-ie/snakepipes/blob/5a0abec2e436af26c76c7e72942bff457a67cf5f/snakePipes/shared/rules/createIndices.snakefile#L57
> 
>     * [ ]  Make sure this change doesn't break anything
> 
> 
> Similarly, three_prime_seq evokes the same warning:
> 
> `snakePipes/shared/rules/three_prime_seq.snakefile:8: SyntaxWarning: invalid escape sequence '\/' `
> 
> which is triggered by:
> 
> https://github.com/maxplanck-ie/snakepipes/blob/cb28234d48852b502b0b61818efd170ceecf2e80/snakePipes/shared/rules/three_prime_seq.snakefile#L8
> 
> https://github.com/maxplanck-ie/snakepipes/blob/cb28234d48852b502b0b61818efd170ceecf2e80/snakePipes/shared/rules/three_prime_seq.snakefile#L222
> 
>     * [ ]  fix the regex, or drop the constraint

The regex in `createIndices.snakeFile` renames spikein genome chromosomes, giving them a suffix provided to `spikeinExt`, such that you can fish them out by extention after having created a genome that is the union of 'host' and 'spikein' chromosomes.
