### ISSUE TITLE
error in createEnvs

### ISSUE THREAD

**Issue by Leif78** [maxplanck-ie/snakepipes#1050]
Hi, I have a problem when createEnvs. I got the same error on both linux and Mac. 

(snakePipes) leif@Leif-sin-MacBook-Pro ~ % snakePipes createEnvs
Traceback (most recent call last):
  File "/Users/leif/miniconda3/envs/snakePipes/bin/snakePipes", line 441, in <module>
    main(sys.argv[1:])
  File "/Users/leif/miniconda3/envs/snakePipes/bin/snakePipes", line 435, in main
    createCondaEnvs(args)
  File "/Users/leif/miniconda3/envs/snakePipes/bin/snakePipes", line 322, in createCondaEnvs
    md5hash.update(condaDirUse.encode())
                   ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'encode'

Any suggestions for what I can do?

Best regards,
Leif

**Comment by katsikora** [comment]
Hi Leif,

which snakePipes version are you using?

Best,

Katarzyna

**Comment by Leif78** [comment]
packages in environment at /Users/leif/miniconda3/envs/snakePipes:
#
# Name                    Version                   Build  Channel
snakepipes                2.8.0                      py_0    mpi-ie

**Comment by katsikora** [comment]
Hi,
did you run `snakePipes config --condaEnvDir $YOUR_ENV_DIR` before `snakePipes createEnvs` ?

Best wishes,

Katarzyna

**Comment by Leif78** [comment]
Hi, I tried this:

(snakePipes) leif@Leif-sin-MacBook-Pro ~ % snakePipes config --condaEnvDir $/Users/leif/miniconda3/envs/

--- Final Updated Config ---------------------------------------------------------------------
config file: /Users/leif/miniconda3/envs/snakePipes/lib/python3.12/site-packages/snakePipes/shared/defaults.yaml
clusterConfig: shared/cluster.yaml
condaEnvDir: $/Users/leif/miniconda3/envs/
configMode: manual
emailSender: None
max_thread: 25
oldConfig: None
onlySSL: False
organismsDir: shared/organisms
smtpPassword: None
smtpPort: 0
smtpServer: None
smtpUsername: None
snakemakeOptions: 
tempDir: /data/extended/
toolsVersion: True
-------------------------------------------------------------------------------- 

(snakePipes) leif@Leif-sin-MacBook-Pro ~ % snakePipes createEnvs
Creating environment from /Users/leif/miniconda3/envs/snakePipes/lib/python3.12/site-packages/snakePipes/shared/rules/envs/shared.yaml in $/Users/leif/miniconda3/envs/
usage: mamba [-h] command ...
mamba: error: unrecognized arguments: --force
There was an error when creating the environments!

but it is not working yet.

Best regards Leif

**Comment by katsikora** [comment]
Thanks!

I see `--force` has been deprecated. It would work with a conda version < 24.3. Is downgrading conda an option for you?

Otherwise, snakePipes 3.0.0 has the fix in place.

Best wishes,

Katarzyna

**Comment by Leif78** [comment]
Thanks, I downgraded conda and upgraded snakePipes and now it works.

Best  regards, 
Leif

**Comment by sunta3iouxos** [comment]
How do we get the 3.0.0 version of snake pipes?

**Comment by katsikora** [comment]
Hi,
the release is available via conda, it should be possible to obtain via
```conda create -n snakePipes -c mpi-ie -c conda-forge -c bioconda snakePipes```

Best,

Katarzyna
