### ISSUE TITLE
Update read downsampling shell script

### ISSUE THREAD

**Issue by katsikora** [maxplanck-ie/snakepipes#106]
In the current version, read downsampling gives a warning message if read names from mates are different, even if it's only by the suffix /1 and /2. This naming is deprecated since some time but downsampling reads from older runs gives this warning message.

@39V34V1:207:C70P6ACXX:8:1103:11632:61146/1	@39V34V1:207:C70P6ACXX:8:1103:11632:61146/2 Read names in paired-end fastq files are out of sync!
@39V34V1:207:C70P6ACXX:5:2101:7575:36461/1	@39V34V1:207:C70P6ACXX:5:2101:7575:36461/2 Read names in paired-end fastq files are out of sync!
@39V34V1:207:C70P6ACXX:2:2216:2841:24703/1	@39V34V1:207:C70P6ACXX:2:2216:2841:24703/2 Read names in paired-end fastq files are out of sync!
@39V34V1:207:C70P6ACXX:8:1103:11688:80199/1	@39V34V1:207:C70P6ACXX:8:1103:11688:80199/2 Read names in paired-end fastq files are out of sync!
@39V34V1:207:C70P6ACXX:5:2101:7579:53624/1	@39V34V1:207:C70P6ACXX:5:2101:7579:53624/2 Read names in paired-end fastq files are out of sync!
@39V34V1:207:C70P6ACXX:2:2216:2851:98510/1	@39V34V1:207:C70P6ACXX:2:2216:2851:98510/2 Read names in paired-end fastq files are out of sync!
@39V34V1:207:C70P6ACXX:8:2110:4013:38480/1	@39V34V1:207:C70P6ACXX:8:2110:4013:38480/2 Read names in paired-end fastq files are out of sync!

**Comment by steffenheyne** [comment]
line 76 of current script downsample_se_pe.sh need to be adapted:

... | awk '{if ($1!=$3) print $0,"Read names in paired-end fastq files are out of sync!"; }'

instead of $1!=$3 we could strip patterns like /1 /2 and then check 

we should also throw a real error in case they are out of sync

**Comment by dpryan79** [comment]
This is now implemented in `develop`.
