### ISSUE TITLE
resources/--j

### ISSUE THREAD

**Issue by hanrong498** [maxplanck-ie/snakepipes#1065]
Hi,

Thanks for the active development of snakePipes :)

I noticed that in the version 3.0.0, there is no longer the option --local and --j. Could you explain how can I allocate more resources to the pipeline now? 

Thanks a lot!
Hanrong

**Comment by hanrong498** [comment]
perfect, thanks a lot!

**Comment by malszycki** [comment]
Please write that in the "setting up snakepipes" section of the documentation. Also is the value specified in config.yaml the maximum number of threads or the software will crash if run with less threads available? Is there any documentation that could help me set up the cluster config file?

**Comment by katsikora** [comment]
Hi Malszycki,

yes, we can update documentation.

Have you tried the cluster config provided with snakePipes and did it fail for you?
Are you using slurm queue manager (this should work out of the box) or another queueing system?

Best wishes,

Katarzyna

**Comment by malszycki** [comment]
Hi Katarzyna,
we have custom made queue manager (based on qsub). Previus snakePipe versions worked well with -local flag, but now using local snakemake profile works, but uses only 2 threads (and takes ages). I tried to modify both the local and genericprofile, but it seems that in both cases the execution is stuck at the very beginning (at least for the few hours I tested). 

Cheers,
Michał

**Comment by katsikora** [comment]
Hi Michal,

the generic snakemake profile is meant for cluster usage.
For local usage, you'd need to modify the local profile . The first line specifies the number of cores that would be used by default and is set to 2.
After modifying your selected profile file, run:
```
snakePipes config --snakemakeProfile /your/modified/profile
```
To be more specific, you'd need to pass the path to the *folder* containing the profile file.

Hope this helps,

Best wishes,

Katarzyna

**Comment by LeilyR** [comment]
Hi, I am using snakepipes 3.4 with local profile. The number of cores set in local profile affects the number of threads and it is not defining the number of job to be submitted in parallel. Could you please help me with that?  for example I get one STAR job submitted at the time with 15 threads if I set the core in the local profile to 15.
