### ISSUE TITLE
createIndices yaml output

### ISSUE THREAD

**Issue by WardDeb** [maxplanck-ie/snakepipes#1071]
By default the organism yaml gets written to the default organism folder (which makes sense). An additional copy in the actual output folder of the run would also be good to have (and has a negligible footprint when compared to the other files).

**Comment by katsikora** [comment]
Hi Ward,
I didn't quite understand where the organism yaml is missing after running createIndices?

If you run `createIndices` with some output folder and `--userYAML some_prefix`, then the yaml with this prefix will be created in the specified output folder.

Hope this helps,
Katarzyna
