### ISSUE TITLE
Add native snakemake support for external (R) scripts 

### ISSUE THREAD

**Issue by katsikora** [maxplanck-ie/snakepipes#117]
From snakemake docs:

In the R script, an S4 object named snakemake analog to the Python case above is available and allows access to input and output files and other parameters. Here the syntax follows that of S4 classes with attributes that are R lists, e.g. we can access the first input file with snakemake@input[[1]] (note that the first file does not have index 0 here, because R starts counting from 1). Named input and output files can be accessed in the same way, by just providing the name instead of an index, e.g. snakemake@input[["myfile"]].

This could be used to replace the current shell ('Rscript') + argparse combo. 

- [ ] DESeq2 
- [x] CSAW
- [ ] WGBS

**Comment by dpryan79** [comment]
Here are the remaining R scripts that need better integration (or just converting them to python if they're only munging files).

 - [ ] library_type.R
 - [ ] merge_count_tables.R
 - [ ] merge_featureCounts.R
 - [ ] sleuth.R
 - [ ] wasabi.R
 - [ ] WGBSpipe.interval_stats.limma.R
 - [ ] WGBSpipe.metilene_stats.limma.R
 - [ ] WGBSpipe.POM.filt.R
 - [ ] WGBSpipe.singleCpGstats.limma.R
 - [ ] WGBS_QC_report_template.Rmd ?

**Comment by steffenheyne** [comment]
how can I debug such a script independently of snakemake? I think we should not easily delete all the commandArgs() stuff if we do not have a way to test a script just from command line...

**Comment by dpryan79** [comment]
You just use snakemake on the command line to debug it, it ends up being the same since you're just looking at what's printed to the console.

**Comment by steffenheyne** [comment]
somehow, but just using a Rscript [..]. call would be more straightforward/faster/efficient for debugging/extending a script...

Why not something like if "snakemake s4 object exists" { } else { commandArgs() } ?

**Comment by dpryan79** [comment]
That'd work too.

**Comment by dpryan79** [comment]
Xref #182

**Comment by dpryan79** [comment]
These end up being a bit annoying to debug and the only thing they really add is that everything is in one place (though with scripts we can have them in a dedicated directory). I'll close until there's a more compelling reason to implement this.
