### ISSUE TITLE
Required documentation

### ISSUE THREAD

**Issue by vivekbhr** [maxplanck-ie/snakepipes#142]
Checkbox for documentation : 
 - [x] Landing page
 - [x] Installing and running the workflows
 - [x] RNA-Seq
 - [x] DNA-mapping
 - [x] ChIP-Seq
 - [x] ATAC-Seq
 - [x] WGBS-Seq
 - [x] scRNA-seq
 - [x] Hi-C

Minimally we need this info per workflow : 

 - Description of what it does + required input
 - Example DAG
 - The explanation for workflow-specific config file parameters
 - Output folder structure
 - Description of some of the outputs (preferably with images)
 - Usage example
 - Argparse

**Comment by dpryan79** [comment]
I've modified this so the items are in the order in which I think they should appear. We can discuss if someone has other preferences there.
