### ISSUE TITLE
make trimming adaptor sequence configurable, maybe skip TrimGalore

### ISSUE THREAD

**Issue by steffenheyne** [maxplanck-ie/snakepipes#151]
see dicussion here:
https://github.com/maxplanck-ie/snakepipes/issues/53

**Comment by dpryan79** [comment]
An alternative would be `fastp`. Apparently it's multithreaded and can do a bunch of nice things like filtering by complexity and poly-A content. Some of the Galaxy tutorials might get switched over to this.

**Comment by dpryan79** [comment]
In case anyone external to us is wondering, I've benchmarked `fastp` and it's slower than cutadapt once you start using more than a couple cores. I really like some of its options, so I'm currently trying to figure out if I can speed it up a bit.

**Comment by mictadlo** [comment]
What about afterqc?

**Comment by dpryan79** [comment]
@mictadlo My understanding is that afterqc is quite similar, only slower. It's from the same authors and they mention that in the fastp preprint at least. I have to admit to not having tried afterqc, though. If you've found it to be performant and the results to be good then let me know :)

**Comment by mictadlo** [comment]
Thank you for pointing it out to me. `fastp` sounds good actually.
