### ISSUE TITLE
Custom genome yaml files require an absolute path

### ISSUE THREAD

**Issue by dpryan79** [maxplanck-ie/snakepipes#154]
Unless the working directory happens to also be the output directory, snakemake won't be able to open the config file since it will be elsewhere. Internally, we need to check if `genome` ends in `.yaml` and wrap it is `abspath()` if so.

**Comment by steffenheyne** [comment]
fixed here https://github.com/maxplanck-ie/snakepipes/pull/155

**Comment by steffenheyne** [comment]
ah I didn't check for .yaml ending yet, just if it is a file...

**Comment by dpryan79** [comment]
Checking if it's a file is probably sufficient, then people can use `.yaml`, `.yml`, or even `.I hate all markup languages`.

**Comment by steffenheyne** [comment]
ok, then I leave it :-)
