### ISSUE TITLE
RNA-seq DESeq2 heatmap issue

### ISSUE THREAD

**Issue by steffenheyne** [maxplanck-ie/snakepipes#163]
I wonder what is going on with that result heatmap...wrongly rotated or what is the color scale here?

![image](https://user-images.githubusercontent.com/10652658/41902968-fe3ccfc6-7934-11e8-9854-b33892375002.png)

On each row we should have some red and blue if these are z-scores....here it seems per column!

**Comment by steffenheyne** [comment]
by comenting out line 263 in DE_functions.R we get this:

I think this is a bit less confusing, or?

![image](https://user-images.githubusercontent.com/10652658/41904741-793430bc-7939-11e8-8153-d988ddb1613f.png)

**Comment by vivekbhr** [comment]
@steffenheyne It was both centered and scaled (to convert to Z-score), but I guess it's not needed.. I always wanted to make those heatmap more informative

**Comment by steffenheyne** [comment]
@vivekbhr 
in the snakepipes/snakediff DE script are now two heatmaps:
1. like above to show absolute expression (differences) per gene
2. a z-score based heatmap to visualize relative expression differences like this:

![image](https://user-images.githubusercontent.com/10652658/42259973-e6104de0-7f62-11e8-9f8b-b08d7bc121c9.png)

are you ok with that? Then we can close this here.... :-)

**Comment by steffenheyne** [comment]
![image](https://user-images.githubusercontent.com/10652658/42278736-0fec7c36-7f9c-11e8-8ff6-04524088a606.png)

with a sequential colro scale

**Comment by vivekbhr** [comment]
closed by #169 now I think
