### ISSUE TITLE
--printToolVersions option

### ISSUE THREAD

**Issue by vivekbhr** [maxplanck-ie/snakepipes#183]
I think the snakePipes wrapper should also have the `printToolVersions` command that prints all tool versions from the env.yaml files for the user..

**Comment by dpryan79** [comment]
:+1: Amusingly, Galaxy does this for all tools when ever they're run. Shall we have it just dump the conda env contents or perhaps instead filter it by what's specified in the environment yaml?

**Comment by bgruening** [comment]
Yes, please!

**Comment by vivekbhr** [comment]
Yah I was simply thinking of printing what's there in env.yamls.. We can instead simply call the command  `version` and then make it print snakepipes version + versions of tools from each environment

**Comment by LeilyR** [comment]
Actually I made a function for hic which generates a text file with the content of conda yaml files. Do you think it should be optional or has to be generated anyway?

**Comment by steffenheyne** [comment]
eg the wrapper could always print it with -v --verbose option, a file could be always generated, it is just a small text file
 
I wonder also if one could identify with that a user version of some package that takes precedence over the version specified/installed in the conda env

**Comment by dpryan79** [comment]
We might need to use [version tracking](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#version-tracking ) with a custom command to see what's really used. Galaxy does that, so there's certainly precedence.

**Comment by dpryan79** [comment]
Leily merged this functionality in.
