### ISSUE TITLE
Use snakemake reports?

### ISSUE THREAD

**Issue by dpryan79** [maxplanck-ie/snakepipes#196]
An idea for a future version is to spin off the various figures into a proper [snakemake report](https://cdn.rawgit.com/snakemake-workflows/dna-seq-gatk-variant-calling/master/.test/report.html). I think WGBS is already doing a lot of nice reporting like this, but I suspect it's the only one.

**Comment by dpryan79** [comment]
This would take care of #183 essentially.

**Comment by vivekbhr** [comment]
I think we should do it ! :+1:  I was planning to convert the DE/DB Rscript to markdown like @katsikora. But I think this would be separate from snakemake reports anyway.

**Comment by dpryan79** [comment]
I don't foresee us ever doing this since we've moved mostly to Rmd files.
