### ISSUE TITLE
Rename DAG for some pipelines

### ISSUE THREAD

**Issue by dpryan79** [maxplanck-ie/snakepipes#204]
A reminder for myself, the DAG output always has the same name. That's normally fine, but for ATAC-seq and ChIP-seq that'll end up in the DNA DAG getting overwritten. We should change the output names for those pipelines (otherwise keeping the default `pipeline.pdf` name).

**Comment by vivekbhr** [comment]
we can simply name it <pipeline_name>_dag.pdf ?

**Comment by dpryan79** [comment]
Yes, that's basically how it should end up (though without _dag). I liked the uniformity of having the same name originally, but I'm starting to recognize the issues that's causing now.

**Comment by dpryan79** [comment]
This is now implemented in alpha 4
