### ISSUE TITLE
make plotPCA images wider

### ISSUE THREAD

**Issue by steffenheyne** [maxplanck-ie/snakepipes#208]
![image](https://user-images.githubusercontent.com/10652658/43132121-0d2bd2fe-8f3b-11e8-9ba2-17925bc95617.png)

this is a default output that we can do better!!!

**Comment by dpryan79** [comment]
I'll push out deepTools 3.1.1 with an increased default width this week :)

**Comment by vivekbhr** [comment]
@dpryan79 IMO samplenames should be on top of the PCA plot, not on the side. This always creates issues

**Comment by dpryan79** [comment]
Putting names on top will create the same errors with `top <= bottom` and people complaining about the legend being in the wrong place. The best solution is to use interactive images, since then one mouses over the data to get the label (assuming one even cares).

**Comment by steffenheyne** [comment]
fixed in #211
