### ISSUE TITLE
ChIP-seq --single-end is still confusing.

### ISSUE THREAD

**Issue by vivekbhr** [maxplanck-ie/snakepipes#212]
I suggest changing the name to `--paired-end` with `store_true` instead of `single-end` with `store_false`

**Comment by steffenheyne** [comment]
I would keep the variables as they are, paired-end data is default nowadays, single-end is the exception and in many rules we use `if paired...`

if the `default: 'TRUE'` is confusing, we can skip printing the default for that particular option or print the inverted value (as we once did, don't now why it was removed)

**Comment by vivekbhr** [comment]
I removed printing of default
