### ISSUE TITLE
--bw-binsize issue

### ISSUE THREAD

**Issue by vivekbhr** [maxplanck-ie/snakepipes#219]
- --bw-binsize is rendered from parserCommon in RNAseq/HiC/DNAmapping workflow, but is still rendered from the workflow.py in other workflows.
 - It's been set to False for RNAseq workflow, so no option for bigwigs is visible in the wrapper on cmdline..

**Comment by dpryan79** [comment]
Maybe I set `bw=False` by mistake in RNAseq, I didn't remember it being an actual option there. In HiC there's an option with the same name but it's doing something different. We should add it to the RNAseq workflow though.
