### ISSUE TITLE
Workflow for index generation

### ISSUE THREAD

**Issue by dpryan79** [maxplanck-ie/snakepipes#222]
This is mostly a reminder to me to write a workflow that can take URLs and other such things as command line options and produce indices and an appropriate YAML file from it.

**Comment by mictadlo** [comment]
Where could I find your code?

**Comment by dpryan79** [comment]
It should be in the most recent beta release (both here and via conda).

**Comment by mictadlo** [comment]
Do you think I could run your code with the stable version?

**Comment by dpryan79** [comment]
The `createIndices` workflow should be compatible with previous versions of snakePipes, but I suggest using the most recent beta release anyway. I expect to tag an official 1.0 release tomorrow, for what it's worth.

**Comment by mictadlo** [comment]
I look forward to running the official 1.0 release. When do you think it would be ready?

**Comment by dpryan79** [comment]
Today I expect :)

**Comment by dpryan79** [comment]
The 1.0.0 release has been tagged and is getting uploaded to anaconda.org now (give it 30 minutes or so).
