### ISSUE TITLE
inclusion of pyGenomeTracks

### ISSUE THREAD

**Issue by steffenheyne** [maxplanck-ie/snakepipes#223]
I think it would be a nice feature to provide some auto-configured `tracks.ini` for pyGenomeTracks for a workflow instance. This should include the most relevant data/bigwigs and can also generate some figure from it. 

The region list is either predefined (organism.yanl) or eg taken from top most differential regions or from user input (bed file) ...

With simple modifications this would also allow users to plot additional regions, but with a much lower entry point... and maybe more plots in publications/citations for us :-)

**Comment by vivekbhr** [comment]
funny I was thinking the same thing

**Comment by dpryan79** [comment]
This would almost have to be according to DE/DB regions. Aside from that :+1:

**Comment by vivekbhr** [comment]
actually I was thinking of simply generating tracks.ini after workflow is finished and leave the --region argument to the user..

**Comment by dpryan79** [comment]
That'd work too, but if possible it'd be nice to give them a track or two to wet their appetite.

**Comment by steffenheyne** [comment]
yeah a default "appetizer" image should be there whenever possible, 
the --region <user.bed> could be there in addition

even for DNA-mapping (or non-differential runs) I would provide one default region/image

**Comment by katsikora** [comment]
I'm closing this as there appears to be no follow-up. Feel free to re-open .
