### ISSUE TITLE
Pandoc, texlive and titling.sty are currently system requirements

### ISSUE THREAD

**Issue by dpryan79** [maxplanck-ie/snakepipes#224]
The PDF generation in the WGBS pipeline currently needs `titling.sty` installed, which isn't there by default on centos. It's also using pandoc, which isn't getting installed via conda. That's easy to fix and it's easy to install texlive-core, but titling.sty is still going to be missing. We could redistribute and install that with `snakePipes createEnvs` easily enough, but ideally this could be a conda requirement. I need to look into this more once I'm back from vacation.

**Comment by dpryan79** [comment]
It's the `produce_report` step that fails (on some but not all nodes) currently.

**Comment by katsikora** [comment]
I don't know if that matters but produce_report is currently a local rule

**Comment by dpryan79** [comment]
Must have been missing on rapidus then, good call on your part making it local :)

I installed texlive-titling on all of the nodes yesterday so the pipeline would complete successfully. I'm not really sure how we should handle this externally. There's minimal support in conda for tex and the RStudio doesn't seem to want to make titling.sty available with their package (they already provide some other .sty files). That decision can wait, though, since this is such a minor issue.

**Comment by dpryan79** [comment]
This is external to snakePipes, so I'm closing.
