### ISSUE TITLE
output bigwigs from methXT step in WGBS

### ISSUE THREAD

**Issue by vivekbhr** [maxplanck-ie/snakepipes#226]
bedgraph files are not compatible with deeptools in downstream analysis

**Comment by dpryan79** [comment]
Unless someone has a strong opinion to the contrary, I'd suggest closing this as "generally not that useful in practice".

**Comment by steffenheyne** [comment]
What is meant here exactly? what is methXT?
A bigwig with the methylation calls (0-100) is quite useful for visualization eg. in IGV. At least with UCSC this can be created, or with a python script and libbigwig...

**Comment by dpryan79** [comment]
IGV can handle BAM files appropriately and color according to methylation levels. That's arguably more useful since you get coverage too (otherwise you need two tracks). Given that I've never found actual methylation tracks that useful (they rarely work well in deepTools due being so sparse).

**Comment by dpryan79** [comment]
This is now implemented, closing.
