### ISSUE TITLE
add bam as alternative entry point

### ISSUE THREAD

**Issue by katsikora** [maxplanck-ie/snakepipes#228]
for the case where merging bams is required. happens occasionally with WGBS/Boehm dpt projects. potentially for internal use only.

**Comment by katsikora** [comment]
added to WGBS in PR#239

**Comment by katsikora** [comment]
added to RNAseq in PR#275 - affects the MPI_internal_branch only

**Comment by dpryan79** [comment]
Added and tested:

 - [ ] ChIP-seq
 - [ ] ATAC-seq
 - [ ] RNA-seq
 - [x] WGBS

I assume scRNA-seq will be skipped for now.

**Comment by steffenheyne** [comment]
Chip-seq also has it in the MPI_internal_branch, ATAC can be done similarily

**Comment by katsikora** [comment]
these tested entry points are available on the MPI_internal_branch

when are we ready to merge the branch into develop?

**Comment by dpryan79** [comment]
I'm :+1: on merging.

**Comment by katsikora** [comment]
implemented in PR#373
