### ISSUE TITLE
race condition for the ChIP-seq workflow when running on a multi-CPU node because MACS2 is installed as a zipped .egg

### ISSUE THREAD

**Issue by razsultana** [maxplanck-ie/snakepipes#229]
First of all, congratulations on a robust and flexible workflow collection!
I was going to build my own set of snakemake-based workflows, when I stumbled on your project, so I decided to give it a try instead.

When running though a ChIP-seq analysis with multiple samples (requiring then to run more than one instance of the `macs2` package and in my case, on the same machine - although this problem would occur on a cluster if the egg cache is in a shared directory), i.e.:
```bash
ChIP-seq -d analysis mm10_gencode_m17 sampleSheet.yaml --single-end --local --jobs 16 -c chipseq.yaml
```

I ran into a race condition:
```bash
cat ChIP-seq_run-1.log|grep -A15 'RuleException'|head -5
RuleException:
CalledProcessError in line 78 of /opt/conda/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/rules/MACS2.snakefile:
Command 'source activate /opt/conda/envs/186e6bb4bb1494b6f966936fc9359052; set -euo pipefail;  
            macs2 callpeak -t filtered_bam/SRR524837.filtered.bam -c filtered_bam/SRR524833.filtered.bam -f BAM -g 2652783500 --keep-dup all --outdir MACS2                 --name SRR524837.filtered.BAM --nomodel --extsize 200  > MACS2/logs/MACS2.SRR524837.filtered.out 2> MACS2/logs/MACS2.SRR524837.filtered.err ' returned non-zero exit status 1.
```

Looking at the .err file in the log (unfortunately I lost the log file version that had the error having since fixed it), it was clear that the error was generated by the fact that the MACS2 package was installed as a zipped .egg file and when two jobs were trying to use this package simultaneously (similar but not identical to the problem described in this SO question https://stackoverflow.com/questions/2192323/what-is-the-python-egg-cache-python-egg-cache).
The error message was hinting that the directory `~/.cache/Python-Eggs/MACS2-2.1.1.20160309-py2.7-linux-x86_64.egg-tmp/MACS2/IO/` already existed, therefore pointing to the race condition. 

This issue can be fixed either by:
1. installing the MACS2 package as an unzipped .egg or 
2. by setting the `PYTHON_EGG_CACHE` to a job-specific directory

The first approach can be accomplished by changing the code that installs MACS2 at one of these levels (as described in the best solution to this SO question https://stackoverflow.com/questions/25816689/configure-setup-py-to-install-a-package-unzipped?answertab=votes#tab-top):
1. the MACS2 source code (https://github.com/taoliu/MACS): fork the repository, change the `setup.py` script by adding `zip_safe=False` to the `setup()` function call
2. the bioconda MACS recipe (https://github.com/bioconda/bioconda-recipes/blob/master/recipes/macs2/build.sh), adding a sed call that modifies the `setup.py` script and adds the above option to the `setup()` call
3. the `snakePipes createEnvs` code, by installing MACS2 using `pip install MACS2==2.1.1.20160309` instead of `conda install MACS2==2.1.1.20160309`

The second approach would involve modifying `https://github.com/maxplanck-ie/snakepipes/blob/master/shared/rules/MACS2.snakefile#L106`, adding something like this to the rule MACS2, for the shell command:
```bash
        shell:
            'mycache=`mktemp`; export PYTHON_EGG_CACHE=$mycache' +
```

I ended up using the first approach, the third option, i.e. uninstalling the MACS2 package in the ChIP-seq environment and then manually installing it using pip instead - which created an un-zipped local package. 

Hope this helps to make the ChIP-seq workflow a bit more robust.

**Comment by dpryan79** [comment]
I'll make a note to fix the MACS2 recipe in bioconda, since zip-safe packages could generally elicit this.

**Comment by dpryan79** [comment]
I've updated the macs2 recipe that bioconda uses and a new macs2 release should then be available in about an hour (depending on the circleci backlog). The new build avoids using zipped eggs, so this problem should then not occur.

**Comment by razsultana** [comment]
Great! (I think you meant above "the non-zip-safe packages could elicit this." )
I re-installed the MACS2 package in the ChIP-seq environment with `conda` install and the updated recipe (with  `python setup --single-version-externally-managed`) worked by installing the un-zipped package.

**Comment by dpryan79** [comment]
Yup, that’s what I meant.
