### ISSUE TITLE
Missing notification that RNA-seq --DE requires --mode alignment 

### ISSUE THREAD

**Issue by mirax87** [maxplanck-ie/snakepipes#245]
In order to use the RNA-seq with the differential analysis from DEseq2 `--DE <sample sheet>`, `--mode alignment` is required. 

The user should be notified about this dependency as by default RNA-seq runs in alignment_free mode.

**Comment by dpryan79** [comment]
`alignment-free`, not `alignment_free`. The problem seems to be that the mode isn't properly checked. For example, one can specify `mapping-free` and get STAR but not DESeq2. If we checked the mode properly then this wouldn't occur.

**Comment by dpryan79** [comment]
An appropriate error message is now produced in `develop`.
