### ISSUE TITLE
Global option to keep temporary output

### ISSUE THREAD

**Issue by mirax87** [maxplanck-ie/snakepipes#252]
A global option to keep temp()'ed files would be useful. The global option could become a default parameter in the workflow wrappers.

Background
I just ran into the problem that --snakemake_options='--notemp' overwrites the default --snakemake_options. Result was nothing worked anymore, and all kinds of searching happened. Thanks @dpryan79 for figuring out the problem.

**Comment by dpryan79** [comment]
Relatedly, we really need a strong warning to the tune of, "Warning! Here be dragons!" in the `--snakemake_options` help.

**Comment by dpryan79** [comment]
This is now implemented in `develop`.
