### ISSUE TITLE
createIndices caused Unable to locate a modulefile for 'slurm'

### ISSUE THREAD

**Issue by mictadlo** [maxplanck-ie/snakepipes#278]
Hi,
I ran `createIndices` in the below way but I got `ModuleCmd_Load.c(208):ERROR:105: Unable to locate a modulefile for 'slurm'`. Our cluster is using PBSpro and therefore I would like to use only one compute node.  How can I remove the slurm error?
```
snakepipes> createIndices --genomeURL /scratch/waterhouse_team/benth/dbg2olc-40x/scaffolds_FINAL.fasta -o snakePipes-output --tempdir snakePipes-tmp dbg2olc-40x
Building DAG of jobs...
Using shell: /bin/bash
Provided cluster nodes: 5
Job counts:
	count	jobs
	1	all
	1	bowtie2Index
	1	bwaIndex
	1	bwamethIndex
	1	computeEffectiveGenomeSize
	1	createGenomeFasta
	1	fastaIndex
	1	hisat2Index
	1	make2bit
	1	starIndex
	10

[Sun Oct 14 01:10:10 2018]
rule createGenomeFasta:
    output: /lustre/scratch/waterhouse_team/benth/dbg2olc-40x/snakepipes/snakePipes-output/genome_fasta/genome.fa
    jobid: 7

ModuleCmd_Load.c(208):ERROR:105: Unable to locate a modulefile for 'slurm'
/bin/sh: SlurmEasy: command not found
Error submitting jobscript (exit code 127):

Job failed, going on with independent jobs.
Exiting because a job execution failed. Look above for error message
Complete log: /lustre/scratch/waterhouse_team/benth/dbg2olc-40x/snakepipes/snakePipes-output/.snakemake/log/2018-10-14T011009.735531.snakemake.log
Error: snakemake returned an error code of 1, so processing is incomplete!
```
Thank you in advance,

Michal

**Comment by dpryan79** [comment]
Please see the section on [configuring your cluster](https://snakepipes.readthedocs.io/en/latest/content/setting_up.html#configure-your-cluster). In short, you'll need to modify the cluster.yaml file to suite how you submit jobs.

**Comment by mictadlo** [comment]
Hi,
Unfortunately, I could not figure out how to change`snakePipes/shared/cluster.yaml` in order not to use SLURM and only use one compute node?

Thank you in advance,

Michal

**Comment by dpryan79** [comment]
Change the “snakemake_cluster_cmd” line to be appropriate for your cluster. Ask you cluster admin for more details.

**Comment by steffenheyne** [comment]
Hi Michal,
if you just want to use one computer, each workflow has the option `--local` By that, snakePipes (and Snakemake) ignores any cluster configuration. With `-j` one can then control the max number of cores used on one machine.

Is that what you want to achieve?

**Comment by mictadlo** [comment]
Hi @steffenheyne , Yes that is what I tried to achieve.
