### ISSUE TITLE
HiC setup

### ISSUE THREAD

**Issue by mictadlo** [maxplanck-ie/snakepipes#282]
Hi,
I am new to HiC and we would like to retrieve 19 chromosomes. Unfortunately, I do not know what the following options mean?

```
## is the Matrix RF resolution?
RF_resolution: true
# bin size in base pairs, if RF resolution is not required
bin_size: 10000
# build matrix only for given region
restrict_region:
# Create files with N merged bins (0 = No)
nbins_toMerge: 19
# shall we merge the samples?
merge_samples: true
# parameters for hicFindTADs
tadparams: '--thresholdComparisons 0.01'
distVsCount: true
distVsCountParams:
chromosomes: 19
# a .tsv file contains names and replicates of samples.
sample_info:
```

Thank you in advance,

Michal

**Comment by LeilyR** [comment]
RF(restriction fragment) resolution: bin sizes are the same as restriction fragments length
enzyme: which restriction enzyme was used
bin size: the length of the window that you choose on the gnome
merge_sample: if you want to merge to contact matrix
nbins_toMerge: if you would like to merge several bins into one
tamparams: parameters you would like to set for tad calling. You might want to have a look at hicExplorer documentation for that since the pipeline uses hicFindTADs
chromoses: in case you only want to make the contact matrix and do the analysis over certain chromosomes
distVsCount: generate a plot of distance vs. counts
distVsCountParams: setting the paramters for distVsCount plot. Check hicPlotDistVsCounts documentation.
sample_info: this is needed if you want to merge_samples. It tells the pipeline which samples should be merged together. For example all the wild types are merged together and all the knock downs together

**Comment by mictadlo** [comment]
I have the following Hi-C data
```
> ls -1
N_Ben_HiC2.R1.fq.gz
N_Ben_HiC2.R2.fq.gz
N_Ben_HiC4.R1.fq.gz
N_Ben_HiC4.R2.fq.gz
```
Do I have to fill any `sample_info`?
I assume I have to set `merge_sample` true.

What is the difference between `bin size` and `nbins_toMerge` and `chromoses`? I would like to recover from my assembly 19 chromosomes? What should I do?

Thank you in advance,

Michal

**Comment by dpryan79** [comment]
19 chromosomes or chromosome 19?

**Comment by LeilyR** [comment]
merging samples give you a less sparse matrix to analyze, which seems what one would like to see, BUT  first check if your samples are correlated otherwise merging just generate artifact. So, at the end it is you who decide if wants to merge or not, but if you decide to merge, indeed you need to fill the sample_info.
bin_size is the size of window you want to check to fill in the contact matrix nbins_toMerge merge several of your set bins together. 
chromsomes: are the chromosomes number you would like to generate matrix for.

**Comment by mictadlo** [comment]
@leilyR How do I check if my samples are correlated otherwise merging just generate artifact? Is there a way to calculate automatically the other parameters?

@dpryan79 I would like to get 19 chromosomes.

**Comment by dpryan79** [comment]
You'll need to list the 19 chromosomes you want then. I think they need to be comma separated.

**Comment by LeilyR** [comment]
As for correlation, first of all you better look for technical stuffs, like the protocols were used to generate data, are they replicates?, conditions(wt,kc,etc.) and so on. Second of all you can compute the correlation between samples  using distVsCount (from the hic pipeline), hicCorrelate from the hicExplorer package or any other other software of your choice which does that.

**Comment by mictadlo** [comment]
@LeilyR  :
- Hi-C data has been made from the protocol of Rao et al. 2014 (A 3D Map of the Human Genome at Kilobase Resolution Reveals Principles of Chromatin Looping) 
- Yes, they are two replicates as I know. 
- The enzyme used is MboI.

@dpryan79 : To which parameter do I attach the list with 19 chromosomes?

**Comment by dpryan79** [comment]
The chromosomes are for the `chromosomes:` parameter, as you correctly surmised above.

**Comment by mictadlo** [comment]
What would be settings for?

- Hi-C data has been made from the protocol of Rao et al. 2014 (A 3D Map of the Human Genome at Kilobase Resolution Reveals Principles of Chromatin Looping) 
- The enzyme used is MboI.
- they are two replicates:

```
> ls -1
N_Ben_HiC2.R1.fq.gz
N_Ben_HiC2.R2.fq.gz
N_Ben_HiC4.R1.fq.gz
N_Ben_HiC4.R2.fq.gz
```
Thank you in advance.

Michal

**Comment by LeilyR** [comment]
1. set the read file suffixes in you configuration yaml file to what fits your input data by modifying `reads:` 
2. trimming is up to you, you could check your read quality and decide about that
3. the same goes for the resolution, you are the one who decides if he wants to go for fixed bin size resolution e.g. 100kb or wants to get a higher RF based resolution. you could give each of them a try to see which results a better presentation for your data. 
4. Although your data are replicates I would still check for the correlation between them , as I have explained it to you before, if they look nicely correlated then merge the  samples too.
5. For TAD calling first try the default parameters but then tweak them a bit to see when you get the best presentation for the TADs

**Comment by mictadlo** [comment]
I would like to try to run it with the 2 replicates. How the `sample_info` file should look like
for this files:
```
> ls -1
N_Ben_HiC2.R1.fq.gz
N_Ben_HiC2.R2.fq.gz
N_Ben_HiC4.R1.fq.gz
N_Ben_HiC4.R2.fq.gz
```
and are the remaining settings correct?

```
pipeline: hic
outdir:
configfile:
cluster_configfile:
local: False
max_jobs: 5
## directory with fastq files
indir: /scratch/hic-data
## preconfigured target genomes (mm9,mm10,dm3,...) , see /path/to/snakemake_workflows/shared/organisms/
## Value can be also path to your own genome config file!
genome: dbg2olc-40x
## FASTQ file extension (default: ".fastq.gz")
ext: '.fq.gz'
## paired-end read name extension (default: ['_R1', "_R2"])
reads: ['.R1', '.R2']
mapping_prg: BWA
## Number of reads to downsample from each FASTQ file
downsample:
## Options for trimming and fastqc
trim: False
trim_prg: cutadapt
trim_options:
fastqc: false
verbose: False
## is the Matrix RF resolution?
RF_resolution: false
# which enzyme was used
enzyme: MboI
# bin size in base pairs, if RF resolution is not required
bin_size: 100000
# build matrix only for given region
restrict_region:
# Create files with N merged bins (0 = No)
nbins_toMerge: 0
# shall we merge the samples?
merge_samples: false
# parameters for hicFindTADs
tadparams: '--thresholdComparisons 0.01'
distVsCount: false
distVsCountParams:
noTAD: false
noCorrect: false
chromosomes: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
# a .tsv file contains names and replicates of samples.
sample_info: ????
```
Thank you in advance,

Michal

**Comment by steffenheyne** [comment]
Hi Michal,
go ahead and play around with the pipeline and produce some results first. There is no need to alter every parameter in the config.yaml file. The defaults are reasonable. And the most important parameters you can alter via the Hi-C wrapper script. If you get an error, check obvious mistakes and come back if you cannot get around with it. Asking help in an open source community also requires some own efforts as all our resources are limited and we usual have to deal at the same time with many other things.

Thanks,
steffen

**Comment by LeilyR** [comment]
If you don't  merge the samples you don't need sample_info

**Comment by mictadlo** [comment]
Thank you for all the explanations.
