### ISSUE TITLE
flagstat_report_all.tsv is of no use

### ISSUE THREAD

**Issue by vivekbhr** [maxplanck-ie/snakepipes#285]
There's no use of sambamba flagstat report table. MultiQC picks up on sambamba reports and the numbers are in the multiQC report. The QC_report folder also contains the same table. I would be removing both the .tsv files unless objected.

**Comment by steffenheyne** [comment]
actually the file `QC_report/QC_report_all.tsv` is build from the sambamba file `flagstat_report_all.tsv`
so we cant't remove this
