### ISSUE TITLE
WGBS : move reference genome conversion to createIndices

### ISSUE THREAD

**Issue by vivekbhr** [maxplanck-ie/snakepipes#286]
and get rid it --convref argument from the wrapper

**Comment by dpryan79** [comment]
@katsikora Is this still being optionally done in the pipeline?

**Comment by katsikora** [comment]
so the convref argument is still there and working

**Comment by dpryan79** [comment]
OK, I'll just remove the option in my next PR. The remaining code can stay of course.

**Comment by katsikora** [comment]
I guess there might be need for some code cleanup afterwards, but removing the option should work for now
