### ISSUE TITLE
Handle UMI deduplication in the DNA-seq pipeline

### ISSUE THREAD

**Issue by dpryan79** [maxplanck-ie/snakepipes#289]
This is mostly for RELACS, which now uses 4 base UMIs. This should obviously be optional and the presumption is that UMIs were already moved to the read headers.

**Comment by LeilyR** [comment]
I have implemented that (`umidedup` branch), however I haven't added it to develop yet since at the moment it only work on a fastq file which the umi is already added as part of the read name. I was thinking to an option to do that too if user asks for it. What do you think?

**Comment by dpryan79** [comment]
@LeilyR Can this be closed now? I think you've merged everything into develop.

**Comment by dpryan79** [comment]
This is all in `develop` now
