### ISSUE TITLE
KeyError in line 38 of snakePipes/workflows/HiC/internals.snakefile: 'MboI'

### ISSUE THREAD

**Issue by mictadlo** [maxplanck-ie/snakepipes#292]
Hi,
While running this command ` HiC dbg2olc40x -i /work/waterhouse_team/All_RawData/Benth/USA_ABombarely/Nbenthamiana_HiC/ -o /scratch/waterhouse_team/benth/dbg2olc-40x/snakepipes/snakePipes` I got:

```
Failed to create temp dir under temp path prefix (/scratch/waterhouse_team/benth/dbg2olc-40x/snakepipes/snakePipes-tmp)! Try fallback: /scratch/waterhouse_team/benth/dbg2olc-40x/snakepipes/snakePipes/ ...
KeyError in line 38 of /lustre/scratch/waterhouse_team/benth/dbg2olc-40x/snakepipes/snakePipes/workflows/HiC/internals.snakefile:
'MboI'
  File "/lustre/scratch/waterhouse_team/benth/dbg2olc-40x/snakepipes/snakePipes/workflows/HiC/Snakefile", line 34, in <module>
  File "/lustre/scratch/waterhouse_team/benth/dbg2olc-40x/snakepipes/snakePipes/shared/rules/hicexplorer.snakefile", line 8, in <module>
  File "/lustre/scratch/waterhouse_team/benth/dbg2olc-40x/snakepipes/snakePipes/workflows/HiC/internals.snakefile", line 38, in get_restriction_seq
Error: snakemake returned an error code of 1, so processing is incomplete!
```
How to I specify Mbol as enzyme?

Thank you in advance,

Michal

**Comment by LeilyR** [comment]
You don't need to always change the config files. almost all you need could be possible to be altered from the command line. MboI is the same as DpnII which is already in the dictionary, also in case in future you had an enzyme which was not in the dictionary you would be able to add it to it. For the moment just use --enzyme DpnII in your command line

**Comment by mictadlo** [comment]
Thank you.
