### ISSUE TITLE
Seems like config file does not overwrite defaults but append

### ISSUE THREAD

**Issue by mirax87** [maxplanck-ie/snakepipes#294]
I ran RNA-seq with a config yaml providing `mode alignment,deepTools_qc` and snakePipes RNA-seq tried to run exactly those modes - and alignment-free. 
Solution to run `--mode alignment,deepTools` exclusively was to provide it through the wrapper directly.

It seems like config file parameters are appended to the defaults, instead of overwriting. 

Maybe related, I tried to modify `star_options:` through the same config yaml, but it did not seem to propagate to `rule STAR`, as the added option was not reported in the STAR log file at `<STAR>/<sample>/<sample>.Log.out`

**Comment by katsikora** [comment]
Hi Michael,

what do you mean with 'append'? Like you see two identical keys in your defaults.yaml in your output dir with different values assigned? This would surely throw an error (alongside duplicate keys or sth).

Any arguments passed to the wrapper overwrite any configs provided...

You can check the actual STAR command ran on your files e.g. by:

samtools view -H my.bam | grep @PG

Best,

Katarzyna

**Comment by mirax87** [comment]
So this is the call I am executing, i.e. RNA-seq with default parameters and a config file `RNA-seq.yaml`. 
`RNA-seq -c RNA-seq.yaml -i <fastq_dir> -o <outdir> dm6`

I changed the following fields in the *input* config file, i.e. `RNA-seq.yaml`
* mode: alignment,deepTools_qc
* star_options: --outSAMstrandField intronMotif

Now checking the *output* in `<outdir>/RNA-seq.config.yaml`
* mode: alignment-free,deepTools_qc,alignment
* star_options: --outSAMstrandField intronMotif

`star_options` seems successfully stored. However `mode` was appended by `alignment-free`, which is the default for snakePipes RNA-seq. 

Thus, I believe that the content in the config file does not overwrite the default parameters for `mode`, but appends the default. 

My expectation would be that config file overwrites the default parameters, whereas the command-line parameters overwrite everything.

**Comment by steffenheyne** [comment]
the default of the command-line option takes precedence over a value in a provided config file. and although the default does not contains "alignment", it gets added by the wrapper automatically as it is needed for deepTools_qc. 

The thing with the precedence of a not given default of a cmdl-option is odd and we need to change that somehow. however this is not easy as we have to identify the really given paramters when a wrapper is called. so far I havn't found any argparse option for this...

**Comment by dpryan79** [comment]
This should now work for all of the tools. The trick was basically parsing the command line twice in cases where someone uses `-c` (note `-c` on the first go, update the defaults from it, then reparse given the updated defaults).
