### ISSUE TITLE
More lax handling of annotation files

### ISSUE THREAD

**Issue by dpryan79** [maxplanck-ie/snakepipes#299]
At the moment we have an undocumented requirement that `ensembl` or `gencode` appear in the path to the GTF file in the RNAseq/scRNAseq workflows. We can keep the current handling of that, but we should add a proper `else` for when neither are the case in `filter_annotation`.

**Comment by steffenheyne** [comment]
right, this should be more generic

basically the current "ensembl" case could also act (as template) for the missing "else" part. already there only `gene_id` and `transcript_id` are really required. 

In case of a missing `gene_name`/ `transcript_name` these entries are set to the `gene_id` or `transcript_id` and the biotypes to `unknown_gene_biotype` or `unknown_tx_biotype`

at the end these transformations are made to get some bed file with some fixed additional columns out of the gtf file. (which in turn are needed for the rules rule like `annotation_bed2t2g` and `annotation_bed2symbol`)

**Comment by steffenheyne** [comment]
this is now fixed by https://github.com/maxplanck-ie/snakepipes/pull/321
