### ISSUE TITLE
Use --restart-times and modify RAM?

### ISSUE THREAD

**Issue by dpryan79** [maxplanck-ie/snakepipes#315]
Usually the memory limits suffice, but when they don't on a shared installation it can be tough for users to increase memory requirements. One option to get around that would be to add `--restart-times 2` and then a lambda to increase memory allotment by a scalar. This is at least possible if the memory requirements are listed in `resources:`, I don't know if that's possible with a config file. It remains to be determined if that's even desirable, of course, since odds are if something fails there's a different reason half the time (usually an unreasonable setting).

**Comment by katsikora** [comment]
I notice that the restart wipes out the files specified under rule's 'log' attribute -> this makes debugging a bit more difficult or at least longer...

**Comment by dpryan79** [comment]
Yeah, it's a double edged sword. It also makes it less obvious that we need to raise limits, but of course our limits are then a bit more flexible. I mostly bring it up since I know nf-core is using that.

**Comment by dpryan79** [comment]
Since we've moved away from having STAR sort the BAM files I'm hoping this is less of an issue. I'll close this for now then.
