### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by vivekbhr** [maxplanck-ie/snakepipes#34]
Integrate Travis CI for established workflows (This would take some effort) ..

- [x] Add travis (basic)
- [ ] Add test datasets
- [ ] Turn on testing (IDK if it's possible since it means installing the dependencies in travis as well)

**Comment by dpryan79** [comment]
For whatever it's worth, TravisCI is now testing PEP8 conformance. I don't know how realistic any further testing on Travis can be, jobs time out after an hour...

**Comment by vivekbhr** [comment]
test dataset is a seperate issue so I am closing it
