### ISSUE TITLE
HiC no sampleSheet has been proveded

### ISSUE THREAD

**Issue by mictadlo** [maxplanck-ie/snakepipes#352]
HI,
I have got the following problem:

```
RuleException:
CalledProcessError in line 137 of /work/waterhouse_team/miniconda2/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/rules/hicexplorer.snakefile:
Command 'source activate /work/waterhouse_team/miniconda2/envs/6b4112b79f7eef4336843e9c4ed82e42; set -euo pipefail;  hicCorrectMatrix diagnostic_plot -m HiC_matrices/N_Ben_HiC4_bs.h5 -o HiC_matrices/QCplots/N_Ben_HiC4_bs_diagnostic_plot.pdf  --chromosomes 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 &> HiC_matrices/QCplots/N_Ben_HiC4_bs_mad_threshold.out ' returned non-zero exit status 1.
  File "/work/waterhouse_team/miniconda2/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/rules/hicexplorer.snakefile", line 137, in __rule_diagnostic_plot
  File "/work/waterhouse_team/miniconda2/envs/snakePipes/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job diagnostic_plot since they might be corrupted:
HiC_matrices/QCplots/N_Ben_HiC4_bs_mad_threshold.out
Job failed, going on with independent jobs.
[Sun Dec  2 10:41:59 2018]
Error in rule diagnostic_plot:
    jobid: 8
    output: HiC_matrices/QCplots/N_Ben_HiC2_bs_diagnostic_plot.pdf, HiC_matrices/QCplots/N_Ben_HiC2_bs_mad_threshold.out
    conda-env: /work/waterhouse_team/miniconda2/envs/6b4112b79f7eef4336843e9c4ed82e42

RuleException:
CalledProcessError in line 137 of /work/waterhouse_team/miniconda2/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/rules/hicexplorer.snakefile:
Command 'source activate /work/waterhouse_team/miniconda2/envs/6b4112b79f7eef4336843e9c4ed82e42; set -euo pipefail;  hicCorrectMatrix diagnostic_plot -m HiC_matrices/N_Ben_HiC2_bs.h5 -o HiC_matrices/QCplots/N_Ben_HiC2_bs_diagnostic_plot.pdf  --chromosomes 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 &> HiC_matrices/QCplots/N_Ben_HiC2_bs_mad_threshold.out ' returned non-zero exit status 1.
  File "/work/waterhouse_team/miniconda2/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/rules/hicexplorer.snakefile", line 137, in __rule_diagnostic_plot
  File "/work/waterhouse_team/miniconda2/envs/snakePipes/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job diagnostic_plot since they might be corrupted:
HiC_matrices/QCplots/N_Ben_HiC2_bs_mad_threshold.out
Job failed, going on with independent jobs.
[Sun Dec  2 10:42:09 2018]
Finished job 9.
7 of 16 steps (44%) done
Exiting because a job execution failed. Look above for error message
Complete log: /lustre/scratch/waterhouse_team/benth/dbg2olc-40x/snakePipes/snakePipes-output/.snakemake/log/2018-12-01T073211.400784.snakemake.log
no sampleSheet has been proveded
Error: snakemake returned an error code of 1, so processing is incomplete!
```

`default.yaml` looks like this:

```
pipeline: hic
outdir: /scratch/waterhouse_team/benth/dbg2olc-40x/snakepipes/snakePipes
configfile:
cluster_configfile:
local: False
max_jobs: 5
## directory with fastq files
indir: /scratch/waterhouse_team/benth/dbg2olc-40x/snakepipes/snakePipes/workflows/HiC/hic-fq
## preconfigured target genomes (mm9,mm10,dm3,...) , see /path/to/snakemake_workflows/shared/organisms/
## Value can be also path to your own genome config file!
genome: dbg2olc40x
## FASTQ file extension (default: ".fastq.gz")
ext: '.fastq.gz'
## paired-end read name extension (default: ['_R1', "_R2"])
reads: ['.R1', '.R2']
mapping_prg: BWA
## Number of reads to downsample from each FASTQ file
downsample:
## Options for trimming and fastqc
trim: False
trim_prg: cutadapt
trim_options:
fastqc: false
verbose: False
## is the Matrix RF resolution?
RF_resolution: false
# which enzyme was used
enzyme: DpnII
# bin size in base pairs, if RF resolution is not required
bin_size: 100000
# build matrix only for given region
restrict_region:
# Create files with N merged bins (0 = No)
nbins_toMerge: 0
# shall we merge the samples?
merge_samples: false
# parameters for hicFindTADs
tadparams: '--thresholdComparisons 0.01'
distVsCount: false
distVsCountParams:
noTAD: false
noCorrect: false
chromosomes: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
# a .tsv file contains names and replicates of samples.
sample_info:
```

This is the command `HiC -i hic-fq -o snakePipes-output -c defaults.yaml --local -j 10 --tempdir TEMPDIR --enzyme DpnII dbg2olc40x` how I executed it:

What did I miss?

Thank you in advance

Michal

**Comment by dpryan79** [comment]
In 1.1.1 we standardized all of the various sample sheet options to the same argument across all pipelines (it's less confusing that way). So you want the `--sampleSheet` option, which corresponds to the `sampleSheet` (rather than `sample_info`, which is no longer used) option in `defaults.yaml`.

**Comment by dpryan79** [comment]
Oh the `no sample sheet` thing isn't related to the error, it's just information. Please check the log file for the failed step `HiC_matrices/QCplots/N_Ben_HiC4_bs_mad_threshold.out`

**Comment by LeilyR** [comment]
Hi Michal,
I have run the same command as you did and can not produce that error .

**Comment by LeilyR** [comment]
I have also tested the pipeline on few chromosomes and still couldn't produce  the error you have got.

**Comment by LeilyR** [comment]
It really depends on what you are interested in. It might be useful to check the hicexplorer modules and their documentation. For example, if you are interested in TADs you could plot them with hicPlotTADs and see if the default parameters of the pipeline suits your data or you need to tweak them. hicexplorer modules provide you with the opportunity of extracting the region of interest (your 19 chr for example). 
Regarding to your hicQC, there might be a bug in hicQC computation of hicexplorer that you got 0% dangeling end, self ligation and self circle. We will look for it and fix it if there is any.
If you would like to share your data that is also fine by us. You can anonymize it if you like and can open an account on our galaxy server (deeptools.ie-freiburg.mpg.de) and FTP your data there  or you can share it elsewhere.

**Comment by mictadlo** [comment]
Hi all, 
I just wonder whether you have recevied my files by email.

Thank you in advance.

Michal

**Comment by LeilyR** [comment]
Yes, we have. I will update you as soon as I will run the pipeline on it.

**Comment by LeilyR** [comment]
I have checked your data.  Your reference genome includes only scaffolds while you ask for chr 1 to 19 which basically don't exist.  That is why your pipeline fails when you mention the chromosomes names.

**Comment by mictadlo** [comment]
If I would use contings rather than scaffolds then would I get the 19 chromosome names?

I thought I could combine a denovo genome assembly with HiC data and get in my case 19 chromosome bins. If snakePipe does not do it then could you please let me know which software does it? 

Thank you in advance.

Michal

**Comment by steffenheyne** [comment]
Whatever you provide as reference genome (contigs/scaffolds/...), the data is mapped against this. if you provide a refernece with 19 chromosomes, then you get data mapped and processed on that. 
The Hi-C snakepipes pipeline is not a genome assembly pipeline. Hi-C pipelines calls TADs and provides matrices with contacts. 
https://snakepipes.readthedocs.io/en/latest/content/workflows/HiC.html#hic
You can build upon this to "order" your scaffolds in a better way.

**Comment by LeilyR** [comment]
Hi Michal,
There is not different between contigs and scaffolds for the pipeline. 
The pipeline is not doing de novo assembly but of course you can use the contact matrix generated by the pipeline and process it further to find the bins with the highest contact.
