### ISSUE TITLE
Missing input files (ref genome) and rules that are not present in the Snakefile

### ISSUE THREAD

**Issue by jbalberge** [maxplanck-ie/snakepipes#368]
Hi,
I have a conda env `sp` for snakePipes with pre-made indices for human, but I don't manage to get the WGBS pipeline working.

```
(sp) [jbalberge@login-01 ecn]$ WGBS -i fastq_wgbs_mm/ -o WGBS_M11959/ -c fastq_wgbs_mm/defaults.yaml hg38
localrules directive specifies rules that are not present in the Snakefile:
        FASTQ1
        FASTQ2

Building DAG of jobs...
MissingInputException in line 122 of /sandbox/users/jbalberge/.conda/envs/sp/lib/python3.6/site-packages/snakePipes/shared/rules/WGBS.snakefile:
Missing input files for rule map_reads:
/sandbox/shares/ecn/GRCh38_gencode_release29/BWAmethIndex/genome.fa
Error: snakemake returned an error code of 1, so processing is incomplete!
```

Here is the configfile:

```
outdir: /sandbox/shares/ecn/WGBS_M11959/
configfile: /sandbox/users/jbalberge/.conda/envs/sp/lib/python3.6/site-packages/snakePipes/shared/defaults.yaml
cluster_configfile: /sandbox/users/jbalberge/.conda/envs/sp/lib/python3.6/site-packages/snakePipes/shared/cluster.yaml
local: False
max_jobs: 12
nthreads: 48
## directory with fastq or bam files
indir: /sandbox/shares/ecn/fastq_wgbs_mm/
## directory with fastqc files for auto quality trimming
fqcin: /sandbox/shares/ecn/WGBS_FQC/
## Genome information
genome: hg38
convrefpath:
convRef: False
###list of bed files to process
intList: []
###SNP black list (bed file)
blackList:
###sample Sheet
sampleSheet: /sandbox/shares/ecn/fastq_wgbs_mm/sampleSheet.tsv
###inclusion bounds for methylation extraction
mbias_ignore: auto
## FASTQ file extension (default: ".fastq.gz")
ext: '.fastq.gz'
## paired-end read name extension (default: ['_R1', "_R2"])
reads: [_R1, _R2]
## Number of reads to downsample from each FASTQ file
downsample: 10000000
(...) (default)
```

in /sandbox/users/jbalberge/.conda/envs/sp/lib/python3.6/site-packages/snakePipes/shared/organisms/hg38.yaml : 
```
bwameth_index: "/sandbox/shares/ecn/GRCh38_gencode_release29/BWAmethIndex/genome.fa"
```

in /sandbox/users/jbalberge/.conda/envs/sp/lib/python3.6/site-packages/snakePipes/shared/defaults.yaml : 
```
snakemake_options: ' --use-conda --conda-prefix /sandbox/users/jbalberge/.conda/envs '
tempdir: '/sandbox/shares/ecn/tmp/' 
```

in  : 
```
snakemake_cluster_cmd: qsub -V -v PATH -cwd -S /bin/bash -pe mpi {threads} -l mem={cluster.memory}
```

I must have configured something wrong as the command WGBS fails to find both the ref genome and snakePipes common rules but I didn't find anything. 
Thanks 
JB

**Comment by dpryan79** [comment]
Hmm can you `ln -s /sandbox/shares/ecn/GRCh38_gencode_release29/genome_fasta/genome.fa /sandbox/shares/ecn/GRCh38_gencode_release29/BWAmethIndex/` ? And see if that fixes things?

**Comment by jbalberge** [comment]
Great, it works! Thanks. The symlink existed but was linking to `/data/processing/ryan/`. Can we switch genome.fa links to relative symlinks in future releases ?
Thanks again for your support

**Comment by dpryan79** [comment]
Yes, I think relative symlinks would also be easier, since then you can move things around and everything should still work (after you edit the YAML of course). I'll get this fixed in the next release (hopefully before I leave Germany for vacation) and try to make all of the symlinks relative too. Thanks for the quick reply and good suggestion!

**Comment by dpryan79** [comment]
This should be fixed now, thanks for pointing out the issue!
