### ISSUE TITLE
restrict deepTools:plot*

### ISSUE THREAD

**Issue by thomasmanke** [maxplanck-ie/snakepipes#37]
the deepTools plot* commands should not be run for very many samples (say >20). Tools that can provide tabular output (i.e plotCorrelation) should be restricted to those.

Personally I would vote to remove scatterplot altogether. This can be left for dedicated analysis.

**Comment by steffenheyne** [comment]
see issue https://github.com/fidelram/deepTools/issues/571 for deeptools, 
we can start supporting this properly once deeptools 2.6 is released.

so far I added to develop that most of deeptools qc stuff (tables+plot) is only computed if we have <= 20 samples

**Comment by vivekbhr** [comment]
I would suggest adding the option `--plotType` to the wrappers. `--plotType` could be `png, pdf .. or None`, None would produce no plot.. This would also resolve issue #44 , along with this..

**Comment by steffenheyne** [comment]
yes, this could be a solution...
By this we could also get rid of any hard coded value (20 for some tools currently) up to which number of samples we produce plots
I would wait until deeptools 2.6 is released, then we can code this directly into the  different (deeptools) rules and not in "rule all" like it is now in eg. DNA-mapping   (currently not all deeptools support just output of text tables, in 2.6 all will do)
