### ISSUE TITLE
HiC output loading into JuiceBox

### ISSUE THREAD

**Issue by mictadlo** [maxplanck-ie/snakepipes#371]
Hi, 
Is there a way to load snakePipe's output to [JuiceBox](https://github.com/aidenlab/Juicebox)?

Thank you in advance,

Michal

**Comment by LeilyR** [comment]
the matrices generated by `snakePipes` cannot be directly converted to `.hic` . if you are only interested in JuiceBox for data visualization, you could as well try relevant modules from `hicExplorer` where there is no need of changing the files' format.  However, in a case of assembly, as we have told before snakePipes is not an assembler and you should give your contig files as an input for the juiceBox assembly pipeline.
