### ISSUE TITLE
include estimateReadFiltering (deepTools@develop)

### ISSUE THREAD

**Issue by thomasmanke** [maxplanck-ie/snakepipes#38]
I frequently run: 
estimateReadFiltering -b Bowtie2/*bam -o metrics.tsv --ignoreDuplicates --minMappingQuality 5 --samFlagExclude 3844 --blackListFileName BL.bed

after mapping. It would be great if this could be always included - possibly with other defaults if you don't like the above.

**Comment by steffenheyne** [comment]
once deeptools 2.6 is released we can integrate this in the workflows, so we keep this open until then....

**Comment by steffenheyne** [comment]
do you have a cmdl for your common usage? ie. which numbers of filtered reads you like to see?

like this?

estimateReadFiltering.py --ignoreDuplicates --samFlagInclude 2 --samFlagExclude 3840 --minMappingQuality 20 --blackListFileName ...

**Comment by LeilyR** [comment]
@thomasmanke is the default ok? It's already on develop (PR #93 )
