### ISSUE TITLE
Conda environment not activated while running DNA-mapping

### ISSUE THREAD

**Issue by ppnin** [maxplanck-ie/snakepipes#386]
Hi -  I seem to have an issue with conda environment (possibly similar to #384). When I run `DNA-mapping`, the environment with `bowtie2` does not activate (at least that's how it looks to me). Here is a part of the log, where it gets stuck:

```
[Thu Feb 14 08:34:39 2019]
rule Bowtie2:
    input: FASTQ/ERR1013031_tr2_R1.fastq.gz, FASTQ/ERR1013031_tr2_R2.fastq.gz
    output: Bowtie2/ERR1013031_tr2.Bowtie2_summary.txt, Bowtie2/ERR1013031_tr2.sorted.bam
    jobid: 19
    benchmark: Bowtie2/.benchmark/Bowtie2.ERR1013031_tr2.benchmark
    wildcards: sample=ERR1013031_tr2
    threads: 10

Activating conda environment: /home/pavle/miniconda3/envs/f417ca0eda671a6a276a01afcb820a70
/bin/bash: activate: No such file or directory
/bin/bash: samtools: command not found
/bin/bash: samtools: command not found
[Thu Feb 14 08:34:39 2019]
Error in rule Bowtie2:
    jobid: 19
    output: Bowtie2/ERR1013031_tr2.Bowtie2_summary.txt, Bowtie2/ERR1013031_tr2.sorted.bam
    conda-env: /home/pavle/miniconda3/envs/f417ca0eda671a6a276a01afcb820a70

RuleException:
CalledProcessError in line 28 of /home/pavle/miniconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/rules/Bowtie2.snakefile:
Command 'source activate /home/pavle/miniconda3/envs/f417ca0eda671a6a276a01afcb820a70; set -euo pipefail;  bowtie2 -X 1000 -x /home/pavle/Documents/Data/HumanGenome/indicesTest/BowtieIndex/genome -1 FASTQ/ERR1013031_tr2_R1.fastq.gz -2 FASTQ/ERR1013031_tr2_R2.fastq.gz  --fr --rg-id ERR1013031_tr2 --rg CN:mpi-ie_deep_sequencing_unit --rg DS:ERR1013031_tr2 --rg PL:ILLUMINA --rg SM:ERR1013031_tr2 -p 10 2> Bowtie2/ERR1013031_tr2.Bowtie2_summary.txt | samtools view -Sb - | samtools sort -m 2G -T ${TMPDIR}ERR1013031_tr2 -@ 2 -O bam - > Bowtie2/ERR1013031_tr2.sorted.bam ' returned non-zero exit status 127.
  File "/home/pavle/miniconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/rules/Bowtie2.snakefile", line 28, in __rule_Bowtie2
  File "/home/pavle/miniconda3/envs/snakePipes/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job Bowtie2 since they might be corrupted:
Bowtie2/ERR1013031_tr2.Bowtie2_summary.txt, Bowtie2/ERR1013031_tr2.sorted.bam
Job failed, going on with independent jobs.
```   

I see that both `samtools` and `bowtie2` are in  `/miniconda3/envs/f417ca0eda671a6a276a01afcb820a70/bin`, so my guess is that for some reason the env does not activate.  

Few days ago I ran `DNA-mapping` without a problem, and there have been no changes on my machine.  Any idea how to deal with this conda env issue?

**Comment by steffenheyne** [comment]
strange, and probably more a snakemake/conda problem...

Did you downgrade conda version as one option discussed in #384 ? I would suggest this here as well.

Are your environments on a NFS/shared filesystem? 
You submit snakemake jobs to a cluster? 
One thing to test here could be a pure local version, ie. all envs etc are local and you also provide --local option to DNA-mapping...

Can you activate same env manually?

**Comment by ppnin** [comment]
Yeah, I was afraid that it could be a snakemake/conda problem..

I haven't downgraded my conda version as both `createIndices` and `DNA-mapping` worked in the end, and i thought that the env issue was resolved.  

No clusters or shared filesystems - I run everything locally on my machine, with the `--local` option in all procedures. And yes, I can activate that same env manually. 

Alright, so you suggest that I downgrade conda to 4.5.13 (as discussed) and re-install snakePipes?

**Comment by steffenheyne** [comment]
yeah, so far this is the only thing I can imagine

**Comment by ppnin** [comment]
Ok, i downgraded conda to 4.5.13.   Btw,  when I installed `snakePipes` using 
`conda install -c mpi-ie snakepipes`  conda reported a SafetyError, related to `.../shared/defaults.yaml` :  

```
Downloading and Extracting Packages
botocore-1.12.94     | 3.2 MB    | ################################################################################################# | 100% 
pyrsistent-0.14.10   | 87 KB     | ################################################################################################# | 100% 
boto3-1.9.94         | 61 KB     | ################################################################################################# | 100% 
googleapis-common-pr | 34 KB     | ################################################################################################# | 100% 
cffi-1.12.0          | 217 KB    | ################################################################################################# | 100% 
Preparing transaction: done
Verifying transaction: | 
SafetyError: The package for snakepipes located at /home/pavle/miniconda3/pkgs/snakepipes-1.1.2-py_0
appears to be corrupted. The path 'site-packages/snakePipes/shared/defaults.yaml'
has an incorrect size.
  reported size: 621 bytes
  actual size: 237 bytes

```
Is it anything to be worried about?

**Comment by ppnin** [comment]
Right, I looked the file and there was nothing strange about it so i proceeded and installed all snakePipes envs. `DNA-mapping` is working now, I see that the relevant env is activated...hopefully it stays that way.

**Comment by steffenheyne** [comment]
great! 
Don't know how this corruption error can happen. Can you just check if your installed defaults.yaml  file looks like the original one here:
https://github.com/maxplanck-ie/snakepipes/blob/master/snakePipes/shared/defaults.yaml

**Comment by ppnin** [comment]
Great, indeed! `DNA-mapping` finished without any further issues. 
I checked the original `defaults.yaml` file and I see only minor differences. Here is the content of my file

```
emailSender: null
onlySSL: false
smtpPassword: null
smtpPort: 0
smtpServer: null
smtpUsername: null
snakemake_options: ' --use-conda --conda-prefix /home/pavle/miniconda3/envs '
tempdir: /media/pavle/WD/Projects/tempDir/
```
and it looks same to me, apart from commented lines. 

Btw, I have a question regarding the `ATAC-seq` procedure which I want to do next (and i thought it would be better to ask it here than opening a new issue).  I read the docs (including the example that covers `ChIP-seq`) but I am not entirely sure about how to make a `samples.yaml` file.  In the `ChIP-seq` example the `chip-samples.yaml` file looks like:

```
chip_dict:
  SRR6761497:
    control: SRR6761502
    broad: True
  SRR6761498:
    control: SRR6761502
    broad: True
  SRR6761495:
    control: SRR6761502
    broad: False
  SRR6761499:
    control: SRR6761502
    broad: False
```    
So if I have 1 control (BBB) and 1 case (AAA) sample,  paired-end reads (so 4 `fastq` files in total), 
could an `atac-samples.yaml` file look something like

```
atac_dict:
  AAA:
    control: BBB
    broad: True
```    
where both AAA and BBB have corresponding R1 and R2 reads?

**Comment by steffenheyne** [comment]
No worries about opening new issues!

No, you need a file like this:
https://github.com/maxplanck-ie/snakepipes/blob/master/docs/content/sampleSheet.example.tsv

name    condition
AAA     KO
BBB     ctrl

but this is only needed for differential open chromatin calling. you can invoke the workflow also first without it and then rerun later with the sample sheet. 
The one you posted is to get the link between ChIP samples and their input for peak calling and log2-ration tracks.

**Comment by ppnin** [comment]
Ok, next time I'll open a new issue :)

Right, then a `samplSheet.tsv` file is enough and I guess it's supposed to be saved in the working directory (with the `DNA-mapping` output). 

Just out of curiosity - if I use `ATAC-seq ` with the `--sampleSheet`  option - what is the function of the file `samples.yaml` (the usage example on https://snakepipes.readthedocs.io/en/latest/content/workflows/ATAC-seq.html):

`ATAC-seq -d working-dir mm10 samples.yaml` ?

**Comment by steffenheyne** [comment]
Leave your copy of sampleSheet.tsv outside of the snakePipes output/working directory. When you start a workflow we copy the sample sheet as well as the main configuration files into the output/working directory for documentation etc. (I think we even overwrite without notice)

minimal call would be:
`ATAC-seq -d [$WORKINGDIR]`

with sample sheet:

`ATAC-seq -d [$WORKINGDIR] --sampleSheet [$YOURSAMPLESHEETFILE]`

The usage example in the documentation is wrong! Thanks for that! We'll fix that. Only the ChIP-seq workflow allows for this additional yaml file (and which is not the sample sheet, but the ChIP<-> input mapping) )

**Comment by ppnin** [comment]
Thanks for info! I ran the minimal call now and two jobs could not be finished for some reason. I'll start a new issue related to ATAC-seq.

**Comment by dpryan79** [comment]
Looks like this is now resolved, so I'll close this issue.
