### ISSUE TITLE
Error while running ATAC-seq 

### ISSUE THREAD

**Issue by ppnin** [maxplanck-ie/snakepipes#388]
Hi, 
I initiated the minimal ATAC-seq call (as discussed in #386) 
`ATAC-seq --working-dir /media/pavle/WD/Projects/DNAmap_out --jobs 10 --local hg19`
and I got `Error in rule MACS2_peak_qc`. Here's the part of the screen print:

```
Activating conda environment: /home/pavle/miniconda3/envs/71994045c5752f4e4facffb86fc61fd5
/bin/bash: line 22: printf: .32426453046679902832: invalid number
/bin/bash: line 22: printf: .00000058132949210356: invalid number
[Fri Feb 15 09:58:38 2019]
Error in rule MACS2_peak_qc:
    jobid: 4
    output: MACS2_QC/ERR1013035_tr2.filtered.BAM_peaks.qc.txt
    conda-env: /home/pavle/miniconda3/envs/71994045c5752f4e4facffb86fc61fd5

RuleException:
CalledProcessError in line 66 of /home/pavle/miniconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/rules/ATAC_qc.snakefile:
Command 'source activate /home/pavle/miniconda3/envs/71994045c5752f4e4facffb86fc61fd5; set -euo pipefail;  
        # get the number of peaks
        peak_count=`cat MACS2/ERR1013035_tr2.filtered.BAM_peaks.narrowPeak | wc -l`

        # get the number of mapped reads
        mapped_reads=`samtools view -c -F 4 filtered_bam/ERR1013035_tr2.filtered.bam`

        # calculate the number of alignments overlapping the peaks
        # exclude reads flagged as unmapped (unmapped reads will be reported when using -L)
        reads_in_peaks=`samtools view -c -F 4 -L MACS2/ERR1013035_tr2.filtered.BAM_peaks.narrowPeak filtered_bam/ERR1013035_tr2.filtered.bam`

        # calculate Fraction of Reads In Peaks
        frip=`bc -l <<< "$reads_in_peaks/$mapped_reads"`

        # compute peak genome coverage
        peak_len=`awk '{total+=$3-$2}END{print total}' MACS2/ERR1013035_tr2.filtered.BAM_peaks.narrowPeak`
        genome_size=`awk '{total+=$3-$2}END{print total}' /home/pavle/Documents/Data/HumanGenome/indicesTest/genome_fasta/genome.fa.fai`
        genomecov=`bc -l <<< "$peak_len/$genome_size"`

        # write peak-based QC metrics to output file
        printf "peak_count	FRiP	peak_genome_coverage
%d	%5.3f	%6.4f
" $peak_count $frip $genomecov > MACS2_QC/ERR1013035_tr2.filtered.BAM_peaks.qc.txt ' returned non-zero exit status 1.
  File "/home/pavle/miniconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/rules/ATAC_qc.snakefile", line 66, in __rule_MACS2_peak_qc
  File "/home/pavle/miniconda3/envs/snakePipes/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job MACS2_peak_qc since they might be corrupted:
MACS2_QC/ERR1013035_tr2.filtered.BAM_peaks.qc.txt
Job failed, going on with independent jobs.

```
This message appeared twice (as I have 1 case and 1 control sample), other jobs finished successfully. Any idea what this might be?

**Comment by dpryan79** [comment]
What OS are you using? Do you end up with a `MACS2/ERR1013035_tr2.filtered.BAM_peaks.narrowPeak` file?

**Comment by ppnin** [comment]
I'm using Linux Mint 19 (which is, I think, based on Ubuntu 18.04 LTS). Yes, I have that file in the MACS2 folder.

**Comment by dpryan79** [comment]
Odd, my only guess was that that file wasn't created, so printf was getting the wrong variable for `peak_count`. Can you run the following successfully?

    printf "%5.3f" .32426453046679902832

**Comment by ppnin** [comment]
I guess that's the problem then.. in my shell I get

```
bash: printf: .32426453046679902832: invalid number
0,000
``` 
Is there a way to get around this?

**Comment by steffenheyne** [comment]
@dpryan79 Oh is this a LOCALE problem?
Can we enforce a  certain LOCALE in a conda env?

**Comment by dpryan79** [comment]
@steffenheyne Presumably we could put a `LOCALE` in there.

@ppnin Does it work if you change `.` to `,`?

**Comment by ppnin** [comment]
I think my issue with `printf` might be related to https://stackoverflow.com/questions/12845997/unexplicable-error-in-bash-printf-command-inside-a-script-returns-invalid-numb

When I run `LC_NUMERIC="en_US.UTF-8" printf "%5.3f" .32426453046679902832`
it does print `0.324`.

So yes, it could be a LOCALE problem

**Comment by ppnin** [comment]
@dpryan79 Yeah, when I run `printf "%5.3f" ,32426453046679902832` I get `0,324`.

**Comment by dpryan79** [comment]
At least the fix is easy. We'll have to update the ChIP-seq QC step too.

**Comment by ppnin** [comment]
Do you think that for now it's enough to  `export LC_NUMERIC="en_US.UTF-8"` in my bash profile before running `ATAC-seq`?  Btw, when I re-run `ATAC-seq` - will it just finish those two jobs?

**Comment by dpryan79** [comment]
Yes to both questions.

**Comment by ppnin** [comment]
Right, after having LOCALE fixed `ATAC-seq` finished those two jobs without any issues.  
Thanks for the help!

**Comment by ppnin** [comment]
Hi again - after running the minimal `ATAC-seq` call I tried the one that includes `--sampleSheet`, for finding differentially accessible regions. I got en error and I am not sure about how to interpret it: 

```
[Mon Feb 18 11:26:22 2019]
rule CSAW:
    input: MACS2/ERR1013031_tr2.filtered.BAM_peaks.xls, MACS2/ERR1013035_tr2.filtered.BAM_peaks.xls, /media/pavle/WD/Projects/Manual/helena_samples2.tsv, deepTools_qc/bamPEFragmentSize/fragmentSize.metric.tsv
    output: CSAW/CSAW.session_info.txt, CSAW/DiffBinding_analysis.Rdata
    log: CSAW/CSAW.log
    jobid: 6
    benchmark: CSAW/.benchmark/CSAW.benchmark

Activating conda environment: /home/pavle/miniconda3/envs/71994045c5752f4e4facffb86fc61fd5
Warning message:
multiple methods tables found for ‘pos’ 
Warning messages:
1: replacing previous import ‘BiocGenerics::path’ by ‘Rsamtools::path’ when loading ‘GenomicAlignments’ 
2: replacing previous import ‘BiocGenerics::path’ by ‘Rsamtools::path’ when loading ‘rtracklayer’ 
3: multiple methods tables found for ‘path’ 
Mode : Differential Binding
bam files used: 

Counting reads in windows.. windows with total counts < 20 are discarded
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘seqinfo’ for signature ‘"NULL"’
Calls: readfiles_chip ... seqlevels<- -> seqlevels<- -> seqinfo -> <Anonymous>
Execution halted
[Mon Feb 18 11:26:30 2019]
Error in rule CSAW:
    jobid: 6
    output: CSAW/CSAW.session_info.txt, CSAW/DiffBinding_analysis.Rdata
    log: CSAW/CSAW.log
    conda-env: /home/pavle/miniconda3/envs/71994045c5752f4e4facffb86fc61fd5

```
What could be the cause of this error?

**Comment by dpryan79** [comment]
That suggests that a file is empty. Can you post the output of the following:

    wc -l MACS2/ERR1013031_tr2.filtered.BAM_peaks.xls MACS2/ERR1013035_tr2.filtered.BAM_peaks.xls /media/pavle/WD/Projects/Manual/helena_samples2.tsv deepTools_qc/bamPEFragmentSize/fragmentSize.metric.tsv

**Comment by ppnin** [comment]
Strange, because I see those files in the working directory and they are not empty.. here's the output:

```
  1516 MACS2/ERR1013031_tr2.filtered.BAM_peaks.xls
   859 MACS2/ERR1013035_tr2.filtered.BAM_peaks.xls
     3 /media/pavle/WD/Projects/Manual/helena_samples2.tsv
     3 deepTools_qc/bamPEFragmentSize/fragmentSize.metric.tsv
  2381 total
```

**Comment by dpryan79** [comment]
Looking at the code this is where it's trying to load the BAM files. Can you post the sample sheet and the file names in the `filtered_bam` directory? There seems to be a mismatch there.

**Comment by ppnin** [comment]
Gah.... that was the error. In my `sampleSheet`, I forgot to add a suffix in the file name. This was my sample sheet:

```
name	condition
ERR1013031	KO
ERR1013035	TS
```

which indeed does not match file names in my `filtered_bam` directory:
`ERR1013031_tr2.filtered.bam  ERR1013031_tr2.filtered.bam.bai  ERR1013035_tr2.filtered.bam  ERR1013035_tr2.filtered.bam.bai  logs`

Now I fixed it and ran `ATAC-seq` again, everything was OK until `plotMDS.default()` : 

```
Error in plotMDS.default(adj.counts, main = top, col = as.numeric(chipCountObject$sampleSheet$condition),  : 
  Only 2 columns of data: need at least 3
Calls: tmmNormalize_chip -> <Anonymous> -> plotMDS.default
Execution halted
[Mon Feb 18 12:23:29 2019]
Error in rule CSAW:
    jobid: 6
    output: CSAW/CSAW.session_info.txt, CSAW/DiffBinding_analysis.Rdata
    log: CSAW/CSAW.log
    conda-env: /home/pavle/miniconda3/envs/71994045c5752f4e4facffb86fc61fd5

``` 
So, I need one sample (I guess)?

**Comment by dpryan79** [comment]
You need replicates for any differential analysis to work, actually.

**Comment by ppnin** [comment]
Good, then I know where the problem is. Thanks for the advice, this is the first time for me to do any of this :)

**Comment by dpryan79** [comment]
Best of luck!

**Comment by steffenheyne** [comment]
...mhmm there is a replicate check for this in the atac code, wondering why this doesn't work...

https://github.com/maxplanck-ie/snakepipes/blob/55950653f15d14cad356dd636da28247681e1027/snakePipes/workflows/ATAC-seq/internals.snakefile#L11

**Comment by ppnin** [comment]
Interesting..  I don't know how the function `check_replicates()` works, but could it be related to the number of columns mentioned in the log that I posted above:

```
Error in plotMDS.default(adj.counts, main = top, col = as.numeric(chipCountObject$sampleSheet$condition),  : 
  Only 2 columns of data: need at least 3
```

If this is related to a `sampleSheet`, I wonder if there can be more than 2 columns since replicates are entered in the first column (as I understand it)?

**Comment by dpryan79** [comment]
The latter error is due to having only two columns of counts (one per sample).

**Comment by ppnin** [comment]
A question: in the ATAC-seq workflow I see `import snakePipes.common_functions as cf` (line 14) , so I guess that `check_replicates()` should be in the imported file. 

I checked the file `.../snakePipes/common_functions.py` now and I see, for example, the function
`check_sample_info_header(sampleSheet)` but I can't find `check_replicates(sampleSheet)`.

Is it supposed to be there?

**Comment by steffenheyne** [comment]
that's all fine, we will deal with that. check_replicates is also in common_functions.py
my comment was more meant for the other developers

@ppnin in the sample sheet you provided ou named your samples like ERR1013031_tr2 right?

**Comment by ppnin** [comment]
Alright, I guess it's somewhere else then.

Yes, my samples are named ERR1013031_tr2 and ERR1013035_tr2.
