### ISSUE TITLE
BinSize Hi-C pipeline should include -rs

### ISSUE THREAD

**Issue by gtrichard** [maxplanck-ie/snakepipes#389]
https://github.com/maxplanck-ie/snakepipes/blob/55950653f15d14cad356dd636da28247681e1027/snakePipes/shared/rules/hicexplorer.snakefile#L67

`-rs  DpnII.bed --restrictionSequence GATC --danglingSequence GATC` should be part of the rule generating matrices at a given fixed bin size. This will solve issues concerning reads filtering and hicQC stats.

**Comment by dpryan79** [comment]
Is this still an issue with the pipeline? @LeilyR

**Comment by LeilyR** [comment]
I will add it to the pipeline today.

**Comment by LeilyR** [comment]
@gtrichard  I have checked for what you have asked for. `--restrictionSequence GATC --danglingSequence`  is already there and `-rs` cannot be accepted by hicexplorer together with `-bs`. So there is nothing more we can do here at snakepipes side.
