### ISSUE TITLE
SlurmEasy

### ISSUE THREAD

**Issue by mictadlo** [maxplanck-ie/snakepipes#396]
Hi,
I found a racon/pilon pipeline [here](https://github.com/RomainFeron/nanopore-snake) and I just wonder whether you are interested to include into your collection. If not then could you please explain how to extend the racon/pilon pipeline to be able to use `SlurmEasy` and be able to submit each step with different CPU/memory requirement?

Thank you in advance,

Michal

**Comment by dpryan79** [comment]
We aren't doing any assembly with long-reads, so we're unlikely to incorporate that ourselves, though if you wanted to make a PR that did that that'd certainly be fine. You can use `SlurmEasy` with that workflow as follows:

    snakemake -c "SlurmEasy -t {threads}" -j 8  # Change the options to SlurmEasy and maybe adjust the -j option

**Comment by mictadlo** [comment]
I'm a newbie to snakemake and this could take some time.
