### ISSUE TITLE
genomeinfodb(data) not available for CSAW rule in develop

### ISSUE THREAD

**Issue by katsikora** [maxplanck-ie/snakepipes#409]
CSAW rule is failing in develop due to failed load of genomeinfodb pointing to unavailable genomeinfodbdata. Including these two packages:

 - bioconductor-genomeinfodb
 - bioconductor-genomeinfodbdata

in ATAC-seq yaml doesn't solve the issue.

**Comment by dpryan79** [comment]
Xref: https://github.com/bioconda/bioconda-recipes/issues/14421
Xref: https://github.com/bioconda/bioconda-recipes/issues/13846

I thought this was fixed in February, but I guess not.

**Comment by dpryan79** [comment]
Hmm, this is working for me. Are you using the stuff from `module load` or your own installation?

**Comment by katsikora** [comment]
(module load v1.1.2 is  working for me)
I'm using my own install, as I want to test some changes I made to CSAW
whatever made me pull from develop before finishing the testing :/

**Comment by dpryan79** [comment]
It's been working fine for me in my own install.

**Comment by dpryan79** [comment]
Since this is an upstream issue I'll close it here.
