### ISSUE TITLE
Consider adding GPL3 license text and header

### ISSUE THREAD

**Issue by heuermh** [maxplanck-ie/snakepipes#419]
Hello,

Per [How to use GNU licenses for your own software](https://www.gnu.org/licenses/gpl-howto.html), GPL3 projects should include a copy of the license itself (in a file called `COPYING`, by convention) and a license notice in the header of every source file.

Please consider adding these, the GPL v3 license notice at https://github.com/maxplanck-ie/snakepipes/blob/master/setup.py#L20 may not be sufficient.

**Comment by dpryan79** [comment]
This is now fixed in `develop`, thanks for pointing it out.
