### ISSUE TITLE
WGBS changes

### ISSUE THREAD

**Issue by dpryan79** [maxplanck-ie/snakepipes#423]
These will be in 1.3.0:

 - [x] Remove `--cref` and `--convref`
 - [x] Remove GATK (is picard needed then?)
 - [x] Add an option to change the coverage threshold (currently it's 10x)
 - [x] Add an option to change the methylation change threshold (currently it's 0.2)
 - [x] Remove `--fqcin`, `--nextera` and `--trim auto`. Trimming should generally be brought into line with the other workflows.
 - [x] Add fastp to the trimmers and make default for WGBS
 - [x] Remove `aux_files` directory if possible
 - [x] Remove the `merged_methylation_data_sampleSheet` directory.
 - [x] Either metilene or the metilene_cleanup output/rule changed from 1.1.2 to 1.2.0 and that needs to be fixed. There are no longer DMRs found.
 - [x] update example defaults.yaml for WGBS
 - [x] Speed up DSS and ensure it's stable
 - [x] Update documentation

**Comment by katsikora** [comment]
I think nothing else than GATK needs Picard

also, checkout the WGBS defaults.yaml for modifiable thresholds:
###Thresholds for filtering of statistical comparisons:
minAbsDiff: 0.2
FDR: 0.02

**Comment by dpryan79** [comment]
Ah, some options just need command line arguments, thanks!
