### ISSUE TITLE
Fragment length should be an option for SE ChIP-seq data

### ISSUE THREAD

**Issue by dpryan79** [maxplanck-ie/snakepipes#437]
This is apparently one of the options that's only in the YAML files but not exposed.

**Comment by steffenheyne** [comment]
I was always wondering if we should have a per-sample fragment length!? (eg in the chip dict) 
MACS2 can do this via cross-correlation. In R eg also CSAW has a function to plot the cross correlation and identify the max per sample `correlateReads(bam.files, max.delay, param=dedup.on)`
 
This would be overall more correct, on the other hand this could also introduce some "spreading" artefacts if libraries have different fragment lengths and they are used together in eg CSAW for differential binding. CSAW can exactly use the same length to "correct" for such artefacts

**Comment by dpryan79** [comment]
Yeah, an option to do this would be good.

**Comment by katsikora** [comment]
I've added --fragmentLength as commandline param to ChIPseq in PR #487.
