### ISSUE TITLE
Standardize option formatting

### ISSUE THREAD

**Issue by dpryan79** [maxplanck-ie/snakepipes#438]
The BOSC reviewers helpfully pointed this out, but we use a mixture of camelCase and under_scores in our options. We should really standardize on one (I vote camelCase), even if they're still a mixture in the YAML file.

**Comment by dpryan79** [comment]
We also have all lower-case options.

**Comment by dpryan79** [comment]
To do still:

 - [ ] mapping_prg -> aligner
 - [ ] mate_orientation -> mateOrientation
 - [ ] insert_size_max -> insertSizeMax
 - [ ] featurecounts_options -> featureCountsOptions
 - [ ] star_options, hisat_options -> alignerOptions
 - [ ] properpairs -> properPairs
 - [ ] window_size -> windowSize
 - [ ] ignore_forNorm -> ignoreForNorm

**Comment by dpryan79** [comment]
This is mostly taken care of by #430

**Comment by vivekbhr** [comment]
are we going for all camelCase?

**Comment by dpryan79** [comment]
Yes
