### ISSUE TITLE
Make the organisms directory configurable

### ISSUE THREAD

**Issue by dpryan79** [maxplanck-ie/snakepipes#439]
At the moment, the organisms yaml files can be either placed under `shared/organisms` or an absolute path provided. What I hadn't considered is people wanting to upgrade snakePipes in places (I ALWAYS create new environments for each software version), which will overwrite any changes people make to the organism yaml files. What would be better is if `shared/defaults.yaml` had an `organisms` entry specifying the relative or absolute path to a directory containing the organisms yaml file.

Additionally, we should move snakemake cluster commands from `cluster.yaml` to `defaults.yaml`. Then only `defaults.yaml` needs to be touched by users when they install/upgrade.

**Comment by steffenheyne** [comment]
and maybe add some SnakePipes configOrgansims --flush

**Comment by steffenheyne** [comment]
and maybe some snakePipes configOrganism 
--flushDefaults
--configOrganismDir [PATH] ---> goes into defaults.yaml
--installDefaults/--installMPIIE or so--> will install our defaults for us

and move all shared/organisms to shared/organisms_mpi or organisms_defaults/examples

**Comment by steffenheyne** [comment]
and createIndicies should check the organism dir in defaults.yaml 
if not set yet, user should run snakePipes configOrganism first

**Comment by dpryan79** [comment]
This is now implemented in `develop`.
