### ISSUE TITLE
Createindicies consume RAM

### ISSUE THREAD

**Issue by Leif78** [maxplanck-ie/snakepipes#440]
Dear all,
I have installed snakepipe 1.2.1 to a completely clean and new ubuntu 18.04. CreateIndicies suddenly consume all my RAM (32G) resulting in total freeze of the system. The same happened when I tried to reduce the number of jobs to 1.

this is my command line:

createIndices --genomeURL ~/Danio_rerio.GRCz11.dna.toplevel.fa.gz --gtfURL ~/Danio_rerio.GRCz11.96.gtf.gz -o ~/GRCz11 --local --jobs 2 GRCz11v96

Is it a method to control the use of RAM in snakePipes?
Thank you for all help!

**Comment by steffenheyne** [comment]
There is no additional control for RAM usage in snakePipes (only some max allowed memory in a cluster environment). The number of jobs can help, but maybe not much. 
At the end, we just use the tools like STAR or Bowtie2 to create their indices as if you would run them on your own.

What you can try is to use the `--tools` option to create only specific indices, one after the other, and see which one causes the memory issue.

The STAR index could be a good candidate for high memory usage.

**Comment by Leif78** [comment]
Hi, thanks for answer.
I tried to do one indicies at a time but the memory usage went up to 32GB at once. I also tried “--tools none” with same result. Is 32GB memory to small to be used for snakePipes?

**Comment by dpryan79** [comment]
I'm not sure what step other than creating aligner indices would use that much RAM. Can you post the logs?

**Comment by Leif78** [comment]
Hi, this is the log:

(snakePipes) leif@leif-OptiPlex-9020:~$ createIndices --genomeURL ~/Danio_rerio.GRCz11.dna.toplevel.fa.gz --gtfURL ~/Danio_rerio.GRCz11.96.gtf.gz -o ~/GRCz11 --tools none --local --jobs 1 GRCz11v96

Failed to create temp dir under temp path prefix (/data/extended/)! Try fallback: /home/leif/GRCz11/ ...
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	computeEffectiveGenomeSize
	1	createGenomeFasta
	1	downloadGTF
	1	extendCodingRegions
	1	fastaDict
	1	fastaIndex
	1	gtf2BED
	1	make2bit
	9

[Mon May 27 12:03:29 2019]
rule downloadGTF:
    output: /home/leif/GRCz11/annotation/genes.gtf
    jobid: 5

Job counts:
	count	jobs
	1	downloadGTF
	1
[Mon May 27 12:03:32 2019]
Finished job 5.
1 of 9 steps (11%) done

[Mon May 27 12:03:32 2019]
rule gtf2BED:
    input: /home/leif/GRCz11/annotation/genes.gtf
    output: /home/leif/GRCz11/annotation/genes.bed
    jobid: 6

Activating conda environment: /home/leif/miniconda3/envs/f4a6bca918942cbcf6bb66f6bdaecc96
[Mon May 27 12:03:36 2019]
Finished job 6.
2 of 9 steps (22%) done

[Mon May 27 12:03:36 2019]
rule extendCodingRegions:
    input: /home/leif/GRCz11/annotation/genes.gtf
    output: /home/leif/GRCz11/annotation/genes.slop.gtf
    jobid: 7

[Mon May 27 12:03:37 2019]
Finished job 7.
3 of 9 steps (33%) done

[Mon May 27 12:03:37 2019]
rule createGenomeFasta:
    output: /home/leif/GRCz11/genome_fasta/genome.fa
    jobid: 1

Job counts:
	count	jobs
	1	createGenomeFasta
	1
^[^[^[^[Killed
Removing output files of failed job createGenomeFasta since they might be corrupted:
/home/leif/GRCz11/genome_fasta/genome.fa
Job failed, going on with independent jobs.
Exiting because a job execution failed. Look above for error message
Complete log: /home/leif/GRCz11/.snakemake/log/2019-05-27T120329.263970.snakemake.log
Error: snakemake returned an error code of 1, so processing is incomplete!

**Comment by dpryan79** [comment]
Apparently decompressing the genome fasta file is blowing up memory for some reason. Is that fasta file the most recent version from Gencode? Can you try decompressing it first and see if that makes a difference?

**Comment by dpryan79** [comment]
Oh, is this from Ensembl? It looks like their compressed file has something wrong with it. We're looking into it.

**Comment by dpryan79** [comment]
It looks like the GRCz11 primary assembly from Ensembl is OK, for whatever that's worth, it's just the top level that's extracting to ~50GB (this is obviously biologically nonsense).

**Comment by Leif78** [comment]
Hi, it is from Ensembl, you have right it seems  to be something with compression which causes the memory issues. Though I got a new error message after extraction of the genome fasta file.

(snakePipes) leif@leif-OptiPlex-9020:~$ createIndices --genomeURL ~/Danio_rerio.GRCz11.dna.toplevel.fa --gtfURL ~/Danio_rerio.GRCz11.96.gtf.gz -o ~/GRCz11 --tools none --local --jobs 1 GRCz11v96

Failed to create temp dir under temp path prefix (/data/extended/)! Try fallback: /home/leif/GRCz11/ ...
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	computeEffectiveGenomeSize
	1	createGenomeFasta
	1	downloadGTF
	1	extendCodingRegions
	1	fastaDict
	1	fastaIndex
	1	gtf2BED
	1	make2bit
	9

[Mon May 27 12:37:27 2019]
rule createGenomeFasta:
    output: /home/leif/GRCz11/genome_fasta/genome.fa
    jobid: 1

Job counts:
	count	jobs
	1	createGenomeFasta
	1
[Mon May 27 12:37:28 2019]
Error in rule createGenomeFasta:
    jobid: 0
    output: /home/leif/GRCz11/genome_fasta/genome.fa

RuleException:
MemoryError in line 11 of /home/leif/miniconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/rules/createIndices.snakefile.
  File "/home/leif/miniconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/rules/createIndices.snakefile", line 33, in __rule_createGenomeFasta
  File "/home/leif/miniconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/rules/createIndices.snakefile", line 11, in downloadFile
  File "/home/leif/miniconda3/envs/snakePipes/lib/python3.6/tempfile.py", line 485, in func_wrapper
  File "/home/leif/miniconda3/envs/snakePipes/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Exiting because a job execution failed. Look above for error message
Job failed, going on with independent jobs.

[Mon May 27 12:37:28 2019]
rule downloadGTF:
    output: /home/leif/GRCz11/annotation/genes.gtf
    jobid: 5

Job counts:
	count	jobs
	1	downloadGTF
	1
[Mon May 27 12:37:30 2019]
Finished job 5.
1 of 9 steps (11%) done

[Mon May 27 12:37:30 2019]
rule gtf2BED:
    input: /home/leif/GRCz11/annotation/genes.gtf
    output: /home/leif/GRCz11/annotation/genes.bed
    jobid: 6

Activating conda environment: /home/leif/miniconda3/envs/f4a6bca918942cbcf6bb66f6bdaecc96
[Mon May 27 12:37:35 2019]
Finished job 6.
2 of 9 steps (22%) done

[Mon May 27 12:37:35 2019]
rule extendCodingRegions:
    input: /home/leif/GRCz11/annotation/genes.gtf
    output: /home/leif/GRCz11/annotation/genes.slop.gtf
    jobid: 7

[Mon May 27 12:37:36 2019]
Finished job 7.
3 of 9 steps (33%) done
Exiting because a job execution failed. Look above for error message
Complete log: /home/leif/GRCz11/.snakemake/log/2019-05-27T123726.758288.snakemake.log
Error: snakemake returned an error code of 1, so processing is incomplete!

**Comment by dpryan79** [comment]
Yeah, it ran out of memory again.

**Comment by steffenheyne** [comment]
can you try this one:
ftp://ftp.ensembl.org/pub/release-96/fasta/danio_rerio/dna/Danio_rerio.GRCz11.dna_sm.primary_assembly.fa.gz

**Comment by steffenheyne** [comment]
oh yeah, so the toplevel assembly contains all the alternate loci and in the Ensembl version the "common"  part is replaced with "N" in every alternate contig. And these "N"s makes the difference between 1.6Gb (primary) and 53GB (toplevel) !!!

Also very few aligners can handle alternate loci properly. So I guess you really want the primary assembly as given in my link above. Please also note in addition that there are "soft masked" or "hard" masked versions in order to deal better with repetitive elements. The link above is for the soft masked ("dna_sm") version. Here, elements found by repeat masker are lower case in the DNA sequence. In the "dna_rm" version, such elements are also replaced by "N", but this you do not want generally.

**Comment by Leif78** [comment]
Thanks, create indices and DNA mapping is working. Thanks for hjelp!
