### ISSUE TITLE
ln -s -r error 

### ISSUE THREAD

**Issue by tiagobrc** [maxplanck-ie/snakepipes#441]
Hi, I am trying to run the pipeline on the dna-mapping stage. But right in the begining, I got an error caused by ln -s -r. Am I missing something?

```
localrule FASTQ1:
    input: /gamma_data1/trezende/Mariy/Seq/4_ForthBatch/WTATAC_exTregIEL_S9_R1.fastq.gz
    output: FASTQ/WTATAC_exTregIEL_S9_R1.fastq.gz
    jobid: 122
    wildcards: sample=WTATAC_exTregIEL_S9
Job failed, going on with independent jobs.

[Thu May 23 15:49:56 2019]
Error in rule FASTQ1:
    jobid: 126
    output: FASTQ/WTATAC_iTreg_S7_R1.fastq.gz
ln: invalid option -- 'r'
Try `ln --help' for more information.
```

**Comment by steffenheyne** [comment]
You are on Mac OS? The -r option for ln might be not supported

**Comment by tiagobrc** [comment]
No, I am using linux server with anaconda. 
```
(snakePipes) [trezende@gamma Seq]$ uname -a
Linux gamma 2.6.32-754.12.1.el6.x86_64 #1 SMP Thu Mar 7 22:07:44 EST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by steffenheyne** [comment]
mhmm, when you `man ln` does it show the -r ?

**Comment by steffenheyne** [comment]
oh you probably have an tool old version of coreutils.

We can think about to if this is really necessary. In the meantime you can just remove the -r from the ln commands in your installed version in `snakePipes/shared/rules/FASTQ.snakefile`

**Comment by tiagobrc** [comment]
Thanks, is it -r super essential? Will do that. 

`ln (GNU coreutils) 8.4`

**Comment by steffenheyne** [comment]
No, it just make relative links

**Comment by tiagobrc** [comment]
Thank you so much for the fast and effective response!

**Comment by dpryan79** [comment]
@tiagobrc Out of curiosity, is there a reason you're running a 10 year old version of Linux?

**Comment by steffenheyne** [comment]
And to overcome the same issue in the future, you can just `conda install coreutils` in the env from where you start snakePipes.  This should give you a more recent version and you don't need to modify the code after installation.

**Comment by tiagobrc** [comment]
@dpryan79  I am using a server from our university and it is like that. 

@steffenheyne I had a problem again

`[Fri May 24 11:23:34 2019]
rule samtools_filter:
    input: Bowtie2/WTATAC_CD4IELa_S10.bam, filter_rules
    output: filtered_bam/WTATAC_CD4IELa_S10.filtered.bam
    log: filtered_bam/logs/samtools_filter.WTATAC_CD4IELa_S10.out, filtered_bam/logs/samtools_filter.WTATAC_CD4IELa_S10.err
    jobid: 39
    benchmark: filtered_bam/.benchmark/samtools_filter.WTATAC_CD4IELa_S10.benchmark
    wildcards: sample=WTATAC_CD4IELa_S10
    threads: 5

WARNING: The conda.compat module is deprecated and will be removed in a future release.
Activating conda environment: /ru-auth/local/home/trezende/envs/09389d85
ln: invalid option -- 'r'
Try `ln --help' for more information.
[Fri May 24 11:23:35 2019]
Error in rule samtools_filter:
    jobid: 39
    output: filtered_bam/WTATAC_CD4IELa_S10.filtered.bam
    log: filtered_bam/logs/samtools_filter.WTATAC_CD4IELa_S10.out, filtered_bam/logs/samtools_filter.WTATAC_CD4IELa_S10.err (check log file(s) for error message)
    conda-env: /ru-auth/local/home/trezende/envs/09389d85
    shell:
        
        filter=""
        if [ "False" == "True" ] ; then filter="$filter -F 1024"; fi
        if [ "False" == "True" ] ; then filter="$filter -f 2"; fi
        if [ "0" != "0" ] ; then filter="$filter -q 0"; fi
        if [[ -z $filter ]] ; then ln -s -r Bowtie2/WTATAC_CD4IELa_S10.bam filtered_bam/WTATAC_CD4IELa_S10.filtered.bam ;
        else
            samtools view -@ 5 -b $filter -o filtered_bam/WTATAC_CD4IELa_S10.filtered.bam Bowtie2/WTATAC_CD4IELa_S10.bam 2> filtered_bam/logs/samtools_filter.WTATAC_CD4IELa_S10.err ;
        fi
        echo "samtools view arguments: $filter" > filtered_bam/logs/samtools_filter.WTATAC_CD4IELa_S10.out`



So to fix this I should install `conda install coreutils` inside the env? I hope it works.

**Comment by tiagobrc** [comment]
So it looks like after installing coreutils with conda inside my snakepipes env it selects the correct ln. But it still fails during samtools, how can I change ln also in the internal env?

**Comment by steffenheyne** [comment]
conda activate  /ru-auth/local/home/trezende/envs/09389d85

Then
conda install coreutils


conda deactivate

The name of the appropriate env is shown in the log before

**Comment by steffenheyne** [comment]
or 
`snakePipes envInfo`
