### ISSUE TITLE
deepTools_qc log-files are uninformative

### ISSUE THREAD

**Issue by thomasmanke** [maxplanck-ie/snakepipes#45]
The log-files (especially for deepTools_qc) should contain the actual call. It can be quite cumbersome to infer the precise call from the snakemake-files.
As it stands those log-files simply report some standard error, which is usually uninformative.

**Comment by steffenheyne** [comment]
the actual call is printed for each rule  if snakemake is started with `--printshellcmds`
We do this if the wrapper is started with -v
cmdl calls are then printed to the screen and they also land in the main text log file  like [OUTDIR]/DNA-mapping.log or [OUTDIR]/ChIP-seq.log

Would this be sufficient?

**Comment by vivekbhr** [comment]
the command calls are found in the workflow log files, so that should be sufficient as long as we take care of #58
