### ISSUE TITLE
Problem with conda install

### ISSUE THREAD

**Issue by re2srm** [maxplanck-ie/snakepipes#461]
I am using the following command to install snakepipes on my university cluster:

conda install -c mpi-ie -c bioconda -c conda-forge snakePipes

I get the following message after about 2 minutes:
Collecting package metadata: done
Solving environment: /Killed

This problem probably has more to do with conda than snakepipes but I am just asking in case someone has any suggestions about how I can resolve it. 

I dont get this error when I install other packages with conda.

Thanks

**Comment by dpryan79** [comment]
How much RAM is on the system where you're running this? Do you get the same results if you use the following channel order: `-c mpi-ie -c conda-forge -c bioconda`?

**Comment by re2srm** [comment]
Thanks. Changing the order fixed it.
