### ISSUE TITLE
cutadapt: move hardcoded Q and -minlength to defaults.yaml

### ISSUE THREAD

**Issue by vivekbhr** [maxplanck-ie/snakepipes#467]
Apparently this threshold is too high for some (bad quality) datasets. Moving to defaults would add more felxibility

**Comment by steffenheyne** [comment]
like this would be good, but `trim_options` is empty right now to be independent of the user choice cutadapt or trimgalore for `trim_prg`
one solution could be to skip trimGalore completely, only missing feature in cutadapt is some way to auto-detect of adaptors

**Comment by vivekbhr** [comment]
Yah that's true this would interfere with trimgalore option. I won't change this for now.

true, we have been thinking to remove trimgalore for a while.

**Comment by dpryan79** [comment]
I just need to update the documentation and my WGBS branch, which adds fastp, will get merged in. Maybe switching to fastp will make life easier.

**Comment by vivekbhr** [comment]
does fastp also have a multiqc module?

**Comment by vivekbhr** [comment]
ok checked.. yes it does

**Comment by dpryan79** [comment]
yes, it's included in my PR

**Comment by vivekbhr** [comment]
👍 from my side to replace cutadapt and trimgalore with *fastp*

**Comment by dpryan79** [comment]
`fastp` is now available in all of the pipelines and it should make some of this a bit simpler.
