### ISSUE TITLE
RNA-seq estimateReadFilter error log location

### ISSUE THREAD

**Issue by mirax87** [maxplanck-ie/snakepipes#470]
From RNA-seq workflow the error log of `rule estimateReadFiltering` is directed to `bamCoverage` instead of `deepTools_qc`. 

Snippet from [deepTools_RNA.snakefile](https://github.com/maxplanck-ie/snakepipes/blob/1.2.2/snakePipes/shared/rules/deepTools_RNA.snakefile)
```
rule estimateReadFiltering:
    [...]
    output:
        "deepTools_qc/estimateReadFiltering/{sample}_filtering_estimation.txt"
    log:
        out = "deepTools_qc/logs/estimateReadFiltering.{sample}.out",
        err = "bamCoverage/logs/estimateReadFiltering.{sample}.err"
    [...]
```

**Comment by dpryan79** [comment]
This is implemented in `develop` now.
