### ISSUE TITLE
HiC: name 'smaple_dict' is not defined

### ISSUE THREAD

**Issue by millerh1** [maxplanck-ie/snakepipes#472]
Using a default install of the most recent snakePipes I was unable to start the HiC workflow with a specified sampleSheet. There was an `error code of 1` error, but the python traceback showed this line:

```
NameError in line 127 of /home/UTHSCSA/millerh1/miniconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/workflows/HiC/Snakefile:
name 'smaple_dict' is not defined
```

To fix this, I just edited line 127 of the Snakefile from `print(smaple_dict)` to `print(sample_dict)` and it works fine now.

**Comment by LeilyR** [comment]
Hi, I have noticed that typo in our current version few days ago and have already fixed. However it is still in develop branch and will be released with the next version very soon. Is it possible for you to use the develop for next couple of days?

**Comment by millerh1** [comment]
Sure! Thank you!
