### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by csijcs** [maxplanck-ie/snakepipes#473]
Hello, really cool tool. I would like to get this setup for our lab to use, and I've run into a few issues that I'm hoping could be added to the pipelines.

**DNA-mapping**

Single-end data: The program does not seem to automatically detect single-end data without a read name extension. It gives an error that there are no files in the folder. It seems that the reads option is required in the DNA-mapping defaults.yaml file, so even for single-end data it is looking for a read name extension. I can give them all one, but would be easier if it could use the files directly, which I thought it was supposed to. Or if it could be given a single-end option like the ChIP-seq pipeline.

Aligner: It would be nice to have the option to choose the aligner here. Especially since STAR are bwa are used by other arms of the pipeline and the indices are available. We typically align with bwa and would like to stick with that for now.

**ChIP-seq**: 
It would be nice to be able to provide bam files only and have the pipeline run deepTools, Sambamba, and setup the folder structure for the pipeline. Can of course be done manually, but would make it easier on some users.

Thanks,
J

**Comment by csijcs** [comment]
I'm sort of answering my own question here, but I see this is related to #468, and possibly other bugs. In digging into this a bit I realized that there are a lot of places in the code for the single end option (i.e. if paired = FALSE) that it still uses reads[0]. For example in the multiQC.snakefile, the TrimGalore.snakefile, and the FastQC.snakefile. Also the DNA-mapping/Snakefile the idxRange = 1, and this adds the reads suffix back to the sample name. Additionally, in the FASTQ.snakefile I added a rule for FASTQ and made the FASTQ1 and FASTQ2 rule "if paired". This does throw a warning:
```
localrules directive specifies rules that are not present in the Snakefile:
	FASTQ2
	FASTQ1
```
but seems to run fine. I also had to add the FASTQ to the Snakefile local rules.

One major issue in automatically recognizing the single-end reads without a read suffix is in the get_sample_names definition.  The `else: continue` seemed to be messing with the proper functionality for some reason, as I found by removing it the file names were correctly identified.

Another minor issue is in the defaults.yaml for DNA mapping downloaded with the package, the value for reads: [_R1, _R2] causes problems, I believe it should be ['_R1', '_R2']. If this is blank the default has the correct notation.

Also, the fix for the bwa aligner was quite simple. I just had to replace 'Bowtie2' in the code with mapping_prg, and then specify BWA in the yaml and make a BWA.snakefile.

Hope this is helpful

**Comment by LeilyR** [comment]
Hello csijcs,
Thank you for your interest, we are working on the option to choose the aligner and if I am not wrong the issue with single end is already solved and is going to be out with the next release. Also we have already thought of starting from bam files, which you can activate it by `--fromBam` flag

**Comment by csijcs** [comment]
Thanks, I didn't know about the --fromBam flag. It doesn't show up in the ChIP-seq options or documentation. I'll give that a try. Looking forward to the next release.

**Comment by LeilyR** [comment]
Here is where you can find `fromBam`: 
https://github.com/maxplanck-ie/snakepipes/blob/master/snakePipes/workflows/ChIP-seq/ChIP-seq#L84

**Comment by csijcs** [comment]
I tried that and it worked pretty well, thanks! I did get an error  in the CSAW, not sure why:
```
Mode : Differential Binding
bam files used: 
../filtered_bam/wz2951.filtered.bam../filtered_bam/wz2952.filtered.bam../filtered_bam/wz2953.filtered.bam../filtered_bam/wz2954.filtered.bam../filtered_bam/wz2955.filtered.bam../filtered_bam/wz2956.filtered.bam../filtered_bam/wz2957.filtered.bam../filtered_bam/wz2958.filtered.bam../filtered_bam/wz2959.filtered.bam../filtered_bam/wz2960.filtered.bam../filtered_bam/wz2961.filtered.bam../filtered_bam/wz2962.filtered.bam../filtered_bam/wz2963.filtered.bam../filtered_bam/wz2964.filtered.bam../filtered_bam/wz2965.filtered.bam../filtered_bam/wz2966.filtered.bam../filtered_bam/wz2983.filtered.bam../filtered_bam/wz2984.filtered.bam../filtered_bam/wz2985.filtered.bam../filtered_bam/wz2986.filtered.bam../filtered_bam/wz2987.filtered.bam../filtered_bam/wz2988.filtered.bam../filtered_bam/wz2989.filtered.bam../filtered_bam/wz2990.filtered.bam../filtered_bam/wz2991.filtered.bam../filtered_bam/wz2992.filtered.bam../filtered_bam/wz2993.filtered.bam../filtered_bam/wz2994.filtered.bam../filtered_bam/wz2995.filtered.bam../filtered_bam/wz2996.filtered.bam../filtered_bam/wz2997.filtered.bam../filtered_bam/wz2998.filtered.bam../filtered_bam/wz3052.filtered.bam
Counting reads in windows.. windows with total counts < 20 are discarded
Checking fragment sizes
Checking strand cross-correlation
Checking read distribution around putative peaks
Plotting
Error in hist.default(log10(fragsize$sizes), breaks = 50, xlab = " log10(Fragment sizes)",  : 
  character(0)
Calls: makeQCplots_chip -> hist -> hist.default
In addition: Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf
Execution halted
```
We typically use DiffBind, so I will probably look into incorporating this into the pipeline downstream instead of CSAW anyways.
Also, it looks like most logs are being directed to the .err file instead of the .out file, not sure why.
One last question, is it possible to adjust the q-value cutoff for MACS2 in the ChIP-seq pipeline without altering the MACS2.snakefile? I don't see an option for it

**Comment by katsikora** [comment]
Hi,

do you have very low coverage data? IT looks like fragment size calculation went wrong for some reason. Does deepTools QC look normal? 

We have a q-value parameter passed to MACS2 in the ATACseq pipeline. We can add it to ChIPseq as well. If you want to do it yourself, you'll need to add it in 3 places 1)defaults.yaml for the ChIPseq workflow, 2)python wrapper for the ChIPseq workflow 3)MACS2 rule in the snakefile included by the ChIPseq workflow.

**Comment by csijcs** [comment]
They all look pretty good, around 20M mapped reads or so. These are single end reads, so it's not clear to me how the fragment size is being calculated in the pipline

**Comment by katsikora** [comment]
Oh I see, currently CSAW code attempts to plot fragment size distribution assuming paired ends. We can fix that. 

For now, you can comment out `makeQCplots_chip(bam.file = first_bam, outplot = "QCplots_first_sample.pdf", pe.param = pe_param)`  and `makeQCplots_chip(bam.file = last_bam, outplot = "QCplots_last_sample.pdf", pe.param = pe_param)` in CSAW.R under shared/rscripts.

For SE data, a default value of `200` is used for fragment size. If you wish to update that value, you have to change `fragment_length: 200`  in a config.yaml and pass that to the pipeline via `-c` .

To be honest the support for SE data is rather buggy at the moment.

**Comment by csijcs** [comment]
No worries, I'm figuring most of it out and getting it sorted. Thanks for your help!

**Comment by katsikora** [comment]
Most/All of these requests have been implemented in the develop branch now.
