### ISSUE TITLE
various issues from users

### ISSUE THREAD

**Issue by katsikora** [maxplanck-ie/snakepipes#475]
- [x] test and document workflow usage with single ends
- [x] document supported and unsupported read extentions
- [x] fix custom config error related to snakemake options being a list rather than a string
- [x] add qval as user-modifiable parameter to ChIPseq (for MACS2)
- [x] fix CSAW QC plots for SE data
- [x] fix MACS2 for SE data
- [x] update histone HMM env yaml
- [x] make Salmon_wasabi a localrule
- [x] unhide --fromBAM and --bamExt
- [x] fix rule sleuth_Salmon
- [x] fix rule DESeq2_Salmon
- [x] output nearestGene.session_info.txt in the correct folder

**Comment by dpryan79** [comment]
I've modified my PR to support any read extension through the `--ext` command line option.

**Comment by katsikora** [comment]
alright! will the SRA file extentions _1.fastq.gz, _2.fastq.gz work? (used to fail previously)

**Comment by dpryan79** [comment]
If one specifies `--reads _1 _2` then yes.

**Comment by katsikora** [comment]
implemented in Devon's PR + PR #484
