### ISSUE TITLE
Salmon_wasabi fails in SE+PE RNAseq

### ISSUE THREAD

**Issue by katsikora** [maxplanck-ie/snakepipes#482]
Activating conda environment: /data/processing/sikora/snakePipes_envs/de25c544
Error in H5Fclose(file$H5Identifier) : 
  HDF5. File accessibilty. Unable to close file.
Calls: prepare_fish_for_sleuth ... <Anonymous> -> h5write.default -> h5closeitLoc -> H5Fclose
Execution halted

 *** caught segfault ***
address 0x558, cause 'memory not mapped'
An irrecoverable exception occurred. R is aborting now ...
/usr/bin/bash: line 1: 177519 Segmentation fault      (core dumped) Rscript /home/sikora/.local/lib/python3.6/site-packages/snakePipes/shared/rscripts/wasabi.R Salmon/ERR2130634/
[Fri Aug  9 09:10:41 2019]
Error in rule Salmon_wasabi:
    jobid: 0
    output: Salmon/ERR2130634/abundance.h5
    conda-env: /data/processing/sikora/snakePipes_envs/de25c544

**Comment by dpryan79** [comment]
This looks like a bug in the hdf5 library :(

**Comment by katsikora** [comment]
As a dirty fixed, I made Salmon_wasabi a localrule, as it works on maximus.

But it might still fail for other users.

Not see with PE reads, don't ask me why, quant.sf files look totally normal.

**Comment by katsikora** [comment]
..Error in H5Dread(h5dataset = h5dataset, h5spaceFile = h5spaceFile, h5spaceMem = h5spaceMem,  : 
  HDF5. Dataset. Read failed.

sleuth.Salmon fails, too (SE + PE RNAseq)

**Comment by katsikora** [comment]
It's failing with hdf5 version 1.8.12-8 (cluster). It's working with 1.8.12-10 (local) .

I will test this issue again when we have hdf5 version updated on the cluster.

**Comment by katsikora** [comment]
The problem is currently unresolved; wasabi + sleuth both fail on cluster nodes while they work on a local node, even after hdf5 library update to the same version.

**Comment by dpryan79** [comment]
If you give me an example I can use then I'll track this down tomorrow.

**Comment by katsikora** [comment]
source activate /data/processing/sikora/snakePipes_envs/de25c544

cd /data/processing/bioinfo-core/requests/RNAseq_PE_wWzFYAbC_test_dev_RNA-seq/analysis

Rscript /data/boehm/sikora/miniconda3/lib/python3.6/site-packages/snakePipes/shared/rscripts/wasabi.R Salmon/SRR3160241/

Thanks!
