### ISSUE TITLE
DNA-mapping, error in rule create_snpgenome

### ISSUE THREAD

**Issue by GinaRe** [maxplanck-ie/snakepipes#488]
The "rule create_snpgenome" ends in an error:
Can't move to ./snp_genome/line_362_full_sequence/

The problem could be related to the folder ./snp_genome/ only containing a folder "SNPs_line_362"

My command:
DNA-mapping -m allelic-mapping --VCFfile ../../dgrp2.vcf --strains 'line_362 , line_555' \
--dedup --trim --fastqc --mapq 5 --bw-binsize 10 --plotFormat pdf -i ../fastq --DAG -j 20 -o . dm3

I used snakepipes/1.2.3

**Comment by GinaRe** [comment]
The folder:
/data/akhtar/group/ramirez/Maria_allele-spec_ChIP-seq/test_inputs_Dafne/dm3

**Comment by dpryan79** [comment]
Ugh, SNPsplit only works with VCF files from the mouse genome project.
