### ISSUE TITLE
createIndice fails: error in rule gtf2bet

### ISSUE THREAD

**Issue by Remi-Montagne** [maxplanck-ie/snakepipes#490]
Hello,

I am trying to create a new index for the genome of my organism but the workflow won't work.

I am using conda 4.7 and the latest version of snakePipes and here is the result I get:

> Failed to create temp dir under temp path prefix (/data/extended/)! Try fallback: /home/remi/anaconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/organisms/ ...
> Building DAG of jobs...
> Using shell: /bin/bash
> Provided cores: 5
> Rules claiming more threads will be scaled down.
> Job counts:
>         count   jobs
>         1       all
>         1       gtf2BED
>         2
> 
> [Wed Sep  4 15:40:52 2019]
> rule gtf2BED:
>     input: /home/remi/anaconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/organisms/annotation/genes.gtf
>     output: /home/remi/anaconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/organisms/annotation/genes.bed
>     jobid: 6
> 
> Activating conda environment: /home/remi/anaconda3/envs/9b52447f46f62928cde4f6c112298687
> Word count less than 8  Bad line 1 of /dev/stdin:
> 
> [Wed Sep  4 15:40:53 2019]
> Error in rule gtf2BED:
>     jobid: 6
>     output: /home/remi/anaconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/organisms/annotation/genes.bed
>     conda-env: /home/remi/anaconda3/envs/9b52447f46f62928cde4f6c112298687
>     shell:
>         
>         awk '{if ($3 != "gene") print $0;}' /home/remi/anaconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/organisms/annotation/genes.gtf             | grep -v "^#"             | gtfToGenePred /dev/stdin /dev/stdout             | genePredToBed stdin /home/remi/anaconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/organisms/annotation/genes.bed
>         
>         (exited with non-zero exit code)
> 
> Removing output files of failed job gtf2BED since they might be corrupted:
> /home/remi/anaconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/organisms/annotation/genes.bed
> Job failed, going on with independent jobs.
> Exiting because a job execution failed. Look above for error message
> Complete log: /home/remi/anaconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/organisms/.snakemake/log/2019-09-04T154050.526041.snakemake.log
> Error: snakemake returned an error code of 1, so processing is incomplete!

Do you know what the problem is ?

Thank you

**Comment by LeilyR** [comment]
did you use the same path you have your program installed to write the output on it? that is already not a good practice.
However i suppose your error comes from a formatting issue in your genes.gtf file. ` Word count less than 8 Bad line 1 of /dev/stdin:`

**Comment by Remi-Montagne** [comment]
Indeed, the problem came from spaces that replaced the tabs...

Thank you
