### ISSUE TITLE
error DNA-mapping, rule Bowtie2: invalid option

### ISSUE THREAD

**Issue by Remi-Montagne** [maxplanck-ie/snakepipes#495]
Hello,

I have recently tried to align reads with DNA-mapping but I have run into an error.

Here is my command line (I didn't use a .yaml file): 

> DNA-mapping sacCer3 -i /media/remi/Disk1/Yeast/data/TADs/Chip-Seq/Chip-Seq_cohesin/Input_snakePipes/ -o /media/remi/Disk1/Yeast/data/TADs/Chip-Seq/Chip-Seq_cohesin/test/ --local -j 6 --DAG --mapq 20

And here is the error:

> Activating conda environment: /home/remi/anaconda3/envs/93bd4eae3c59f7593166a198d7b8e6d5
> sort: invalid option -- 'T'
> sort: invalid option -- 'O'
> open: No such file or directory
> [bam_sort_core] fail to open file /media/remi/Disk1/Yeast/data/TADs/Chip-Seq/Chip-Seq_cohesin/Output_snakePipes_ChIP-seq_bin150bp/tmp.snakemake.uDsfWnjc/SRR2065097_ChIP-Scc1_IP
> [samopen] SAM header is present: 16 sequences.
> [Tue Sep 24 13:04:41 2019]
> Error in rule Bowtie2:
>     jobid: 20
>     output: Bowtie2/SRR2065097_ChIP-Scc1_IP.Bowtie2_summary.txt, Bowtie2/SRR2065097_ChIP-Scc1_IP.sorted.bam
>     conda-env: /home/remi/anaconda3/envs/93bd4eae3c59f7593166a198d7b8e6d5
>     shell:
>         bowtie2 -x /media/remi/Disk1/Yeast/data/ref_genomes/Scerevisiae_S288C_gtf_tss/createindex/BowtieIndex/genome -U FASTQ/SRR2065097_ChIP-Scc1_IP_R1.fastq.gz  --rg-id SRR2065097_ChIP-Scc1_IP --rg CN:mpi-ie_deep_sequencing_unit --rg DS:SRR2065097_ChIP-Scc1_IP --rg PL:ILLUMINA --rg SM:SRR2065097_ChIP-Scc1_IP -p 6 2> Bowtie2/SRR2065097_ChIP-Scc1_IP.Bowtie2_summary.txt | samtools view -Sbu - | samtools sort -m 2G -T ${TMPDIR}SRR2065097_ChIP-Scc1_IP -@ 2 -O bam - > Bowtie2/SRR2065097_ChIP-Scc1_IP.sorted.bam
>         (exited with non-zero exit code)

I am using a recent version of snakePipes. It looks like there is a problem with samtools or pysam but i can't really say why. Do you know how to fix it ?

Thanks

**Comment by dpryan79** [comment]
Can you run the following and let me know what you get?

    conda activate 93bd4eae3c59f7593166a198d7b8e6d5
    conda list

I wonder if for some reason a really old version of samtools got installed in there.

**Comment by Remi-Montagne** [comment]
I does not look like it though:

> # packages in environment at /home/remi/anaconda3/envs/93bd4eae3c59f7593166a198d7b8e6d5:
> #
> # Name                    Version                   Build  Channel
> _libgcc_mutex             0.1                        main  
> _r-mutex                  1.0.0               anacondar_1  
> bcftools                  1.9                  ha228f0b_4    bioconda
> binutils_impl_linux-64    2.31.1               h6176602_1  
> binutils_linux-64         2.31.1               h6176602_7  
> bioconductor-biobase      2.42.0           r351h14c3975_1    bioconda
> bioconductor-biocgenerics 0.28.0                   r351_1    bioconda
> bioconductor-biocparallel 1.16.6           r351h1c2f66e_0    bioconda
> bioconductor-biostrings   2.50.2           r351h14c3975_0    bioconda
> bioconductor-delayedarray 0.8.0            r351h14c3975_0    bioconda
> bioconductor-genomeinfodb 1.18.1                   r351_0    bioconda
> bioconductor-genomeinfodbdata 1.2.1                    r351_0    bioconda
> bioconductor-genomicalignments 1.18.1           r351h14c3975_0    bioconda
> bioconductor-genomicranges 1.34.0           r351h14c3975_0    bioconda
> bioconductor-iranges      2.16.0           r351h14c3975_0    bioconda
> bioconductor-noiseq       2.26.1                   r351_0    bioconda
> bioconductor-rsamtools    1.34.0           r351hf484d3e_0    bioconda
> bioconductor-rtracklayer  1.42.1           r351h9d9f1b6_1    bioconda
> bioconductor-s4vectors    0.20.1           r351h14c3975_0    bioconda
> bioconductor-summarizedexperiment 1.12.0                   r351_0    bioconda
> bioconductor-xvector      0.22.0           r351h14c3975_0    bioconda
> bioconductor-zlibbioc     1.28.0           r351h14c3975_0    bioconda
> bowtie2                   2.3.5            py37he860b03_0    bioconda
> bwidget                   1.9.11                        1  
> bzip2                     1.0.6             h14c3975_1002    conda-forge
> ca-certificates           2019.5.15                     1  
> cairo                     1.16.0            ha4e643d_1000    conda-forge
> certifi                   2019.9.11                py37_0  
> curl                      7.64.1               hf8cf82a_0    conda-forge
> fontconfig                2.13.1            he4413a7_1000    conda-forge
> freetype                  2.10.0               he983fc9_0    conda-forge
> gcc_impl_linux-64         7.3.0                habb00fd_1    conda-forge
> gcc_linux-64              7.3.0                h553295d_7    conda-forge
> gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
> gfortran_impl_linux-64    7.3.0                hdf63c60_1  
> gfortran_linux-64         7.3.0                h553295d_7  
> glib                      2.58.3            hf63aee3_1001    conda-forge
> graphite2                 1.3.13            hf484d3e_1000    conda-forge
> gsl                       2.4               h294904e_1006    conda-forge
> gxx_impl_linux-64         7.3.0                hdf63c60_1    conda-forge
> gxx_linux-64              7.3.0                h553295d_7    conda-forge
> harfbuzz                  2.4.0                h37c48d4_0    conda-forge
> htslib                    1.9                  ha228f0b_7    bioconda
> icu                       58.2              hf484d3e_1000    conda-forge
> jpeg                      9c                h14c3975_1001    conda-forge
> krb5                      1.16.3            h05b26f9_1001    conda-forge
> libblas                   3.8.0               10_openblas    conda-forge
> libcblas                  3.8.0               10_openblas    conda-forge
> libcurl                   7.64.1               hda55be3_0    conda-forge
> libdeflate                1.0                  h14c3975_1    bioconda
> libedit                   3.1.20170329      hf8c457e_1001    conda-forge
> libffi                    3.2.1             he1b5a44_1006    conda-forge
> libgcc-ng                 8.2.0                hdf63c60_1  
> libgfortran-ng            7.3.0                hdf63c60_0  
> libiconv                  1.15              h516909a_1005    conda-forge
> libpng                    1.6.37               hed695b0_0    conda-forge
> libssh2                   1.8.2                h22169c7_2    conda-forge
> libstdcxx-ng              8.2.0                hdf63c60_1  
> libtiff                   4.0.10            h648cc4a_1001    conda-forge
> libuuid                   2.32.1            h14c3975_1000    conda-forge
> libxcb                    1.13              h14c3975_1002    conda-forge
> libxml2                   2.9.9                h13577e0_0    conda-forge
> make                      4.2.1             h14c3975_2004    conda-forge
> ncurses                   6.1               hf484d3e_1002    conda-forge
> openblas                  0.3.6                h6e990d7_2    conda-forge
> openjdk                   11.0.1            h516909a_1016    conda-forge
> openssl                   1.1.1d               h7b6447c_1  
> pango                     1.40.14           h4ea9474_1004    conda-forge
> pcre                      8.41              hf484d3e_1003    conda-forge
> perl                      5.26.2            h516909a_1006    conda-forge
> pip                       19.1                     py37_0    conda-forge
> pixman                    0.34.0            h14c3975_1003    conda-forge
> pthread-stubs             0.4               h14c3975_1001    conda-forge
> pysam                     0.15.3           py37h5ad169c_0    bioconda
> python                    3.7.3                h5b0a415_0    conda-forge
> qualimap                  2.2.2b                        1    bioconda
> r-base                    3.5.1             h271c98b_1006    conda-forge
> r-bh                      1.69.0_1         r351h6115d3f_0    conda-forge
> r-bitops                  1.0_6           r351h96ca727_1002    conda-forge
> r-formatr                 1.6              r351h6115d3f_0    conda-forge
> r-futile.logger           1.4.3           r351h6115d3f_1001    conda-forge
> r-futile.options          1.0.1           r351h6115d3f_1000    conda-forge
> r-getopt                  1.20.3                   r351_0    conda-forge
> r-lambda.r                1.2.3           r351h6115d3f_1000    conda-forge
> r-lattice                 0.20_38         r351h96ca727_1000    conda-forge
> r-matrix                  1.2_17           r351hcdcec82_0    conda-forge
> r-matrixstats             0.54.0          r351h96ca727_1000    conda-forge
> r-optparse                1.6.1            r351h6115d3f_0    conda-forge
> r-rcurl                   1.95_4.12        r351hcdcec82_0    conda-forge
> r-snow                    0.4_3           r351h6115d3f_1000    conda-forge
> r-xml                     3.98_1.19        r351hcdcec82_0    conda-forge
> readline                  7.0               hf8c457e_1001    conda-forge
> samtools                  1.9                 h10a08f8_12    bioconda
> setuptools                41.0.1                   py37_0    conda-forge
> sqlite                    3.26.0            h67949de_1001    conda-forge
> tbb                       2019.6               hc9558a2_0    conda-forge
> tk                        8.6.9             h84994c4_1001    conda-forge
> tktable                   2.10                 h14c3975_0  
> wheel                     0.33.4                   py37_0    conda-forge
> xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
> xorg-libice               1.0.9             h516909a_1004    conda-forge
> xorg-libsm                1.2.3             h84519dc_1000    conda-forge
> xorg-libx11               1.6.7             h14c3975_1000    conda-forge
> xorg-libxau               1.0.9                h14c3975_0    conda-forge
> xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
> xorg-libxext              1.3.4                h516909a_0    conda-forge
> xorg-libxrender           0.9.10            h516909a_1002    conda-forge
> xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
> xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
> xorg-xproto               7.0.31            h14c3975_1007    conda-forge
> xz                        5.2.4             h14c3975_1001    conda-forge
> zlib                      1.2.11            h14c3975_1004    conda-forge
>

**Comment by steffenheyne** [comment]
can you do 
```
conda activate 93bd4eae3c59f7593166a198d7b8e6d5
samtools --version
```
?

**Comment by Remi-Montagne** [comment]
Ok, so indeed there was a path to an old version of samtools in my variable $PATH.

> Program: samtools (Tools for alignments in the SAM format)
> Version: 0.1.19-44428cd
> 
> Usage:   samtools <command> [options]
> 
> Command: view        SAM<->BAM conversion
>          sort        sort alignment file
>          mpileup     multi-way pileup
>          depth       compute the depth
>          faidx       index/extract FASTA
>          tview       text alignment viewer
>          index       index alignment
>          idxstats    BAM index stats (r595 or later)
>          fixmate     fix mate information
>          flagstat    simple stats
>          calmd       recalculate MD/NM tags and '=' bases
>          merge       merge sorted alignments
>          rmdup       remove PCR duplicates
>          reheader    replace BAM header
>          cat         concatenate BAMs
>          bedcov      read depth per BED region
>          targetcut   cut fosmid regions (for fosmid pool only)
>          phase       phase heterozygotes
>          bamshuf     shuffle and group alignments by name

PATH: 

> /home/remi/tools/ucsc:/home/remi/tools/tabix-0.2.6:/home/remi/tools/samtools-0.1.19:/home/remi/tools/bedtools-2.21.0/bin:/usr/local/ucsc_bioinfo_tools:/usr/local/sratoolkit.2.9.6-ubuntu64/bin:/home/remi/anaconda3/envs/93bd4eae3c59f7593166a198d7b8e6d5/bin:/home/remi/anaconda3/condabin:/home/remi/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

**Comment by steffenheyne** [comment]
ok, great...but you should also get rid of the other things like bedtools etc as all these can lead to unwanted and unknown side effects in combination with conda

**Comment by Remi-Montagne** [comment]
I corrected my $PATH variable and snakePipes now works just fine.

I will follow your advise and remove superfluous paths.

Thank you !
