### ISSUE TITLE
Error in rule bamCompare_subtract

### ISSUE THREAD

**Issue by Leif78** [maxplanck-ie/snakepipes#498]
Hi,
I run the ATAC-seq pipeline with the command:
ATAC-seq -d /home/leif/10mGy/mapped --sampleSheet /home/leif/10mGy/samplesheet.tsv --local GRCz11

It runs for a while and the first error message is this:

[Thu Oct  3 00:14:13 2019]
rule bamCompare_subtract:
    input: MACS2/G_C3.short.cleaned.bam, MACS2/G_C3.short.cleaned.bam.bai
    output: deepTools_ATAC/bamCompare/G_C3.filtered.bw
    log: deepTools_ATAC/logs/bamCompare.G_C3.filtered.out, deepTools_ATAC/logs/bamCompare.G_C3.filtered.out
    jobid: 17
    benchmark: deepTools_ATAC/.benchmark/deepTools_ATAC/logs/bamCompare.G_C3.filtered.benchmark
    wildcards: sample=G_C3
    threads: 5

Activating conda environment: /home/leif/anaconda3/envs/3a9f67754a2de46efdfe958091b679ba
[Thu Oct  3 00:14:32 2019]
Error in rule bamCompare_subtract:
    jobid: 17
    output: deepTools_ATAC/bamCompare/G_C3.filtered.bw
    log: deepTools_ATAC/logs/bamCompare.G_C3.filtered.out, deepTools_ATAC/logs/bamCompare.G_C3.filtered.out (check log file(s) for error message)
    conda-env: /home/leif/anaconda3/envs/3a9f67754a2de46efdfe958091b679ba
    shell:
        
    bamCoverage -b MACS2/G_C3.short.cleaned.bam                 -o deepTools_ATAC/bamCompare/G_C3.filtered.bw                 --binSize 25                 -p 5                 --normalizeUsing RPGC                 --effectiveGenomeSize 1368780147                                                   --extendReads > deepTools_ATAC/logs/bamCompare.G_C3.filtered.out 2> deepTools_ATAC/logs/bamCompare.G_C3.filtered.out
    
        (exited with non-zero exit code)

Job failed, going on with independent jobs.

Any suggestions for what we can do?

**Comment by katsikora** [comment]
Hi,
Can you look up the exact error message in your deepTools_ATAC/logs folder ?
Also, did just one or multiple bam files fail?
Best, 
Katarzyna

**Comment by Leif78** [comment]
Hi,
I do not see any error message in the deepTools_ATAC/logs folder. It failed for all six bam files.
However, the deepTools_ATAC/logs/bamCompare.G_C1.filtered.out file looks like this:

normalization: 1x (effective genome size 1368780147)
Traceback (most recent call last):
  File "/home/leif/anaconda3/envs/3a9f67754a2de46efdfe958091b679ba/bin/bamCoverage", line 12, in <module>
    main(args)
  File "/home/leif/anaconda3/envs/3a9f67754a2de46efdfe958091b679ba/lib/python3.6/site-packages/deeptools/bamCoverage.py", line 162, in main
    scale_factor = get_scale_factor(args, stats)
  File "/home/leif/anaconda3/envs/3a9f67754a2de46efdfe958091b679ba/lib/python3.6/site-packages/deeptools/getScaleFactor.py", line 254, in get_scale_factor
    scale_factor *= 1.0 / current_coverage
ZeroDivisionError: float division by zero

Leif

**Comment by Leif78** [comment]
This is the complete log from the run:

[ATAC-seq_run-1.log](https://github.com/maxplanck-ie/snakepipes/files/3685520/ATAC-seq_run-1.log)

Leif

**Comment by vivekbhr** [comment]
maybe double check if you have empty bam files after filtering

**Comment by katsikora** [comment]
Perhaps you have very low coverage? How did the mapping step go, did you get good mapping rate?
If you've run DNA-mapping pipeline beforehand, you should have some overview of the quality metrics in the multiQC folder.

**Comment by Leif78** [comment]
After filtering, the filtered.bam files are about 6 GB while MACS2/sample.short.cleaned.bam is about 260 MB. 
It was a mapping rate of about 55%, and about 20M unique reads according to multiQC.

**Comment by katsikora** [comment]
Hi Leif,
it looks like you've lost >90% of your reads during fragment size filtering. The default fragment size cutoff in the ATAC-seq pipeline is 150bp. 
What is the fragment size distribution you get in deepTools_qc from the DNA-mapping pipeline?
Depending on the quality of the experiment, I think we see at least 30-50% fragments retained in ATACseq.
