### ISSUE TITLE
Restructure scRNA-seq pipeline

### ISSUE THREAD

**Issue by dpryan79** [maxplanck-ie/snakepipes#503]
The current scRNA-seq is quite limited and only handles low-throughput methods. It would be desirable to either spin that off as a renamed pipeline (replacing it with a pipeline based on salmon/alevin) or add an option to ignore all of the low-throughput components and instead assume 1000+ cells and using salmon/alevin. This would then handle 10x and other high-throughput methods.

**Comment by katsikora** [comment]
We now have mode STARsolo and mode Alevin in develop. Mode Gruen will be deprecated towards the end of the year.
