### ISSUE TITLE
variable matrix formats in HiC pipeline

### ISSUE THREAD

**Issue by LeilyR** [maxplanck-ie/snakepipes#514]
I think it is a good idea to give users the opportunity to get matrices of their desired format. I will work on it.

**Comment by AdrijaK** [comment]
...even a .hic format? (That would be amazing!)

**Comment by LeilyR** [comment]
Hi @AdrijaK, By adding other formats I mainly meant .cool on top the the current .h5. We are using hicexplorer as the tool to analyse the hit data and it doesn't support .hic format. But if you generate your matrices in .cool or .h5 by our pipeline, hicexplorer offers a variety of tools for further downstream analysis. Feel free to have a look at it under https://hicexplorer.readthedocs.io/en/latest/

**Comment by LeilyR** [comment]
#638 addresses this issue
