### ISSUE TITLE
PeriodicWildcardError in RNA-seq

### ISSUE THREAD

**Issue by mptrsen** [maxplanck-ie/snakepipes#518]
I am using `RNA-seq` in alignment-only mode and am getting a PeriodicWildcardError from sambamba.snakefile. I am using a custom genome file, but that should not matter because the error has to do with the input fastq filenames, as far as I understand:

    $ RNA-seq --mode alignment --DAG -i data/clean/gill1 -o results/snakepipes/gill1 ~/configs/Pmar-genome.yaml
    localrules directive specifies rules that are not present in the Snakefile:
        sleuth_Salmon
        Salmon_wasabi

    Building DAG of jobs...
    PeriodicWildcardError in line 7 of /data/processing/petersen/lamprey-transcriptome/code/conda/lib/python3.6/site-packages/snakePipes/shared/rules/sambamba.snakefile:
    The value .sorted in wildcard sample is periodically repeated (gill1.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted). This would lead to an infinite recursion. To avoid this, e.g. restrict the wildcards in this rule to certain values.
    localrules directive specifies rules that are not present in the Snakefile:
        Salmon_wasabi
        sleuth_Salmon

    Building DAG of jobs...
    PeriodicWildcardError in line 7 of /data/processing/petersen/lamprey-transcriptome/code/conda/lib/python3.6/site-packages/snakePipes/shared/rules/sambamba.snakefile:
    The value .sorted in wildcard sample is periodically repeated (gill1.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted). This would lead to an infinite recursion. To avoid this, e.g. restrict the wildcards in this rule to certain values.
    Error: snakemake returned an error code of 1, so processing is incomplete!

I have not created an analysis-specific config file, all parameters are passed as command line options. The only thing I changed in the RNA-seq config was

    aligner: Bowtie2

My Fastq file names end in _R1.fastq.gz/_R2.fastq.gz.

Let me know if you need additional info. Thanks!

**Comment by katsikora** [comment]
Hi,

Bowtie2 is not an option for RNAseq in our workflows. 
Please choose between HISAT2 and STAR.

Best,
Katarzyna

**Comment by mptrsen** [comment]
OK, thank you, that gets me somewhere else. I think the error is misleading in that case; it would be better to refuse anything except HISAT2 and STAR for RNA-seq in the first place.

**Comment by dpryan79** [comment]
Editing the config file is a rather advanced thing to do, if you just specify everything with command line options I think it would have thrown an error related to the aligned.

**Comment by katsikora** [comment]
I think we have to add 'choices' to aligner in argparser for RNAseq.

**Comment by katsikora** [comment]
fixed in PR #516
