### ISSUE TITLE
RNA-seq --fromBam gives ambiguous file error (due to umi tools)

### ISSUE THREAD

**Issue by steffenheyne** [maxplanck-ie/snakepipes#519]
```
Building DAG of jobs...
AmbiguousRuleException:
Rules link_bam_bai_external and filter_reads are ambiguous for the file filtered_bam/EpM96_P2.filtered.bam.
Consider starting rule output with a unique prefix, constrain your wildcards, or use the ruleorder directive.
Wildcards:
	link_bam_bai_external: sample=EpM96_P2
	filter_reads: sample=EpM96_P2
Expected input files:
	link_bam_bai_external: EXTERNAL_BAM/EpM96_P2.bam EXTERNAL_BAM/EpM96_P2.bam.bai
	filter_reads: EXTERNAL_BAM/EpM96_P2.bamExpected output files:
	link_bam_bai_external: filtered_bam/EpM96_P2.filtered.bam filtered_bam/EpM96_P2.filtered.bam.bai
	filter_reads: filtered_bam/EpM96_P2.filtered.bam
```

**Comment by steffenheyne** [comment]
move `include: os.path.join(maindir, "shared", "rules", "umi_tools.snakefile")` to `if not fromBAM:` solves this for the moment if no UMI tools stuff is wanted

**Comment by LeilyR** [comment]
Do we expect the user to provide the filtered bams or raw bams for the from bam mode? if raw bam then i can add it to from bam mode.

**Comment by steffenheyne** [comment]
so far we used the bams as they were given, whatever the user has done with it, but to be meaningful, they should be filtered as our filtered bams in case we start from fastq

but actually, for RNA-seq, we don't do any filtering I think
