### ISSUE TITLE
mktemp: failed to create directory via template

### ISSUE THREAD

**Issue by zifeng9527** [maxplanck-ie/snakepipes#521]
Hi, thanks for your providing such a powerfull tools.

I installed the pipes following instructions. However, when run the DNA-mapping pipes, I encontered the problem " mktemp: failed to create directory via template ‘/data/extended//snakepipes.XXXXXXXXXX’: No such file or directory" 

Anybody can help me?

More info:
CentOS7
(snakePipes) root@bio814:~# uname -a
Linux bio814 3.10.0-1062.1.1.el7.x86_64 #1 SMP Fri Sep 13 22:55:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

(snakePipes) root@bio814:~# **snakePipes info**
Organism YAML files:
    /data/software/anaconda2/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/organisms/hs37d5.yaml
    /data/software/anaconda2/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/organisms/GRCz10.yaml
    /data/software/anaconda2/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/organisms/dm6.yaml
    /data/software/anaconda2/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/organisms/SchizoSPombe_ASM294v2.yaml
    /data/software/anaconda2/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/organisms/dm3.yaml
    /data/software/anaconda2/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/organisms/mm10_gencodeM13.yaml
    /data/software/anaconda2/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/organisms/hg19.yaml
    /data/software/anaconda2/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/organisms/hg38.yaml
    /data/software/anaconda2/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/organisms/mm10.yaml
    /data/software/anaconda2/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/organisms/mm9.yaml

The workflow-generic defaults.yaml file is:
    /data/software/anaconda2/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/defaults.yaml

The default cluster.yaml file. Its defaults are overridden by the per-workflow cluster.yaml files:
    /data/software/anaconda2/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/cluster.yaml

Workflow-specific cluster.yaml and defaults.yaml files are in:
    /data/software/anaconda2/envs/snakePipes/lib/python3.6/site-packages/snakePipes/workflows/HiC
    /data/software/anaconda2/envs/snakePipes/lib/python3.6/site-packages/snakePipes/workflows/ATAC-seq
    /data/software/anaconda2/envs/snakePipes/lib/python3.6/site-packages/snakePipes/workflows/scRNAseq
    /data/software/anaconda2/envs/snakePipes/lib/python3.6/site-packages/snakePipes/workflows/createIndices
    /data/software/anaconda2/envs/snakePipes/lib/python3.6/site-packages/snakePipes/workflows/preprocessing
    /data/software/anaconda2/envs/snakePipes/lib/python3.6/site-packages/snakePipes/workflows/ChIP-seq
    /data/software/anaconda2/envs/snakePipes/lib/python3.6/site-packages/snakePipes/workflows/WGBS
    /data/software/anaconda2/envs/snakePipes/lib/python3.6/site-packages/snakePipes/workflows/RNA-seq
    /data/software/anaconda2/envs/snakePipes/lib/python3.6/site-packages/snakePipes/workflows/DNA-mapping

**command line**
**DNA-mapping -i ./input_DNA-mapping -o ./out_DNA-mapping mm10 -v --trim --trimmer trimgalore --fastqc --plotFormat pdf --qualimap -j 92 --local --dedup --mapq 3**

TMPDIR=/data/extended/ PYTHONNOUSERSITE=True /data/software/anaconda2/envs/snakePipes/bin/snakemake --use-conda --conda-prefix /data/software/anaconda2/envs --latency-wait 300 --snakefile /data/software/anaconda2/envs/snakePipes/lib/python3.6/site-packages/snakePipes/workflows/DNA-mapping/Snakefile --jobs 92 --directory /data/home/001_wzf/004_ATAC-seq/901_wf/901_wf_ATAC_merge_snakePipes/out_DNA-mapping --configfile /data/home/001_wzf/004_ATAC-seq/901_wf/901_wf_ATAC_merge_snakePipes/out_DNA-mapping/DNA-mapping.config.yaml --keep-going --printshellcmds

Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 92
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	8	Bowtie2
	8	FASTQ1
	8	FASTQ2
	16	FastQC
	16	FastQC_on_trimmed
	8	Qualimap_bamqc
	8	Qualimap_bamqc_symlink_html
	8	Qualimap_bamqc_symlink_txt
	8	TrimGalore
	1	all
	8	bamCoverage
	8	bamCoverage_filtered
	1	bamPE_fragment_size
	8	estimate_read_filtering
	8	filter_reads
	1	multiBamSummary
	1	multiQC
	8	origFASTQ1
	8	origFASTQ2
	1	plotCorrelation_pearson
	1	plotCorrelation_spearman
	1	plotCoverage
	1	plotPCA
	8	sambamba_flagstat
	8	sambamba_markdup
	8	samtools_filter
	8	samtools_index
	8	samtools_index_filtered
	184

[Mon Dec  2 14:35:37 2019]
rule origFASTQ2:
    input: /data/home/001_wzf/004_ATAC-seq/901_wf/901_wf_ATAC_merge_snakePipes/input_DNA-mapping/ATACSeq_244_Rep2_raw_R2.fastq.gz
    output: originalFASTQ/ATACSeq_244_Rep2_raw_R2.fastq.gz
    jobid: 171
    wildcards: sample=ATACSeq_244_Rep2_raw

( [ -f originalFASTQ/ATACSeq_244_Rep2_raw_R2.fastq.gz ] || ln -s -r /data/home/001_wzf/004_ATAC-seq/901_wf/901_wf_ATAC_merge_snakePipes/input_DNA-mapping/ATACSeq_244_Rep2_raw_R2.fastq.gz originalFASTQ/ATACSeq_244_Rep2_raw_R2.fastq.gz )

...........

[Mon Dec  2 15:38:00 2019]
rule Bowtie2:
    input: FASTQ_TrimGalore/ATACSeq_521_Rep1_raw_R1.fastq.gz, FASTQ_TrimGalore/ATACSeq_521_Rep1_raw_R2.fastq.gz
    output: Bowtie2/ATACSeq_521_Rep1_raw.Bowtie2_summary.txt, Bowtie2/ATACSeq_521_Rep1_raw.sorted.bam
    jobid: 129
    benchmark: Bowtie2/.benchmark/Bowtie2.ATACSeq_521_Rep1_raw.benchmark
    wildcards: sample=ATACSeq_521_Rep1_raw
    threads: 24

            MYTEMP=$(mktemp -d ${TMPDIR:-/tmp}/snakepipes.XXXXXXXXXX);
            bowtie2             -X 1000             -x /data/home/000_index/022_snakePipes/BowtieIndex/genome -1 FASTQ_TrimGalore/ATACSeq_521_Rep1_raw_R1.fastq.gz -2 FASTQ_TrimGalore/ATACSeq_521_Rep1_raw_R2.fastq.gz              --fr             --rg-id ATACSeq_521_Rep1_raw             --rg DS:ATACSeq_521_Rep1_raw --rg PL:ILLUMINA --rg SM:ATACSeq_521_Rep1_raw             -p 24             2> Bowtie2/ATACSeq_521_Rep1_raw.Bowtie2_summary.txt |             samtools view -Sb - |             samtools sort -m 2G -T $MYTEMP/ATACSeq_521_Rep1_raw -@ 2 -O bam - > Bowtie2/ATACSeq_521_Rep1_raw.sorted.bam;
            rm -rf $MYTEMP
            

[Mon Dec  2 15:38:00 2019]
rule FastQC_on_trimmed:
    input: FASTQ_TrimGalore/ATACSeq_521_Rep1_raw_R1.fastq.gz
    output: FastQC_trimmed/ATACSeq_521_Rep1_raw_R1_fastqc.html
    log: FastQC_trimmed/logs/FastQC_trimmed.ATACSeq_521_Rep1_raw_R1.out, FastQC_trimmed/logs/FastQC_trimmed.ATACSeq_521_Rep1_raw_R1.err
    jobid: 29
    benchmark: FastQC_trimmed/.benchmark/FastQC_trimmed.ATACSeq_521_Rep1_raw_R1.benchmark
    wildcards: sample=ATACSeq_521_Rep1_raw_R, read=1
    threads: 2

            fastqc -o FastQC_trimmed "FASTQ_TrimGalore/ATACSeq_521_Rep1_raw_R1.fastq.gz" > FastQC_trimmed/logs/FastQC_trimmed.ATACSeq_521_Rep1_raw_R1.out 2> FastQC_trimmed/logs/FastQC_trimmed.ATACSeq_521_Rep1_raw_R1.err
            

[Mon Dec  2 15:38:00 2019]
rule FastQC_on_trimmed:
    input: FASTQ_TrimGalore/ATACSeq_521_Rep1_raw_R2.fastq.gz
    output: FastQC_trimmed/ATACSeq_521_Rep1_raw_R2_fastqc.html
    log: FastQC_trimmed/logs/FastQC_trimmed.ATACSeq_521_Rep1_raw_R2.out, FastQC_trimmed/logs/FastQC_trimmed.ATACSeq_521_Rep1_raw_R2.err
    jobid: 30
    benchmark: FastQC_trimmed/.benchmark/FastQC_trimmed.ATACSeq_521_Rep1_raw_R2.benchmark
    wildcards: sample=ATACSeq_521_Rep1_raw_R, read=2
    threads: 2

            fastqc -o FastQC_trimmed "FASTQ_TrimGalore/ATACSeq_521_Rep1_raw_R2.fastq.gz" > FastQC_trimmed/logs/FastQC_trimmed.ATACSeq_521_Rep1_raw_R2.out 2> FastQC_trimmed/logs/FastQC_trimmed.ATACSeq_521_Rep1_raw_R2.err
            
Activating conda environment: /data/software/anaconda2/envs/a0867dacba0b8e42decb9d4bf277ec1d
Activating conda environment: /data/software/anaconda2/envs/bf3707dd080135259f2ce93c9e91b45e
Activating conda environment: /data/software/anaconda2/envs/bf3707dd080135259f2ce93c9e91b45e
**mktemp: failed to create directory via template \u2018/data/extended//snakepipes.XXXXXXXXXX\u2019: No such file or directory**
[Mon Dec  2 15:38:03 2019]
Error in rule Bowtie2:
    jobid: 129
    output: Bowtie2/ATACSeq_521_Rep1_raw.Bowtie2_summary.txt, Bowtie2/ATACSeq_521_Rep1_raw.sorted.bam
    conda-env: /data/software/anaconda2/envs/a0867dacba0b8e42decb9d4bf277ec1d
    shell:
        
            MYTEMP=$(mktemp -d ${TMPDIR:-/tmp}/snakepipes.XXXXXXXXXX);
            bowtie2             -X 1000             -x /data/home/000_index/022_snakePipes/BowtieIndex/genome -1 FASTQ_TrimGalore/ATACSeq_521_Rep1_raw_R1.fastq.gz -2 FASTQ_TrimGalore/ATACSeq_521_Rep1_raw_R2.fastq.gz              --fr             --rg-id ATACSeq_521_Rep1_raw             --rg DS:ATACSeq_521_Rep1_raw --rg PL:ILLUMINA --rg SM:ATACSeq_521_Rep1_raw             -p 24             2> Bowtie2/ATACSeq_521_Rep1_raw.Bowtie2_summary.txt |             samtools view -Sb - |             samtools sort -m 2G -T $MYTEMP/ATACSeq_521_Rep1_raw -@ 2 -O bam - > Bowtie2/ATACSeq_521_Rep1_raw.sorted.bam;
            rm -rf $MYTEMP
            
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

**Job failed, going on with independent jobs.**
[Mon Dec  2 15:41:51 2019]
Finished job 30.
50 of 184 steps (27%) done
[Mon Dec  2 15:41:59 2019]
Finished job 29.
51 of 184 steps (28%) done
[Mon Dec  2 15:49:03 2019]
Finished job 21.
52 of 184 steps (28%) done

[Mon Dec  2 15:49:03 2019]
rule FastQC_on_trimmed:
    input: FASTQ_TrimGalore/ATACSeq_7_Rep1_raw_R2.fastq.gz
    output: FastQC_trimmed/ATACSeq_7_Rep1_raw_R2_fastqc.html
    log: FastQC_trimmed/logs/FastQC_trimmed.ATACSeq_7_Rep1_raw_R2.out, FastQC_trimmed/logs/FastQC_trimmed.ATACSeq_7_Rep1_raw_R2.err
    jobid: 34
    benchmark: FastQC_trimmed/.benchmark/FastQC_trimmed.ATACSeq_7_Rep1_raw_R2.benchmark
    wildcards: sample=ATACSeq_7_Rep1_raw_R, read=2
    threads: 2
.......

**Comment by dpryan79** [comment]
Please run `snakePipes config` and use the `--tempDir` option to specify the appropriate location on your cluster.

**Comment by zifeng9527** [comment]
It works well after changed the tempDir as your suggestion. 
great!
