### ISSUE TITLE
unable to install snakePipes on windows

### ISSUE THREAD

**Issue by oreiner** [maxplanck-ie/snakepipes#522]
Hi, 
I'm trying to install snakePipes on Windows 10 using git bash. Is there a way to do this or should I give it up?
I installed miniconda3 (version 4.7.12) and when trying to quick install 
conda create -n snakePipes -c mpi-ie -c bioconda -c conda-forge snakePipes
I get

> Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done

>  Found conflicts! Looking for incompatible packages.

>  This can take several minutes.  Press CTRL-C to abort.

> failed

>  UnsatisfiableError: The following specifications were found to be incompatible with each other:

>  Package graphviz conflicts for:

>  snakepipes -> graphviz

> Package wget conflicts for:
> snakepipes -> wget
> Package pandas conflicts for:
> snakepipes -> pandas
> Package python conflicts for:
> snakepipes -> python[version='>=3']
> Package fuzzywuzzy conflicts for:
> snakepipes -> fuzzywuzzy
> Package snakemake conflicts for:
> snakepipes -> snakemake[version='5.2.0.*|>=5.2.3|>=5.7']
> Package pyyaml conflicts for:
> snakepipes -> pyyaml[version='>=5.1']

this is my conda list

ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py37_0    conda-forge
openssl                   1.1.1d               hfa6e2cd_0    conda-forge
pip                       19.3.1                   py37_0    conda-forge
python                    3.7.3                h510b542_1    conda-forge
setuptools                42.0.2                   py37_0    conda-forge
sqlite                    3.30.1               hfa6e2cd_0    conda-forge
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_0
wheel                     0.33.6                   py37_0    conda-forge
wincertstore              0.2                   py37_1003    conda-forge

Thanks in advance!
Omer

**Comment by dpryan79** [comment]
Sorry, as with most bioinformatics programs, it's not possible to use snakePipes on Windows since very few of its dependencies work there. You may be able to get things working on the Linux subsystem of Windows 10, none of use have ever tried.

**Comment by oreiner** [comment]
okay, thanks for the info
