### ISSUE TITLE
The DEseq_basic_DEresults seem not reasonable

### ISSUE THREAD

**Issue by zifeng9527** [maxplanck-ie/snakepipes#524]
I perform the RNA-seq analysis using snakePipes. The conmmond line is:

**RNA-seq --local -i ./input_RNA-seq -o ./out_RNA-seq mm10 --reads '_R1' '_R2' --trim --fastqc --plotFormat pdf -j 48 --local --sampleSheet sampleSheet.tsv --dnaContam --DAG  --featureCountsOptions '-p -B'** 

**In the final "DEseq_basic_DEresults.tsv" file, I sort the data accoring to the padj. The Mapk12 gene ranks #192, of which the p value is 0.213, the padj is 0.9999.** 

  |   | baseMean | log2FoldChange | lfcSE | stat | pvalue | padj | Status | external_gene_name
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | ENSMUSG00000054753.9 | 3.127632 | -20.3046 | 2.343052 | -8.66587 | 4.48E-18 | 1.00E-13 | DOWN | AU018091
2 | ENSMUSG00000020364.14 | 6.321696 | -21.738 | 2.654708 | -8.18847 | 2.65E-16 | 2.95E-12 | DOWN | Zfp354a |  
3 | ENSMUSG00000054612.4 | 14.6991 | 21.90804 | 2.866094 | 7.643866 | 2.11E-14 | 1.57E-10 | UP | Mgmt |  
........
191 | ENSMUSG00000042808.8 | 40.03671 | -3.59329 | 2.892854 | -1.24213 | 0.21419 | 0.999989 | None | Gpx2
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
192 | ENSMUSG00000022610.9 | 286.2224 | -3.58877 | 2.886407 | -1.24333 | 0.213744 | 0.999989 | None | Mapk12

**However, Mapk12 is the gene which we knockout. The p value and padj is not reasonable. Then I check the bam file and the DEseq_basic_counts_DESeq2.normalized.tsv. These file seems ok.**

  |   | RNASeq_244_Rep1 | RNASeq_244_Rep2 | RNASeq_521_Rep1 | RNASeq_521_Rep2 | s244.jing1 | s244.jing2 | s521.jing1 | s521.jing2 | RNASeq_7_Rep1 | RNASeq_7_Rep2 | RNASeq_8_Rep1 | RNASeq_8_Rep2 | s812.jing1 | s812.jing2 | s8.jing1 | s8.jing2 |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | ENSMUSG00000054753.9 | 20.34306 | 11.13097 | 0 | 1.068763 | 1.02974 | 0 | 15.63785 | 12.47583 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | AU018091
2 | ENSMUSG00000020364.14 | 0 | 0 | 36.95147 | 41.68175 | 0 | 0 | 20.85047 | 21.62477 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | Zfp354a
3 | ENSMUSG00000054612.4 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 93.53811 | 90.53511 | 0 | 1.851017 | 44.88524 | 70.89246 | Mgmt
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
191 | ENSMUSG00000042808.8 | 0 | 0 | 115.7813 | 149.6268 | 9.267662 | 7.340262 | 292.9491 | 332.6888 | 9.169454 | 9.684843 | 0 | 1.191251 | 3.906866 | 0.925509 | 7.480874 | 5.251293 | Gpx2
192 | ENSMUSG00000022610.9 | 616.2752 | 593.2808 | 607.2358 | 616.6762 | 446.9073 | 463.4851 | 605.7061 | 645.4162 | 10.83663 | 19.36969 | 19.643 | 9.530012 | 4.883583 | 4.627543 | 4.156041 | 12.25302 | Mapk12

**My sampleSheet.tsv is**
name    condition
RNASeq_244_Rep1 Ctrl
RNASeq_244_Rep2 Ctrl
RNASeq_521_Rep1 Ctrl
RNASeq_521_Rep2 Ctrl
RNASeq_7_Rep1   KO
RNASeq_7_Rep2   KO
RNASeq_8_Rep1   KO
RNASeq_8_Rep2   KO
s244.jing1      Ctrl
s244.jing2      Ctrl
s521.jing1      Ctrl
s521.jing2      Ctrl
s812.jing1      KO
s812.jing2      KO
s8.jing1        KO
s8.jing2        KO

**Apparently, Mapk12 significantly down regulate in my KO sample. I think there should be some problem when runing the DEseq2.  But it seems there is no Arguments to optimize DEseq2.**

Anybody can help me?

**Comment by katsikora** [comment]
What does your PCA/MDS plot look like? Or the whole DESeq2 stats report for that matter?

**Comment by zifeng9527** [comment]
Here is the plotPCA
#plotPCA --outFileNameData
Component	RNASeq_244_Rep1	RNASeq_244_Rep2	RNASeq_521_Rep1	RNASeq_521_Rep2	RNASeq_7_Rep1	RNASeq_7_Rep2	RNASeq_8_Rep1	RNASeq_8_Rep2	s244-jing1	s244-jing2	s521-jing1	s521-jing2	s8-jing1	s8-jing2	s812-jing1	s812-jing2	Eigenvalue
1	-2.835569358905425	-5.198287984604832	11.565485279289058	8.167636558921203	16.374814470767006	20.108052149547085	43.07052639807388	30.788269038461753	-21.545396671586	-22.55469533894548	-10.25975660997335	-9.91555465496289	-18.77780167689874	-15.970351204280323	-10.584740384882174	-12.43263001002077	5761.753653823476
2	-24.09412507079486	-25.467448834466527	-8.110002215316275	-8.19528695353555	-0.06453542691179967	1.8643547434168841	8.397019238214288	3.305537104006535	-11.9304538798261	-8.537093851806173	3.482208513466321	3.357069639908656	13.069843881664454	14.743366829272908	19.00801398487288	19.171532297834382	2802.6224930713083
3	6.698275188438243	8.05685257602366	3.7840049207117987	4.414058670583582	4.9013229104718	3.2013230504490875	-11.341688327086276	-8.913421066998243	-31.155536433784135	-5.875155625517734	14.77706764297448	12.103882754664252	-0.13614805630954252	-11.673026617408576	9.17342467576358	1.9847637370240299	1980.3564799338621
4	11.196514522232413	12.580815483823674	-2.048053290200167	-0.9225227229639563	2.1220120019973288	0.8235464541301376	-4.339171582314316	-0.31701769650978895	-5.151229927418728	-10.628353285629599	-18.387625250664854	-17.896999250853245	4.383435711369295	6.701822658781976	9.902729677548813	11.980096496671017	1416.4146106727005
5	-1.8983215181790574	-2.5307490543074644	-2.1526865124514383	-3.7838161853057986	4.525119935669993	4.883450233877256	-0.07012639408202093	-2.951404105270612	6.741269441177775	9.02879075779181	-2.227864013758838	-2.0238461406596433	-14.863450699965313	-15.941765288861284	11.022997037058271	12.242402507266364	964.4681775858099
6	-7.596182787276559	-7.16217563702827	10.018121107209181	10.20099539586977	11.326100342326049	12.280470191787748	-10.902290252893938	-9.179770534316363	3.264455194197208	-2.1611256135566084	-4.1963647832801145	-4.1798733577215215	0.7521053606301756	3.3427530765186546	-3.1147242023776425	-2.6924935000877634	874.7390663178905
7	-0.7589256228063631	-1.478132986031286	10.512205468277376	9.408126195158856	-8.637593473742688	-9.092618072547092	-0.6865984866091375	0.6279244415596447	5.1640520469115865	-11.385022526782567	1.3585184232551177	3.3021515716266907	-6.717456545744754	-0.5630909128574445	1.8991366933433962	7.047323786988676	627.6783138992848
8	1.910904895647313	1.7718786819364059	-6.4428147699052305	-4.280970790496239	3.7098585406885167	4.5267538528948	-1.0979397843826386	-1.3507797749901278	6.287779692732698	-10.805687222535827	3.982331458458618	4.074083079763342	-1.542458973802163	0.2974560281401843	-1.5837458033408933	0.5433508891912473	297.9396205937536
9	-2.0055131687503267	0.44815202745012894	-1.2687363682196229	0.8530100063144446	2.0229893917621973	-1.429595461420792	-5.405067505649916	7.375069858069508	0.21816542136298822	-0.025603826854470713	-0.23826136150869545	0.3414695173743233	0.8374993259990792	-1.731740789278072	-0.5742745480623281	0.5824374814115529	100.89385834050493
10	0.8438944552814471	-0.30695529040877734	-0.2009648971167188	-0.6404517517396859	0.059830608560978216	0.7752899211304225	-0.7207821507419311	0.4218688797543624	-1.8893777938589529	1.40017360236223	1.3640469721520887e-06	0.8347186531444034	-3.2690965715691505	3.1831597555178024	-4.150485452727933	3.6591766683645295	60.221690763796104
11	-1.946190450349339	1.8300321841810891	-3.555278503918002	3.9422257219578274	-0.46637863940861	0.13605171251462678	0.7203720631816998	-0.5655838262243826	-0.21910701610720584	0.3899499184995735	0.8661453072190294	-0.9172041201530374	-1.2214224118549826	0.8510309726112797	0.3546974681730381	-0.1993403803226051	40.56587724550034
12	-0.23497022733730755	0.3195146962104014	0.49133717760192813	-0.9185621969645368	2.4003371694207996	-2.1272000120617447	-0.14183684971834898	0.059053440358681486	-0.1442656898582113	0.10170090446852242	-0.0213836809602633	0.35235468823178523	-2.5167913211166244	2.3347105359318947	1.9657131544681063	-1.9197117886750923	31.04287294882702
13	1.4132741499248715	-1.3016657262761253	-0.26431700338723935	0.17808833755645626	-1.9765545549200696	1.8525654693674025	-1.0440820359249563	1.098886448348131	-0.04572891760554387	0.0863776534753703	0.5198835452601243	-0.483721820110545	-1.0584489071754573	0.8640175117266966	1.366277108274189	-1.2048512585333038	19.128719845296423
14	-1.6757620489233396	1.7464644728321734	0.6576977425913044	-0.8105090759145388	-1.164891486615568	1.1756686729227124	-0.15781742198681115	0.13255631777635313	-0.06396517277173652	0.021499425219990792	-1.1973398832208788	1.3378164716098055	-0.3051322954305979	0.28593231295612154	0.3442562291377485	-0.3264742601827407	13.357344677816114
15	-0.8046979569096813	0.7925338984045831	0.8059915487320275	-0.840042455227202	-0.21621125269698793	0.17442308315004418	-0.09242447928168662	0.14177185222344102	0.08190908809789649	-0.07780333469739337	1.7414863333746597	-1.71945439300984	-0.11182548451905383	0.11542805277204382	-0.15761738835611044	0.1665328879432615	8.81722028017653
16	7.629313847345998e-15	7.840950111415168e-15	1.1046719095020308e-14	1.0325074129013956e-14	6.716849298982197e-15	4.6074255521944e-15	1.965094753586527e-14	1.3322676295501878e-14	1.4099832412739488e-14	1.0769163338864018e-14	1.0047518372857667e-14	1.0269562977782698e-14	9.658940314238862e-15	5.6343818499726694e-15	8.326672684688674e-15	3.608224830031759e-15	2.054678658950863e-27

**Comment by zifeng9527** [comment]
Here is correlation.spearman.bed_coverage

#plotCorrelation --outFileCorMatrix
	's812-jing1'	's812-jing2'	'RNASeq_7_Rep1'	'RNASeq_7_Rep2'	'RNASeq_8_Rep1'	'RNASeq_8_Rep2'	's8-jing1'	's8-jing2'	'RNASeq_521_Rep1'	'RNASeq_521_Rep2'	's521-jing1'	's521-jing2'	'RNASeq_244_Rep1'	'RNASeq_244_Rep2'	's244-jing1'	's244-jing2'
's812-jing1'	1.0000	0.9798	0.9611	0.9599	0.9513	0.9528	0.9588	0.9565	0.9521	0.9529	0.9568	0.9561	0.9555	0.9561	0.9433	0.9538
's812-jing2'	0.9798	1.0000	0.9610	0.9604	0.9525	0.9534	0.9574	0.9572	0.9527	0.9534	0.9556	0.9553	0.9540	0.9544	0.9458	0.9516
'RNASeq_7_Rep1'	0.9611	0.9610	1.0000	0.9833	0.9622	0.9629	0.9596	0.9601	0.9671	0.9680	0.9613	0.9605	0.9622	0.9618	0.9538	0.9578
'RNASeq_7_Rep2'	0.9599	0.9604	0.9833	1.0000	0.9628	0.9624	0.9585	0.9597	0.9671	0.9677	0.9605	0.9595	0.9613	0.9597	0.9543	0.9565
'RNASeq_8_Rep1'	0.9513	0.9525	0.9622	0.9628	1.0000	0.9796	0.9609	0.9634	0.9579	0.9584	0.9489	0.9484	0.9578	0.9566	0.9499	0.9498
'RNASeq_8_Rep2'	0.9528	0.9534	0.9629	0.9624	0.9796	1.0000	0.9626	0.9640	0.9585	0.9591	0.9495	0.9488	0.9604	0.9588	0.9499	0.9507
's8-jing1'	0.9588	0.9574	0.9596	0.9585	0.9609	0.9626	1.0000	0.9792	0.9578	0.9589	0.9611	0.9615	0.9543	0.9550	0.9555	0.9628
's8-jing2'	0.9565	0.9572	0.9601	0.9597	0.9634	0.9640	0.9792	1.0000	0.9605	0.9608	0.9590	0.9602	0.9518	0.9514	0.9609	0.9609
'RNASeq_521_Rep1'	0.9521	0.9527	0.9671	0.9671	0.9579	0.9585	0.9578	0.9605	1.0000	0.9826	0.9728	0.9733	0.9556	0.9544	0.9543	0.9551
'RNASeq_521_Rep2'	0.9529	0.9534	0.9680	0.9677	0.9584	0.9591	0.9589	0.9608	0.9826	1.0000	0.9737	0.9736	0.9568	0.9556	0.9549	0.9555
's521-jing1'	0.9568	0.9556	0.9613	0.9605	0.9489	0.9495	0.9611	0.9590	0.9728	0.9737	1.0000	0.9810	0.9542	0.9544	0.9526	0.9602
's521-jing2'	0.9561	0.9553	0.9605	0.9595	0.9484	0.9488	0.9615	0.9602	0.9733	0.9736	0.9810	1.0000	0.9525	0.9533	0.9525	0.9602
'RNASeq_244_Rep1'	0.9555	0.9540	0.9622	0.9613	0.9578	0.9604	0.9543	0.9518	0.9556	0.9568	0.9542	0.9525	1.0000	0.9812	0.9540	0.9634
'RNASeq_244_Rep2'	0.9561	0.9544	0.9618	0.9597	0.9566	0.9588	0.9550	0.9514	0.9544	0.9556	0.9544	0.9533	0.9812	1.0000	0.9536	0.9640
's244-jing1'	0.9433	0.9458	0.9538	0.9543	0.9499	0.9499	0.9555	0.9609	0.9543	0.9549	0.9526	0.9525	0.9540	0.9536	1.0000	0.9720
's244-jing2'	0.9538	0.9516	0.9578	0.9565	0.9498	0.9507	0.9628	0.9609	0.9551	0.9555	0.9602	0.9602	0.9634	0.9640	0.9720	1.0000

**Comment by zifeng9527** [comment]
The DESeq2.err file:
estimating size factors
estimating dispersions
gene-wise dispersion estimates
mean-dispersion relationship
final dispersion estimates
fitting model and testing
-- replacing outliers and refitting for 29245 genes
-- DESeq argument 'minReplicatesForReplace' = 7 
-- original counts are preserved in counts(dds)
estimating dispersions
fitting model and testing
Writing 8 Bibtex entries ... OK
Results written to file ‘citations.bib’


processing file: DESeq2_report_basic.Rmd
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
output file: DESeq2_report_basic.knit.md

[WARNING] This document format requires a nonempty <title> element.
  Please specify either 'title' or 'pagetitle' in the metadata,
  e.g. by using --metadata pagetitle="..." on the command line.
  Falling back to 'DESeq2_report_basic.utf8'

Output created: DESeq2_report_basic.html
Warning messages:
1: Transformation introduced infinite values in continuous x-axis 
2: Transformation introduced infinite values in continuous x-axis 
3: Removed 527914 rows containing non-finite values (stat_density). 
4: Removed 27435 rows containing non-finite values (stat_density). 
5: Removed 31505 rows containing missing values (geom_point). 
6: Removed 16 rows containing missing values (geom_point). 
7: Removed 24126 rows containing non-finite values (stat_bin). 
8: Removed 31070 rows containing non-finite values (stat_bin).

**Comment by katsikora** [comment]
Can you post screenshots of your MDS plot, MA plot and dispersion fitting from your DESeq2_report_basic.hml like the example ones below?

![image](https://user-images.githubusercontent.com/7079932/70422406-fdcb3f80-1a6b-11ea-8875-b8b15dadc9c2.png)
![image](https://user-images.githubusercontent.com/7079932/70422445-0d4a8880-1a6c-11ea-8011-12e9ef04a2c4.png)
![image](https://user-images.githubusercontent.com/7079932/70422501-218e8580-1a6c-11ea-88fb-6bf64df0bc6d.png)

**Comment by zifeng9527** [comment]
Thanks for your replay. Here is the plot:

![image](https://user-images.githubusercontent.com/12741752/70423028-b8c4fe80-1aa7-11ea-8769-f7e6f486cdab.png)
![image](https://user-images.githubusercontent.com/12741752/70423069-c5e1ed80-1aa7-11ea-946d-1792dc06a2d9.png)
![image](https://user-images.githubusercontent.com/12741752/70423100-cf6b5580-1aa7-11ea-9bef-92f5e17e6de3.png)

**Comment by katsikora** [comment]
Ye gods, it looks horrible. Dispersion fitting definitely went wrong.

It looks like two of your samples are screwing up the analysis, see PCA plot.

My advice is to remove the two samples RNASeq_521_Rep2 and RNASeq_8_Rep2  e.g. by deleting them from the sample sheet and repeat the analysis. If you rename the sample sheet, you can just rerun the workflow on the same output folder and a new DESeq2 results folder will be generated (i.e. you only have to rerun the DESeq2 step, not the whole workflow).

Good luck!

**Comment by zifeng9527** [comment]
OK, I will try and feedback later. Thanks for your advise.

**Comment by zifeng9527** [comment]
It finished. 

**The result seems still abnormal.  The padj of Mapk12 is 0.999997.**

  | baseMean | log2FoldChange | lfcSE | stat | pvalue | padj | Status | external_gene_name
-- | -- | -- | -- | -- | -- | -- | -- | --
ENSMUSG00000022610.9 | 294.4758 | -5.71211 | 2.889708 | -1.97671 | 0.048075 | 0.999997 | None | Mapk12 |  

**The count table seems OK:**

  | RNASeq_244_Rep1 | RNASeq_244_Rep2 | RNASeq_521_Rep1 | s244.jing1 | s244.jing2 | s521.jing1 | s521.jing2 | RNASeq_7_Rep1 | RNASeq_7_Rep2 | RNASeq_8_Rep1 | s812.jing1 | s812.jing2 | s8.jing1 | s8.jing2
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ENSMUSG00000022610.9 | 626.0967 | 604.2563 | 618.2222 | 454.1967 | 470.9113 | 616.2594 | 655.5521 | 11.04659 | 19.70032 | 20.04571 | 4.970517 | 4.711308 | 4.225981 | 12.46614

The relevant plot:
![image](https://user-images.githubusercontent.com/12741752/70428972-a00e1600-1ab2-11ea-9125-6cf5dc165fd1.png)

![image](https://user-images.githubusercontent.com/12741752/70429151-fb400880-1ab2-11ea-98cc-141c8a83bd97.png)

![image](https://user-images.githubusercontent.com/12741752/70429170-08f58e00-1ab3-11ea-97a2-a6fe9b4754f3.png)

![image](https://user-images.githubusercontent.com/12741752/70429184-0f840580-1ab3-11ea-9f0c-c2d205b16e02.png)


**The bigwig plot of mapk12 locus:**
![image](https://user-images.githubusercontent.com/12741752/70429456-86b99980-1ab3-11ea-89d7-2842702d2b04.png)

![image](https://user-images.githubusercontent.com/12741752/70429500-a355d180-1ab3-11ea-978d-095cc6183c2c.png)

**Comment by zifeng9527** [comment]
According to the bamCoverage plot, there is a abnormal mapping site on chr18 of sample 244:
![image](https://user-images.githubusercontent.com/12741752/70429876-84a40a80-1ab4-11ea-9821-43082df6ce6d.png)
Note: the vertical axis is 80000

Here is the gapdh mapping result:
![image](https://user-images.githubusercontent.com/12741752/70429976-bae18a00-1ab4-11ea-9531-109f807d9dc1.png)
Note: the vertical axis is 5000

whether sample 244 also should be removed?

**Comment by dpryan79** [comment]
There's nothing indicating any issue with samples 244 (I assume you have two of them and these aren't technical replicates). DESeq2 isn't giving mapk12 a significant p-value because the WT levels vary by about 50%, making the fit itself highly variable.

Anyway, this isn't a snakePipes issue, it just that the data is noisy, which happens.

**Comment by dpryan79** [comment]
BTW, the region on chr8 is an ERV that seems to be expressed in some of your samples. Usually these are removed by poly-A enrichment during library prep.

**Comment by zifeng9527** [comment]
Thanks for your advise. I checked this site, it's a MuLV-int.  
I also checked our ATAC-seq data, this site is totally accessible in sample 244. I guess it's a real status in smaple 244. 

![image](https://user-images.githubusercontent.com/12741752/70488030-4e0cd500-1b32-11ea-860c-c7b82b0451f7.png)
