### ISSUE TITLE
Premade index mm10 is actual human

### ISSUE THREAD

**Issue by ii-bioinfo-thomas** [maxplanck-ie/snakepipes#528]
The premade index downloadable through the docs is not mouse but human

Mouse (GRCm38/mm10, Gencode release m19)
https://zenodo.org/record/2650854

Actually already on the download site it says release29 which only exists for human.

head of genome.fa.fai shows the chromosome sizes of hs:

```
chr1    248956422       8       60      61
chr2    242193529       253105712       60      61
chr3    198295559       499335808       60      61
chr4    190214555       700936301       60      61
chr5    181538259       894321107       60      61
chr6    170805979       1078885012      60      61
chr7    159345973       1252537766      60      61
chr8    145138636       1414539514      60      61
chr9    138394717       1562097136      60      61
chr10   133797422       1702798442      60      61
```

Mouse GRCm38 are shorter:
`1       195471971       56      60      61`

Best regards,
Thomas

**Comment by dpryan79** [comment]
Gah, sorry about that, I'll fix that on Monday.

**Comment by dpryan79** [comment]
This fell off my radar, but I've now fixed it in this record: https://zenodo.org/record/3629114

I'll update the webpage to link to that.
