### ISSUE TITLE
/bin/bash: bamCoverage: command not found when running DNA-mapping

### ISSUE THREAD

**Issue by brennerUT** [maxplanck-ie/snakepipes#530]
I tried running the DNA-mapping pipeline, but I got an error at the bamCoverage part. In the .err files in the bamCoverage/logs/  directory within the output directory, it says: 

/bin/bash: bamCoverage: command not found

I can run $bamCoverage --help without any issues, and if I run $which bamCoverage , it says it's here:

~/anaconda3/envs/snakePipes/bin/bamCoverage

Any idea how to fix this?

Thanks

-Eric

**Comment by katsikora** [comment]
Hi Brenner,

did you append --snakemakeOptions '  --use-conda --conda-prefix ~/anaconda3/envs/  ' to your command or modify the corresponding line in the defaults.yaml ? 

Best,

Katarzyna

**Comment by brennerUT** [comment]
Yep! My default.yaml files looks correct as far as I can tell. Here's what's in it: 

clusterConfig: shared/cluster.yaml
emailSender: null
onlySSL: false
organismsDir: shared/organisms
smtpPassword: null
smtpPort: 0
smtpServer: null
smtpUsername: null
snakemakeOptions: ' --use-conda --conda-prefix /stor/home/ericb123/anaconda3/envs '
tempDir: /stor/scratch/Brock/temp

**Comment by dpryan79** [comment]
It seems that for some reason the environment for this step wasn't created properly. I suggest running `snakePipes envInfo` and looking for the location associated with `shared.yaml`. Delete that directory and rerun `snakePipes createEnvs` and the environment should be properly recreated.
