### ISSUE TITLE
Bulk RNA-seq analysis using snakePipes and RNAcocktail, totally different output

### ISSUE THREAD

**Issue by zifeng9527** [maxplanck-ie/snakepipes#533]
Several days ago, I feedback an issues about DEseq #524.  dpryan79 told me that my data is noisy.

In fact, before meeting with snakePipes, I used RNAcocktail (https://bioinform.github.io/rnacocktail/) all the while. So I re-analyzed these data using RNAcocktail and snakePipes to make a comparison. 

The conclusion is that RNAcocktail output a reasonable result, whereas snakePipes output a strange result. 

I have 16 samples,  the information is:

Mouse   NO. | sample name | condition | Sequencing batch | other info.
-- | -- | -- | -- | --
#M244 | RNASeq_244_Rep1 | Ctrl | Batch2 | Female/ with a strong activate MuLV-int at chr8
#M244 | RNASeq_244_Rep2 | Ctrl | Batch2 | Female/ with a strong activate MuLV-int at chr8
#M244 | s244.jing1 | Ctrl | Batch1 | Female/ with a strong activate MuLV-int at chr8
#M244 | s244.jing2 | Ctrl | Batch1 | Female/ with a strong activate MuLV-int at chr8
#M521 | RNASeq_521_Rep1 | Ctrl | Batch2 | Female
#M521 | RNASeq_521_Rep2 | Ctrl | Batch2 | Female
#M521 | s521.jing1 | Ctrl | Batch1 | Female
#M521 | s521.jing2 | Ctrl | Batch1 | Female
#M7 | RNASeq_7_Rep1 | KO | Batch2 | Female
#M7 | RNASeq_7_Rep2 | KO | Batch2 | Female
#M8 | RNASeq_8_Rep1 | KO | Batch2 | Male
#M8 | RNASeq_8_Rep2 | KO | Batch2 | Male
#M8 | s8.jing1 | KO | Batch1 | Male
#M8 | s8.jing2 | KO | Batch1 | Male
#M812 | s812.jing1 | KO | Batch1 | Male
#M812 | s812.jing2 | KO | Batch1 | Male

**1. PCA analysis**
1) using RNAcocktail, the pipline generates bam files, then I use multiBamSummary and plotPCA to perform PCA analysis
with all chromsomes
![image](https://user-images.githubusercontent.com/12741752/71301178-0fe79f00-23d7-11ea-85d4-14f3622679f4.png)

exclude sex chromsomes
![image](https://user-images.githubusercontent.com/12741752/71301199-3d344d00-23d7-11ea-93f2-45c629f7eed7.png)

2) using snakePipes
![image](https://user-images.githubusercontent.com/12741752/71302836-1253f400-23eb-11ea-96db-2f19436f0738.png)

![image](https://user-images.githubusercontent.com/12741752/71302860-5c3cda00-23eb-11ea-8207-709c2321a9d1.png)

![image](https://user-images.githubusercontent.com/12741752/71302862-63fc7e80-23eb-11ea-95b9-1acdaf6897bc.png)

**2. DEG datafile** (ranked with padj)
1) using RNAcocktail

gene_id | baseMean | log2FoldChange | lfcSE | stat | pvalue | padj | transcript_id | ref_gene_id | gene_name
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
ENSMUSG00000084349.3 | 18749.22 | 11.43876 | 0.293705 | 38.94644 | 0 | 0 | ENSMUST00000120557.1 | NA | Rpl3-ps1
ENSMUSG00000021908.10 | 1092.492 | 8.410164 | 0.395961 | 21.23986 | 4.09E-100 | 3.67E-96 | ENSMUST00000022467.10 | NA | Gm6768
ENSMUSG00000022610.9 | 595.492 | -5.96227 | 0.288688 | -20.653 | 9.18E-95 | 5.49E-91 | ENSMUST00000088827.6 | NA | Mapk12
ENSMUSG00000003849.8 | 384.9707 | -4.98685 | 0.311335 | -16.0176 | 9.62E-58 | 4.32E-54 | ENSMUST00000003947.8 | NA | Nqo1
ENSMUSG00000025081.13 | 18.35192 | -4.93931 | 0.466231 | -10.5941 | 3.17E-26 | 1.14E-22 | ENSMUST00000111606.7\|ENSMUST00000078723.10\|ENSMUST00000121249.7\|ENSMUST00000111604.1 | NA | Tdrd1
ENSMUSG00000035385.5 | 228.2971 | 4.295384 | 0.443204 | 9.691665 | 3.27E-22 | 9.79E-19 | ENSMUST00000000193.5\|ENSMUST00000124479.1 | NA | Ccl2
ENSMUSG00000037664.13 | 26.9553 | 4.498897 | 0.475553 | 9.460354 | 3.07E-21 | 7.87E-18 | ENSMUST00000167912.8\|ENSMUST00000037287.7\|ENSMUST00000208118.1\|ENSMUST00000207910.1\|ENSMUST00000208137.1 | NA | Cdkn1c
ENSMUSG00000015599.9 | 47.92813 | -2.95532 | 0.31463 | -9.39303 | 5.83E-21 | 1.31E-17 | ENSMUST00000047034.8\|ENSMUST00000225808.1\|ENSMUST00000223818.1 | NA | Ttbk1
ENSMUSG00000078954.9 | 434.5072 | 2.021999 | 0.215554 | 9.380477 | 6.57E-21 | 1.31E-17 | ENSMUST00000172307.8\|ENSMUST00000006029.10\|ENSMUST00000167499.7\|ENSMUST00000168811.1\|ENSMUST00000163312.7\|ENSMUST00000100464.3\|ENSMUST00000169075.1 | NA | Arhgap8
ENSMUSG00000105243.1 | 10.87856 | 4.520645 | 0.483876 | 9.34256 | 9.40E-21 | 1.69E-17 | ENSMUST00000198123.1 | NA | Gm43444
ENSMUSG00000030748.9 | 6786.53 | 1.116352 | 0.127185 | 8.777383 | 1.67E-18 | 2.73E-15 | ENSMUST00000033004.7\|ENSMUST00000206217.1\|ENSMUST00000206681.1\|ENSMUST00000205985.1\|ENSMUST00000206846.1 | NA | Il4ra
ENSMUSG00000052392.5 | 61.62974 | -2.06085 | 0.240299 | -8.57622 | 9.80E-18 | 1.36E-14 | ENSMUST00000021652.4\|ENSMUST00000128162.1\|ENSMUST00000221860.1 | NA | Acot4
ENSMUSG00000034330.10 | 785.1478 | -2.25291 | 0.263974 | -8.53459 | 1.41E-17 | 1.80E-14 | ENSMUST00000081232.8 | NA | Plcg2
ENSMUSG00000061740.7 | 35.13392 | -3.99077 | 0.486671 | -8.20014 | 2.40E-16 | 2.69E-13 | ENSMUST00000023083.7 | NA | Cyp2d22
ENSMUSG00000032491.14 | 146.5485 | -2.40677 | 0.299793 | -8.02812 | 9.90E-16 | 1.05E-12 | ENSMUST00000035069.13\|ENSMUST00000196735.1\|ENSMUST00000196876.1\|ENSMUST00000197894.1 | NA | Nradd
ENSMUSG00000073197.9 | 23.0708 | -2.97675 | 0.37485 | -7.94117 | 2.00E-15 | 2.00E-12 | ENSMUST00000177778.8\|ENSMUST00000063216.5 | NA | 5730507C01Rik
ENSMUSG00000020614.13 | 209.1067 | -2.63257 | 0.333779 | -7.88716 | 3.09E-15 | 2.92E-12 | ENSMUST00000155559.7\|ENSMUST00000020938.7\|ENSMUST00000146408.7\|ENSMUST00000144972.1 | NA | Fam20a
ENSMUSG00000020121.15 | 935.6161 | -1.16018 | 0.147873 | -7.8458 | 4.30E-15 | 3.86E-12 | ENSMUST00000020322.11\|ENSMUST00000081688.12\|ENSMUST00000161996.1\|ENSMUST00000161156.1\|ENSMUST00000162710.1 | NA | Srgap1
ENSMUSG00000029348.11 | 7.17663 | -3.83562 | 0.489529 | -7.83532 | 4.68E-15 | 4.00E-12 | ENSMUST00000031291.8\|ENSMUST00000198357.1\|ENSMUST00000200227.1\|ENSMUST00000196256.1\|ENSMUST00000199906.1\|ENSMUST00000197585.4\|ENSMUST00000199095.1 | NA | Asphd2

mapk12, which gene we ko, is ranked top4 with padj 5.49E-91

2) using snakePipes

baseMean | log2FoldChange | lfcSE | stat | pvalue | padj | Status | external_gene_name
-- | -- | -- | -- | -- | -- | -- | --
ENSMUSG00000074065.4 | 0.639017 | -18.2669 | 1.333619 | -13.6972 | 1.05E-42 | 3.04E-38 | DOWN | Gm10617
ENSMUSG00000104704.1 | 0.463286 | -18.2059 | 1.3668 | -13.3201 | 1.77E-40 | 2.55E-36 | DOWN | Gm43133
ENSMUSG00000055312.2 | 0.518386 | -18.365 | 1.387381 | -13.2372 | 5.35E-40 | 5.14E-36 | DOWN | Them7
ENSMUSG00000099773.1 | 0.602114 | -18.3708 | 1.416185 | -12.972 | 1.76E-38 | 2.74E-35 | DOWN | Hmgb1-rs16
........ |   |   |   |   |   |   |   |  
ENSMUSG00000022610.9 | 326.4753 | -2.89477 | 2.885986 | -1.00304 | 0.315839 | 0.999987 | None | Mapk12

mapk12 is ranked 6894 with padj 0.999987

3) DEG overlap using these two pipeline
extract DEG according |LFC| >=1  padj<0.01

![image](https://user-images.githubusercontent.com/12741752/71302991-68c23200-23ed-11ea-8637-e9fc6832674a.png)

it looks horrible!

**Comment by LeilyR** [comment]
which aligner did you use and how did you filter your reads for both pipelines?

**Comment by zifeng9527** [comment]
Thanks for your replay.

**For RNAcocktail**
Before run the RNAcocktail or snakePipes, i trimed the raw data using trim galore
trim_galore -q 20 --phred33 --stringency 3 --length 20 -e 0.1 --paired R1.fastq.gz 2.fastq.gz

Then I run RNAcocktail (https://bioinform.github.io/rnacocktail/)using HISAT2-StringTie-DESeq2 and Salmon-SMEM-DESeq2, respectively. These two process give similar results. Here I just show Salmon-SMEM-DESeq2 result.
run_rnacocktail.py quantify --quantifier_idx  mm10vM16tran_fmd_idx --1R1.fq.gz --2 R2.fq.gz --libtype IU --salmon_k 19  --salmon salmon --threads 72 --sample x --unzip
run_rnacocktail.py diff --quant_files xx --sample xx --ref_gtf  mm10vM16.gtf  

**For snakePipes**
Before run the RNAcocktail or snakePipes, i trimed the raw data using trim galore
trim_galore -q 20 --phred33 --stringency 3 --length 20 -e 0.1 --paired R1.fastq.gz 2.fastq.gz

Then I run snakePipes 
RNA-seq --local -i ./input_RNA-seq -o ./out_RNA-seq mm10 --reads '_R1' '_R2' --trim --fastqc --plotFormat pdf -j 48 --local --sampleSheet sampleSheet.tsv --dnaContam --DAG --featureCountsOptions '-p -B' 

During the snakePipes proecss， I using the default parameters to trim the data again. But I don't think this treatment should genereate the so huge difference.

**Comment by LeilyR** [comment]
If you have used snakepipes default, then it used STAR to map the reads, this is already making your comparison biased, since neither HISAT2 nor salmon have been used there. If you want to use Salmon you can choose a different mode for snakepipes (alignment free mode), and then be careful to set the same parameters for them. I see that for RNACocktail you have set -k to 19 , be aware that the default of snakepipes is 31. 
Also, snakepipes default tool to trim raw reads is `cutadapt`. I cannot confirm that the difference you see is coming from that, but it doesn't seem to make sense to cut your reads twice with two different tools.

**Comment by zifeng9527** [comment]
Thanks. 

In the defaults.yaml and RNA-seq files, I have changed the aligner from STAR to HISAT2. Here I will change -k from 31 to 19 to run it again.

**RNA-seq --local -i ./input_RNA-seq -o ./out_RNA-seq mm10 --reads '_R1' '_R2' --fastqc --plotFormat pdf -j 48 --local --sampleSheet sampleSheet.tsv --dnaContam --DAG --featureCountsOptions '-p -B'**  


################################################################################
# This file is the default configuration of the RNA-seq workflow!
#
# In order to adjust some parameters, please either use the wrapper script
# (eg. /path/to/snakemake_workflows/workflows/RNA-seq/RNA-seq)
# or save a copy of this file, modify necessary parameters and then provide
# this file to the wrapper or snakmake via '--configFile' option
# (see below how to call the snakefile directly)
#
# Own parameters will be loaded during snakefile executiuon as well and hence
# can be used in new/extended snakemake rules!
################################################################################
## General/Snakemake parameters, only used/set by wrapper or in Snakemake cmdl, but not in Snakefile
pipeline: rna-seq
outdir:
configFile:
clusterConfigFile:
local: False
**maxJobs: 48**
## directory with fastq files
indir:
## preconfigured target genomes (mm9,mm10,dm3,...) , see /path/to/snakemake_workflows/shared/organisms/
## Value can be also path to your own genome config file!
genome:
## FASTQ file extension (default: ".fastq.gz")
ext: '.fastq.gz'
## paired-end read name extension (default: ["_R1", "_R2"])
reads: ["_R1","_R2"]
## assume paired end reads
pairedEnd: True
## Number of reads to downsample from each FASTQ file
downsample:
## Options for trimming
trim: False
trimmer: cutadapt
trimmerOptions:
## further options
mode: alignment,deepTools_qc
sampleSheet:
bwBinSize: 25
fastqc: False
featureCountsOptions: -C -Q 10 --primary
filterGTF:
fragmentLength: 150
libraryType: 2
**salmonIndexOptions: --type quasi -k 19**
dnaContam: True
## supported mappers: STAR HISAT2
**aligner: HISAT2**
alignerOptions:
verbose: False
plotFormat: pdf
# for allele-spcific mapping
SNPFile:
NMaskedIndex:
#### Flag to control the pipeline entry point
fromBAM: False
bamExt: '.bam'
#umi_tools
UMIBarcode: False
bcPattern: NNNNCCCCCCCCC #default: 4 base umi barcode, 9 base cell barcode (eg. RELACS barcode)
UMIDedup: False
UMIDedupSep: "_"
UMIDedupOpts: --paired
################################################################################
# Call snakemake directly, i.e. without using the wrapper script:
#
# Please save a copy of this config yaml file and provide an adjusted config
# via '--configFile' parameter!
# example call:
#
# snakemake --snakefile /path/to/snakemake_workflows/workflows/RNA-seq/Snakefile
#           --configFile /path/to/snakemake_workflows/workflows/RNA-seq/defaults.yaml
#           --directory /path/to/outputdir
#           --cores 32
#############################################################################

**Comment by zifeng9527** [comment]
By the way, I will try to use the alignment free mode to run it.

RNA-seq  --mode alignment-free --local -i ./input_RNA-seq -o ./out_RNA-seq mm10 --reads '_R1' '_R2' --fastqc --plotFormat pdf -j 48 --local --sampleSheet sampleSheet.tsv --dnaContam --DAG --featureCountsOptions '-p -B' 


I will feedback the reslut about 24 hours later.


Thanks.

**Comment by zifeng9527** [comment]
I like snakePipes, because it friendly to use for our freshbird (only one command line can generate the result ). I hope I can fix the problem.

**Comment by katsikora** [comment]
Dear Zifeng,

if the table you pasted in your very first post above is what you submit to snakePipes as sample sheet, then it is **not conformant** with our requirements. Please see https://snakepipes.readthedocs.io/en/latest/content/workflows/RNA-seq.html or the screenshot below for details. 
![image](https://user-images.githubusercontent.com/7079932/71657602-eae11d80-2d40-11ea-8acb-f4ab88d6280b.png)

Also, from that table, it is apparent you have two major sources of intra-group heterogeneity (batch, sex) you should probably make up for.

Best,

Katarzyna

**Comment by katsikora** [comment]
Closing because of lack of feedback from the user.
