### ISSUE TITLE
createIndices Error: snakemake returned an error code of 1

### ISSUE THREAD

**Issue by xiuru** [maxplanck-ie/snakepipes#534]
Hello, thanks for releasing this amazing package. This will be very helpful for my project with different sequencing data. But when create the genome indices  i met an error like:
 /bin/sh: 1: module: not found
/bin/sh: 1: SlurmEasy: not found
Error submitting jobscript (exit code 127):

Logfile: [createIndices_run-1.log](https://github.com/maxplanck-ie/snakepipes/files/4006988/createIndices_run-1.log)

version installed:
snakePipes 1.3.2
conda 4.8.0
Python 3.6.7

I searched on google and issues for snakepipes, but had no clue about how to fix this. I am new to conda pipeline, could you please give me some advice about how to solving this problem?

Thank you in advance! 
Xiuru

**Comment by dpryan79** [comment]
You need to run the configuration step to setup how to submit jobs to your cluster. See https://snakepipes.readthedocs.io/en/latest/content/setting_up.html#modify-global-options and https://snakepipes.readthedocs.io/en/latest/content/setting_up.html#configure-your-cluster

**Comment by xiuru** [comment]
Thanks Ryan, i am working on this now

**Comment by xiuru** [comment]
Hi Ryan, thanks for your help. Create Indices works on cluster now, but i am curious about how to setup cluster.yaml if i want to run this pipeline on a linux desktop.

**Comment by dpryan79** [comment]
You just need the `--local` option then.
