### ISSUE TITLE
Error in rule create_annotation_bed

### ISSUE THREAD

**Issue by xiuru** [maxplanck-ie/snakepipes#535]
Hello,
I tried to use RNAseq pipeline with command:
`RNA-seq -i /work/lab/xiuru/data/RNASeq/ -o /work/lab/xiuru/data/RNASeq/results/ --sampleSheet /work/lab/xiuru/data/RNASeq/DBJ-sample.txt --libraryType 0 zm4`
 But met an error at rule create_annotation_bed. I have no clue after checking the logfile: 

> join: invalid file number in field spec: `auto'

[create_annotation_bed.24565670.err.txt](https://github.com/maxplanck-ie/snakepipes/files/4012807/create_annotation_bed.24565670.err.txt)

Thank you in advance!
Xiuru

**Comment by katsikora** [comment]
Hi Xiuru,

thanks for reporting the issue.
This looks like a shell command error. What kind of OS are you running your analysis on?
This has been tested on CentOS (linux) and should be MacOS compatible, too.

Best,

Katarzyna

**Comment by xiuru** [comment]
Hi Katarzyna,
It is Scientific Linux release 6.10 (Carbon).

**Comment by katsikora** [comment]
Hi Xiuru,

Can you post the output of <code>man join</code> on your system?

We pass `-o auto` to join in rule create_annotation_bed to automatically determine the number of fields in the output file.

This is what I'm looking for:

![image](https://user-images.githubusercontent.com/7079932/71718093-6ebb0880-2e1a-11ea-8b23-d591d8b4c563.png)
![image](https://user-images.githubusercontent.com/7079932/71718120-7e3a5180-2e1a-11ea-91f7-fc0c4a155d2d.png)

**Comment by xiuru** [comment]
Hi Katarzyna,

Sorry for my late reply. The -o auto may not work on my system. Here is the description of -o option:
```
-o FORMAT
    obey FORMAT while constructing output line
```
There us no description about the keyword 'auto'.

**Comment by dpryan79** [comment]
This will be fixed in the next release :)
