### ISSUE TITLE
STAR zcat CIFS doesn't allow FIFOs

### ISSUE THREAD

**Issue by tamerbio** [maxplanck-ie/snakepipes#537]
Dear All,
is there any option to modify STAR option `--readFilesCommand zcat` to  `--readFilesIn <(gunzip -c R1.fastq.gz) <(gunzip -c R2.fastq.gz)` as we are running snakePipes on our shared server which is mount by CIFS  which doesn't allow FIFO files required for  zcat option therefore STAR gets stuck.
many many thanks
Tamer

**Comment by dpryan79** [comment]
That should be possible with some internal code changes. I'm amazed that pipes don't work on CIFS. Do you have issues with other tools like bowtie2? Most of them are running zcat internally.

**Comment by dpryan79** [comment]
BTW, can you let me know what error you get when you use things as is? I'm wondering if there's just an option that can be given to the mounter to fix things.

**Comment by tamerbio** [comment]
I have no problems with bowtie2. regarding BWA still did not check .. it seems it is STAR -specific issue

**Comment by dpryan79** [comment]
OK, that makes this easier to combat then.

**Comment by tamerbio** [comment]
thanks man

**Comment by tamerbio** [comment]
It did not throw any error message ... the pipeline just jammed with no progress nor error message

**Comment by dpryan79** [comment]
This will be fixed in the next release, where I've used `<(gunzip -c ...)` like Alex suggested.
