### ISSUE TITLE
creating genes.bed

### ISSUE THREAD

**Issue by sunta3iouxos** [maxplanck-ie/snakepipes#544]
Hi all,
I am working with Zea mays and would like to create the genes.bed file, is there a way to do it from the gtf file? In enseblegenomes there is no such file.

Thank you for your time

**Comment by dpryan79** [comment]
The `createIndices` workflow should construct it for you.

**Comment by sunta3iouxos** [comment]
Thank you for the info, and the immediate response. somehow I missed that.

So this script will create everything I need and place the links in organism.yaml file?
The fasta and gtf files are in:
/projects/public/Genomes/fasta/Zea_mays_B73/
will the produced files created in that folder?

**Comment by sunta3iouxos** [comment]
Thank you for the immediate answer.
If I edit the `snakePipes/workflows/createIndices/defaults.yam`l do I need to use the command line options?
is createIndices path agnostic? if I run it as
 `bash /home/sunta3iouxos/snakemake/miniconda3/envs/snakePipes/bin/createIndices`
will it read the deafults.yalm and create the files in the proper positions?

**Comment by dpryan79** [comment]
It's a python script so please omit `bash`, but otherwise yes, it figures out where it's installed and where the installed files are relative to itself.

**Comment by sunta3iouxos** [comment]
Perfect, I believe I figured it out. I run into some other issues and will open a new thread since it is unrelated to this one.
