### ISSUE TITLE
handling lanes

### ISSUE THREAD

**Issue by sunta3iouxos** [maxplanck-ie/snakepipes#546]
Hi all,
is it possible for the tool to correctly recognize lanes and merge them?
my fastq files are of the following naming (where R1 ,R2 are the pairs):
A006850049_116290_S19_L001_R1_001.fastq.gz
A006850049_116290_S19_L001_R2_001.fastq.gz
A006850049_116290_S19_L002_R1_001.fastq.gz
A006850049_116290_S19_L002_R2_001.fastq.gz

is a type of:
{machineID}_{sampleName}_{sampleNumber}_{lane}_{pair}_*.fastq.gz

Thank you in advance

**Comment by dpryan79** [comment]
There's a `preprocessing` pipeline for this, though it won't automatically recognize the lanes since I rather assume people just have `bcl2fastq` to merge for them when they do demultipleixing.

**Comment by sunta3iouxos** [comment]
> 
> 
>  assume people just have `bcl2fastq` to merge for them when they do demultipleixing.

I believe that facilities tend provide also the lanes since some people complaining on "batch effects" (no idea on the placebo or not effect and on the false idea that everything introduces unwanted variability, no need to be analysed here)

So I need to do it manually before starting the pipeline.

I just think that it it will be a good inclusion since if I am not mistaken the snakemake can handle the lanes:
{{wildcard.sample}}_{wildcard.lane}.bam"
or something like this

**Comment by dpryan79** [comment]
I haven't seen a lane-level batch effect in the better part of a decade :P

I suppose I could just add an option to the preprocessing pipeline to generate a sample sheet given standard Illumina naming. I'll try to get that implemented today so it'll be in the next release.

**Comment by dpryan79** [comment]
There is now an option for this in the preprocessing pipeline. Hopefully we can push out the next release very soon.
