### ISSUE TITLE
--fromBAM is not working in snakePipes 1.3.0, at least RNAseq

### ISSUE THREAD

**Issue by katsikora** [maxplanck-ie/snakepipes#549]
Rules link_bam_bai_external and filter_reads are ambiguous for the file filtered_bam/18070907_GCN5-KD_301x174_unfertilized_1a_RNA.filtered.bam.

**Comment by dpryan79** [comment]
WGBS also has an error when using `--fromBAM`. I'll make a PR fixing these and adding them to the CI tests today.

**Comment by dpryan79** [comment]
Fixed in `develop`
