### ISSUE TITLE
csaw for ATAC-seq

### ISSUE THREAD

**Issue by LeilyR** [maxplanck-ie/snakepipes#558]
we might need to check for the content of `Filtered.results` bed files. The empty bed files throw an error later on when building matrices using `computeMatrix`. Alternatively we can avoid generating the empty ones, then the current code would work since it checks if a bed file exists.

**Comment by katsikora** [comment]
Hi Leily, the current code checks if the file exists and the size is larger than zero, so I don't know how this error occurs.
If you just skip generating empty files, you will probably get missing Output exception.
Perhaps you want to try the recent "checkpoint" functionality of snakemake, which allows you to determine which files actually got generated dynamically during the run?

**Comment by katsikora** [comment]
Fixed by @LeilyR Leily and merged into develop.
