### ISSUE TITLE
cluster_logs : only keep non-empty files

### ISSUE THREAD

**Issue by vivekbhr** [maxplanck-ie/snakepipes#56]
During the cleanup at the end of the pipeline, only the non-empty files in cluster_logs should be kept.

**Comment by dpryan79** [comment]
Perhaps likewise everything in the `*/logs/` directories too.

**Comment by dpryan79** [comment]
This is implemented in my current ChIPseq PR. At some point I'll add a `--cleanup` option to remove all logs, benchmarks, and `.snakemake`.
