### ISSUE TITLE
preprocessing: 'InputFiles' object has no attribute 'tempOut'

### ISSUE THREAD

**Issue by AdrijaK** [maxplanck-ie/snakepipes#569]
```bash
source activate snakePipes
preprocessing --version
```
/localhome/inst/usr123/analysis/software/anaconda3/envs/snakePipes/bin/preprocessing 1.3.2

```bash
preprocessing -i rawfastq -o fastq --optDedupDist 40 --clumpifyOptions 'spany=t adjacent=t' --fastqc --local --sampleSheet $PWD/rawfastq/samples.tsv
```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 5
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	6	FASTQ1
	6	FastQC_singleEnd
	1	all
	6	clumpify
	1	multiQC
	6	origFASTQ1
	1	splitFastq2YAML
	27

[Thu Feb 27 10:32:50 2020]
rule clumpify:
    input: mergedFASTQ/test_sample_R1.fastq.gz
    output: deduplicatedFASTQ/test_sample_R1.fastq.gz, deduplicatedFASTQ/test_sample.metrics, deduplicatedFASTQ/test_sample_temp.fq.gz
    log: deduplicatedFASTQ/logs/test_sample.stdout, deduplicatedFASTQ/logs/test_sample.stderr
    jobid: 5
    benchmark: deduplicatedFASTQ/.benchmarks/test_sample
    wildcards: sample=test_sample
    threads: 5

**RuleException in line 87 of /localhome/inst/usr123/analysis/software/anaconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/rules/preprocessing.snakefile:
'InputFiles' object has no attribute 'tempOut'**

```bash
snakePipes info | grep 'defaults.yaml'
```

**The workflow-generic defaults.yaml file is:
    /localhome/inst/usr123/analysis/software/anaconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/defaults.yaml**
Workflow-specific cluster.yaml and defaults.yaml files are in:

```bash
less /localhome/inst/usr123/analysis/software/anaconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/defaults.yaml
```

clusterConfig: /localhome/inst/usr123/analysis/software/anaconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/cluster.yaml
emailSender: null
onlySSL: false
organismsDir: /localhome/inst/usr123/analysis/software/anaconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/organisms
smtpPassword: null
smtpPort: 0
smtpServer: null
smtpUsername: null
snakemakeOptions: ' --use-conda --conda-prefix /localhome/inst/usr123/analysis/software/anaconda3/envs/snakePipes'
**tempDir: /localhome/inst/usr123/analysis/tmp_snakePipes/**

Thanks in advance.

**Comment by AdrijaK** [comment]
This issue disappears if I avoid using --optDedupDist 40

**Comment by dpryan79** [comment]
This is a typo in the rule. Can you edit `/localhome/inst/usr123/analysis/software/anaconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/rules/preprocessing.snakefile`? On line 110, change `input.tempOut` to `output.tempOut`. I'll fix this real quick for the next release.

**Comment by AdrijaK** [comment]
This worked, thank you!
