### ISSUE TITLE
createIndoces: name 'toolsVersion' is not defined

### ISSUE THREAD

**Issue by AdrijaK** [maxplanck-ie/snakepipes#579]
[createIndices.log](https://github.com/maxplanck-ie/snakepipes/files/4275379/createIndices.log)

**Comment by dpryan79** [comment]
That's odd, it should be getting defined in each workflow. @LeilyR Can you have a look?

**Comment by AdrijaK** [comment]
Found an error in my snakePipes configuration: 
`snakemakeOptions:  --use-conda --conda-prefix path/to/anaconda3/envs/snakePipes/`

instead of an actual path.

**Comment by dpryan79** [comment]
Ah, and fixing that was all that was needed to resolve this? I never would have considered that.

**Comment by AdrijaK** [comment]
actually not, still same error

**Comment by dpryan79** [comment]
Darn, would have been a nicely simple fix :(

**Comment by AdrijaK** [comment]
Here is the way I set up my environment:

create conda environment:
```bash
conda create -n snakePipes -c mpi-ie -c bioconda -c conda-forge snakePipes
conda activate snakePipes
snakePipes config --snakemakeOptions " --use-conda --conda-prefix ~/analysis/software/anaconda3/envs/snakePipes/"
```

get list of chromosome names to ignore for normalisation:
```bash
wget -qO-  ftp://ftp.ncbi.nlm.nih.gov/genomes/genbank/vertebrate_mammalian/Mus_musculus/all_assembly_versions/GCA_000001635.8_GRCm38.p6/GCA_000001635.8_GRCm38.p6_assembly_report.txt | awk '{print $NF}' | grep 'random\|chrUn\|chrM\|chrX\|chrY' > ignoreForNormalization.txt
```

get blacklisted regions:
```bash
#get a list of chromosome sizes
wget -qO- ftp://ftp.ncbi.nlm.nih.gov/genomes/genbank/vertebrate_mammalian/Mus_musculus/all_assembly_versions/GCA_000001635.8_GRCm38.p6/GCA_000001635.8_GRCm38.p6_assembly_report.txt | grep -v '^#' |  awk -v RS='\r\n' '{print $10"\t"$9}' | grep -v '^na'  > GRCm38.genome

# get blacklisted regions for mouse, expand the regions 50bp both ways and remove overlaps
wget -qO- https://github.com/Boyle-Lab/Blacklist/blob/master/lists/mm10-blacklist.v2.bed.gz?raw=true | gunzip -c | sort -k1,1 -k2,2n | slopBed -i stdin -g GRCm38.genome -b 50 > mm10-blacklist.v2.bed
```

create indices
```bash
conda activate snakePipes

createIndices \
--genomeURL ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M24/GRCm38.primary_assembly.genome.fa.gz \
--gtfURL ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M24/gencode.vM24.primary_assembly.annotation.gtf.gz \
--blacklist mm10-blacklist.v2.bed \
--ignoreForNormalization ignoreForNormalization.txt \
--local \
-j 40 \
-o GRCm38_M24 GRCm38_M24 > createIndices.log
```

**Comment by dpryan79** [comment]
Thanks, that will make debugging easier :)

**Comment by dpryan79** [comment]
Can you run `snakePipes info` and the post the contents of the file listed under "The workflow-generic defaults.yaml file is"? My guess is that it's missing a line.

**Comment by LeilyR** [comment]
which snakepipes version is this? Only the very recent release from today actually has toolsVersion in the yaml file.

**Comment by LeilyR** [comment]
the toolsVersion is missing form the yaml file in the log file you have sent us. Can you be sure that you are not mixing up two different versions? Is it possible to do the installation in a fresh env and conda activate to that env and call createIndices from there?

**Comment by vitaly001** [comment]
I run mRNA-seq version 2.0.0 and got same error:
NameError in line 274 of /home/parallels/miniconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/workflows/mRNA-seq/Snakefile:
name 'toolsVersion' is not defined
  File "/home/parallels/miniconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/workflows/mRNA-seq/Snakefile", line 274, in __onstart
Error: snakemake returned an error code of 1, so processing is incomplete!

**Comment by dpryan79** [comment]
Somehow the `defaults.yaml` file didn't get updated. Please add `toolsVersion: True` to the end of the "The workflow-generic defaults.yaml file is" listed by `snakePipes info`.

**Comment by dpryan79** [comment]
@vitaly001 Did you happen to run `snakePipes config`? I just noticed that that will cause this error to occur when then running createIndices or another pipeline (I'll fix that real quick).

**Comment by dpryan79** [comment]
I just pushed out version 2.0.1 so this will hopefully not happen again.

**Comment by AdrijaK** [comment]
Thank you for the prompt solution. I have been locked out of the server since Monday afternoon, but I will check how it works as soon as I get the access.

**Comment by vitaly001** [comment]
Not yet. I need to update to 2.0.1 version first

**Comment by AdrijaK** [comment]
I updated to 2.0.1, and the error is gone.

**Comment by LeilyR** [comment]
I close this issue since the error seems to be taken care of in 2.0.1. 
@vitaly001 reopen it please if you still have a problem with it.
