### ISSUE TITLE
sample.tsv for WGBS

### ISSUE THREAD

**Issue by sunta3iouxos** [maxplanck-ie/snakepipes#581]
Hi all,
In my case there are 2 groups (wild_type and mutant) each consisted of triplicates (109242, 109243, 109244) and (109245, 109246, and 109247).
the file names are of the following type:
A006200053_109243_S1_L002_R1_001.fastq.gz
so should I use the 
sampleSheet.example.tsv or the preprocessing_sampleSheet.example.tsv
in https://github.com/maxplanck-ie/snakepipes/tree/master/docs/content ?

thank you in advance

**Comment by katsikora** [comment]
Hi, have a look at our example sample sheet: https://github.com/maxplanck-ie/snakepipes/blob/master/.ci_stuff/test_sampleSheet.tsv

**Comment by sunta3iouxos** [comment]
Hi,
I've looked at it but it does not explicitly directs the pipeline to a specific fastq, so will it be something like:
```
                                                                                                name	condition
/path/to/file/A006200053_109243_S1_L002_R1_001.fastq.gz	109243	wild_type
/path/to/file/A006200053_109244_S1_L002_R1_001.fastq.gz	109244	wild_type
/path/to/file/A006200053_109244_S1_L002_R1_001.fastq.gz	109244	wild_type
/path/to/file/A006200053_109245_S1_L002_R1_001.fastq.gz	109245	mut
/path/to/file/A006200053_109246_S1_L002_R1_001.fastq.gz	109246	mut
/path/to/file/A006200053_109247_S1_L002_R1_001.fastq.gz	109247	mut

```

**Comment by katsikora** [comment]
Sample names in the "name" column have to be such that:
sample + reads_list + read_extention  =  basename of your read file
If you have a file called sample1_R1.fastq.gz, then sample 1 is what you want to put in the "name" column of the sample sheet. The rest will be taken care of by the pipeline.

sample1(sample) + _R1 (reads_list) + .fastq.gz (read_extention)

Also, note that you'll either have to modify the read dictionary to accomodate "_R1_001", as it doesn't match the default ['_R1'] (same for R2?), or to rename your files.

**Comment by sunta3iouxos** [comment]
Nice,
So I need to either rename the files to 109243_R{1,2}.fastq.gz
or
sample use the whole A006200053_109243
for the R{1,2} part I will need to change the default ['_R1'] in the WGBS .yalm to ['_S1_L002_R1_001', '_S1_L002_R2_001']

the last part will probably be easier.

Still, do I need a double entry of the name, like:
                                    name                          condition
A006200053_109243 A006200053_109243 wild_type

the name in the index in which column is assigned.

Best
Theo

**Comment by katsikora** [comment]
Either of those modifications should work. You can also modify the reads list by passing the '--reads' argument to your WGBS command.

So this extra instance of your sample name will be treated as "rownames" for the data.frame in R. The second instance will be parsed into the "name" column, and then comes the "condtion" column.

**Comment by sunta3iouxos** [comment]
I am sorry but I can not seem to find a --reads option for the WGBS, am I missing something?

**Comment by katsikora** [comment]
usage: WGBS
       -i INDIR -o OUTDIR [-h] [-v] [--ext EXT] [--reads READS READS]
       [-c CONFIGFILE] [--clusterConfigFile CLUSTERCONFIGFILE] [-j INT]
       [--local] [--keepTemp] [--snakemakeOptions SNAKEMAKEOPTIONS] [--DAG]
       [--version] [--emailAddress EMAILADDRESS] [--smtpServer SMTPSERVER]
       [--smtpPort SMTPPORT] [--onlySSL] [--emailSender EMAILSENDER]
       [--smtpUsername SMTPUSERNAME] [--smtpPassword SMTPPASSWORD]
       [--downsample INT] [--trim] [--trimmer {cutadapt,trimgalore,fastp}]
       [--trimmerOptions TRIMMEROPTIONS] [--fastqc] [--bcExtract]
       [--bcPattern BCPATTERN] [--UMIDedup] [--UMIDedupSep UMIDEDUPSEP]
       [--UMIDedupOpts UMIDEDUPOPTS] [--bwBinSize BWBINSIZE]
       [--plotFormat STR] [--blacklist BLACKLIST] [--sampleSheet SAMPLESHEET]
       [--noAutoMethylationBias] [--maxDist MAXDIST] [--minCpGs MINCPGS]
       [--minMethDiff MINMETHDIFF] [--minCoverage MINCOVERAGE] [--FDR FDR]
       [--MethylDackelOptions METHYLDACKELOPTIONS] [--fromBAM]
       [--bamExt BAMEXT] [--singleEnd] [--DMRprograms DMRPROGRAMS] [--skipDOC]
       [--GCbias]
       GENOME

MPI-IE workflow for WGBS analysis

usage example:
    WGBS -i read_input_dir -o output-dir mm10

positional arguments:
  GENOME                Genome acronym of the target organism. Either a yaml
                        file or one of: SchizoSPombe_ASM294v2, hg38, hs37d5,
                        mm9, mm10, dm6, mm10_gencodeM13, GRCz10, dm3

Required Arguments:
  -i INDIR, --input-dir INDIR
                        input directory containing the FASTQ files, either
                        paired-end OR single-end data
  -o OUTDIR, --output-dir OUTDIR
                        output directory

General Arguments:
  -h, --help            show this help message and exit
  -v, --verbose         verbose output (default: 'False')
  --ext EXT             Suffix used by input fastq files (default:
                        '.fastq.gz').
  --reads READS READS   Suffix used to denote reads 1 and 2 for paired-end
                        data. This should typically be either '_1' '_2' or
                        '_R1' '_R2' (default: '['_R1', '_R2']). Note that you
                        should NOT separate the values by a comma (use a
                        space) or enclose them in brackets.

WGBS --version
WGBS 2.0.0

**Comment by sunta3iouxos** [comment]
I am sorry but I can not seem to find a --reads option for the WGBS, am I missing something?

**Comment by sunta3iouxos** [comment]
It appears hat I am getting blind.
Thank you again.

another one on the --reads:
can I use wild cards as: _S*_L002_R1

**Comment by katsikora** [comment]
You're welcome!

I'm pretty sure this will fail.

**Comment by sunta3iouxos** [comment]
it did!
with error :Error! NO samples found in dir
Best option so far to rename the fastq files to the bare minimum required.
So I believe that this ends this session
Best
