### ISSUE TITLE
Docker/Conda

### ISSUE THREAD

**Issue by vivekbhr** [maxplanck-ie/snakepipes#59]
For the first public release of our pipeline, we should make it independent using docker and conda.. Then we can also see whether we can add some some travis tests (issue #34) .

**Comment by dpryan79** [comment]
If you want to go the docker route we might as well switch to singularity instead and avoid the permissions issues.

**Comment by dpryan79** [comment]
We can use this as a list of any remaining rules that need to use conda after the hackathon. Of course if there are none left then someone please close this :)

**Comment by vivekbhr** [comment]
Rules remaining for condafication after hackathon : 
 - [ ] macs2
 - [ ] macs2 QC (atac and chip)
 - [ ] DESeq2
 - [ ] CSAW
 
(@steffenheyne @katsikora please update)

**Comment by katsikora** [comment]
WGBS is all condified as of this afternoon

**Comment by dpryan79** [comment]
I'm working on macs2, macs2 QC, and CSAW, since those are needed in the ATAC-seq pipeline.

**Comment by dpryan79** [comment]
The following rules in `develop` still need to be moved to conda:

 - [ ] convert_flagstat_output (ChIP-seq_qc_report.snakefile)
 - [ ] report_flagstat_all_data (ChIP-seq_qc_report.snakefile)
 - [ ] qc_report_all (ChIP-seq_qc_report.snakefile)
 - [ ] hisat2 (HISAT2.snakefile)
 - [ ] histoneHMM (histoneHMM.snakefile)
 - [ ] histoneHMM_out_gz (histoneHMM.snakefile)
 - [ ] MACS2 (MACS2.snakefile)
 - [ ] MACS2_peak_qc (MACS2.snakefile)
 - [ ] combine_sample_counts (scRNAseq.snakefile)
 - [ ] extract_scale_counts (scRNAseq.snakefile)
 - [ ] sc_bam_featureCounts_genomic (scRNAseq.snakefile)

So mostly ChIP-seq and some R code.

**Comment by vivekbhr** [comment]
I don't remember when we made HISAT2.snakefile, since HISAT2 was only used for RNA mapping..

**Comment by dpryan79** [comment]
I have a feeling that `HISAT2.snakefile` isn't imported anywhere any more. I'm checking into that now.

**Comment by steffenheyne** [comment]
HISAT2 RNAseq mapping is part of RNA_mapping.snakefile so I think as well that we can remove HISAT2.snakefile
