### ISSUE TITLE
[WGBS] plots produced (only metilene finished... at this point)

### ISSUE THREAD

**Issue by sunta3iouxos** [maxplanck-ie/snakepipes#601]
Hi again,
firstly the drm-seq part did not finished but the metilene finished successfully. I will come back to it maybe latter.
A. I noticed that the plots posted in the tutorial are not in the output folder. the PCA plots are missing.
B. After the analysis I got the following plots. The Volcano plot seems a bit off. Can I change the axis for the Volcano plot, from mean methylation to log2 so that it will look better?
C. Since I do not have the PCA I do not know what to make out of the QValueDistribution plot. All values seem to stack at 1.00, but I was expecting a bit of variability?

![Volcano](https://user-images.githubusercontent.com/20404754/77233219-6e731380-6ba6-11ea-85b5-f2d570993b68.png)
![MethylationDensity](https://user-images.githubusercontent.com/20404754/77233221-6f0baa00-6ba6-11ea-8ce1-ba94d0a74f97.png)
![QValueDistribution](https://user-images.githubusercontent.com/20404754/77233222-6f0baa00-6ba6-11ea-90da-5ad2d067dea6.png)

Thank in advance for any input

**Comment by sunta3iouxos** [comment]
By the way this is plant methylome so it is different from mammal's.

**Comment by katsikora** [comment]
Hi Theo,

it looks like the PCA plots need to be added back in. You can always use "metilene.IN.txt" to plot PCA for your data (e.g. in R).

I have to say the "volcano" plot and the bottom-most qvalue histogram seem contradictory, i.e. if all values got corrected to 1, then you should have a horizontal line in the topmost plot, too.

Other than that, methylation difference is a more native statistic than log2FC for methylation data. 

If that bottom plot is correct, that means all the nominal pvalues were corrected to qvalues =1 after adjustment for multiple hypothesis testing. This can happen, if the effect size is small and/or variability large.

From your density plot (middle plot), there appears there is very little difference between the groups.

**Comment by sunta3iouxos** [comment]
(Sidenote, First of all I ma a bit rusty with WGBS, if you ca provide with reading material I could be happy)

> it looks like the PCA plots need to be added back in. You can always use "metilene.IN.txt" to plot PCA for your data (e.g. in R).
OK, I can do that, but in the next update you'll get it back?
 
> I have to say the "volcano" plot and the bottom-most qvalue histogram seem contradictory, i.e. if all values got corrected to 1, then you should have a horizontal line in the topmost plot, too.
> From your density plot (middle plot), there appears there is very little difference between the groups.

Exactly, I was expecting something else. And that was the main reason for this post. and I am wondering about the analysis. Density plot shows little difference, but the volcano plot tells another story.

> Other than that, methylation difference is a more native statistic than log2FC for methylation data.
 
> If that bottom plot is correct, that means all the nominal pvalues were corrected to qvalues =1 after adjustment for multiple hypothesis testing. This can happen, if the effect size is small and/or variability large.

will dmr-seq provide a better outcome?

Thank you for your time again

**Comment by katsikora** [comment]
Alright, so I'm not sure why the histogram ends up like this for your data. There is some binning of qvalues for the histogram, maybe this is the issue.

On our test data:
![MethylationDensity](https://user-images.githubusercontent.com/7079932/77556123-5d811580-6eb8-11ea-845f-c5a878c23177.png)
![Volcano](https://user-images.githubusercontent.com/7079932/77556125-5f4ad900-6eb8-11ea-8bf2-c8c1aa65ce7e.png)
![QValueDistribution](https://user-images.githubusercontent.com/7079932/77556131-61149c80-6eb8-11ea-809a-913eb931c372.png)

Maybe you're more lucky with dmrseq or DSS (the latter tends to be quite slow).

Here the link to dmrseq preprint:
https://www.biorxiv.org/content/10.1101/183210v1.full

Hope this helps,

Best,

Katarzyna

**Comment by sunta3iouxos** [comment]
I now realized that I have not specified that my analysis is on plant methylome that is heavily methylated. That can probably explain the graphs.
And I am wondering if there should be an option that can accommodate the highly methylated genomes.
Also from the metilene manual I am reading that:
In case of memory issues (almost exclusively for analyzing non-CpG contexts in plants), you can limit the maximum segment length using the option -G, --maxseg.
12.2 Option -G
This option sets the maximum segment length in terms of the number of data points in cases where the memory consumption becomes an issue. It occurs almost exclusively when analyzing cytosines from non-CpG contexts (e.g. in plants). By default, the maximum segment length is unlimited (i.e. set to -1).

In addittion is it possible to use specific option for the DMR programs?

Best

**Comment by katsikora** [comment]
Hi Theo,

the analysis is agnostic to the methylation levels in your sample. Sure, your control and treatment samples are highly methylated, but there is nothing 'special' about that. We have previously used this pipeline to call differential methylation in zebrafish sperm DNA, which is also very highly methylated.

In the current setup, only only methylation values for cytosines in CpG context are extracted and only these are passed to metilene, dmrseq or DSS.
Are you interested in non-CpG context methylation?

Can you give me the source for this metilene option?
I don't see it on https://www.bioinf.uni-leipzig.de/Software/metilene/Manual/#12_parameters .

Best,
Katarzyna

**Comment by sunta3iouxos** [comment]
sorry for replying so late:
A. about the -G option
from here:
https://www.bioinf.uni-leipzig.de/Software/metilene/Downloads/
download the file. in the included pdf, page 6
-G, --maxseg Integer -1 Maximum segment length in case of memory issues
hope it helps.

B. about the  zebrafish sperm DNA:
do you have again a publication in mind about the plots and also about the correction of the q-values/count

**Comment by katsikora** [comment]
A.Thanks, we will add freetext option to metilene etc. that will allow the user to pass anything they find relevant, e.g. -G.

B. Our internal data is somewhere in the revision process and not yet publically available.This study https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4030421/ (doi: 10.1016/j.cell.2013.04.030) uses similar starting material to ours and their data is available on GEO.

**Comment by katsikora** [comment]
You can now pass freetext options to metilene via --metileneOptions , e.g. --metileneOptions ' -G your_value' , on top of the options that have been directly passed to metilene before e.g. --maxDist, --minCpGs, --minMethDiff.
