### ISSUE TITLE
{WGBS} DMR genome wide or at specific locy

### ISSUE THREAD

**Issue by sunta3iouxos** [maxplanck-ie/snakepipes#604]
Hallo,
So in my understaning the plots from the metilene analysis correspond to gene associated/proximate areas, identified by the provided gtf file.

is it possible to perform the analysis in other areas like genome wide or at specific loci like the repeated elements?

Best
Theo

**Comment by katsikora** [comment]
Hi Theo,

metilene or dmrseq are used to call 'DMRs' or differentially-methylated regions genome-wide. This will segment your CpGs into regions based on CpG density and distance to one-another.
See metilene publication for details: https://genome.cshlp.org/content/early/2015/12/24/gr.196394.115

These DMRs are further annotated with the nearest gene and distance to it, using some cutoff criteria.

If you want to analyze specific loci, you can provide a bed file to the workflow with "--MethylDackelOptions -l /path/to/your/file.bed". If you want to analyze repeats, you can provide a bed file e.g. from the RepeatMasker.

Best,

Katarzyna
