### ISSUE TITLE
[WGBS][Enhancement][Request] introduce also a --no-index-bam/markDupes/indexMarkDupes

### ISSUE THREAD

**Issue by sunta3iouxos** [maxplanck-ie/snakepipes#606]
While using the -fromBam option the bam files are sent once again for sorting, dedub, indexing. Whe we want to resume an analysis using ready made bam files it would be also nice to have options to avoid those steps.

Best
Theo

**Comment by katsikora** [comment]
That's a good point, we will add it to the workflows.

**Comment by katsikora** [comment]
This is now implemented in WGBS via: `--fromBAM` as before and then add `--skipBamQC` .
