### ISSUE TITLE
[WGBS] using /tmp, although I set a different temp directory

### ISSUE THREAD

**Issue by sunta3iouxos** [maxplanck-ie/snakepipes#608]
Hi all,

Suddenly snakePipes is using the /tmp folder although I redirected to different folders, look below for details. [this fix](https://github.com/maxplanck-ie/snakepipes/issues/521) did not work for me

```
finding positions of the duplicate reads in the file...
sambamba-markdup: Wrote 4089 instead of 177488 objects of type ubyte 
to file 
`/tmp/snakepipes.5VFa94Xugt/109242/sambamba-pid2745-markdup-dbkf/PairedEndsInfofkgx11'
(No space left on 
device)
```
I had no such an error before, and I am redirecting all tmp files to:

> snakemake/miniconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/shared/defaults.yaml (END)

```
/scratch/snakePipes
clusterConfig: shared/cluster.yaml
emailSender: null
onlySSL: false
organismsDir: shared/organisms
smtpPassword: null
smtpPort: 0
smtpServer: null
smtpUsername: null
snakemakeOptions: ' --use-conda --conda-prefix /home/hthiele0/snakemake/miniconda3/envs '
tempDir:  /scratch/snakemake/
toolsVersion: true
```
and even my custom yaml is:

> less WGBS.config.yaml

```
DMRprograms: metilene,dmrseq
FDR: 0.1
GCbias: false
MethylDackelOptions: --mergeContext --maxVariantFrac 0.25 --minDepth 4
UMIBarcode: false
UMIDedup: false
UMIDedupOpts: --paired
UMIDedupSep: _
aligner: bwameth
bamExt: .sorted.bam
baseDir: snakemake/miniconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes
bcPattern: NNNNCCCCCCCCC
blacklist: null
bwBinSize: 25
clusterConfig: shared/cluster.yaml
clusterConfigFile: /scratch/ccg-ngs/fastq/BU16/WGBS.cluster_config.original.yaml
configFile: snakemake/miniconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/workflows/WGBS/defaults.yaml
createDAG: true
downsample: null
emailAddress: null
emailSender: null
ext: .fastq.gz
fastqc: false
fromBAM: true
genome: ZeamaysB73RefGenv4
indir: /scratch/ccg-ngs/fastq/BU16/bam
keepTemp: false
local: false
maxDist: 300
maxJobs: 12
minCoverage: 5
minCpGs: 10
minMethDiff: 0.1
noAutoMethylationBias: false
onlySSL: false
organismsDir: shared/organisms
outdir: /scratch/ccg-ngs/fastq/BU16/analyzed3
pairedEnd: true
pipeline: WGBS
plotFormat: pdf
reads:
- _R1
- _R2
sampleSheet: /home/hthiele0/snakemake/BU16.bak2
skipDOC: false
smtpPassword: null
smtpPort: 0
smtpServer: null
smtpUsername: null
snakemakeOptions: ' --use-conda --conda-prefix snakemake/miniconda3/envs '
tempDir: /scratch/snakemake/
toolsVersion: true
trim: false
trimmer: fastp
trimmerOptions: -q 5 -l 30 -M 5
verbose: false
workingdir: /scratch/ccg-ngs/fastq/BU16/analyzed3
```

**Comment by katsikora** [comment]
Hi Theo,

does the path '/scratch/snakemake' exist before you call the workflow?

**Comment by sunta3iouxos** [comment]
yes it does,
an update from our HPC team:

> a short addendum: I've taken a look at the sambamba scripts created by snakemake and they work correctly although not as they should:
> 
> MYTEMP=$(mktemp -d "${TMPDIR:-/tmp}"/snakepipes.XXXXXXXXXX)
> ...
> sambamba markdup -t 10 --tmpdir "$MYTEMP/109246"
> ...
> rm -rf "$MYTEMP"
> 
> This results in mktemp creating a temporary directory in /tmp/snakepipes.<random>, since TMPDIR hasn't been set in this context. It's then used (correctly) by sambamba, e.g. "/tmp/snakepipes.5VFa94Xugt/109246..."  as seen in your error message.
> 
> The safest bet is to set MYTEMP or TMPDIR directly in the snakemake job template, thus ensuring that it will be propagated to all generated environments.
> 

Is there a way to do this:
The safest bet is to set MYTEMP or TMPDIR directly in the snakemake job template, thus ensuring that it will be propagated to all generated environments.

Best
Theo

**Comment by katsikora** [comment]
I see, thanks. Can you check the second command in your global log in the output directory? It should read something like this:

TMPDIR=/data/extended/ PYTHONNOUSERSITE=True <MYPATH>snakemake --use-conda --conda-prefix /package/anaconda3/envs/ --dryrun --latency-wait 300 --snakefile <MYPATH>/envs/snakemake/lib/python3.6/site-packages/snakePipes/workflows/DNA-mapping/Snakefile ....

This is where the global variable TMPDIR is set. What does it look like for you?

**Comment by sunta3iouxos** [comment]
there you are:
TMPDIR=/scratch/snakemake/ PYTHONNOUSERSITE=True snakemake/miniconda3/envs/snakePipes/bin/snakemake --use-conda --conda-prefix snakemake/miniconda3/envs --latency-wait 300 --snakefile snakemake/miniconda3/envs/snakePipes/lib/python3.6/site-packages/snakePipes/workflows/WGBS/Snakefile --jobs 12 --directory /scratch/ccg-ngs/fastq/BU16/analyzed3 --configfile /scratch/ccg-ngs/fastq/BU16/analyzed3/WGBS.config.yaml --keep-going --cluster-config /scratch/ccg-ngs/fastq/BU16/analyzed3/WGBS.cluster_config.yaml --cluster 'sbatch --ntasks-per-node=1 -c {threads} -J {rule}.snakemake --mem-per-cpu={cluster.memory} -p MYQUEUE -o cluster_logs/{rule}.%j.out -e cluster_logs/{rule}.%j.err --partition=ccg --account=unikoeln '

it appears that is set correctly.
But the sambamba is not directed there

Best
Theo

**Comment by katsikora** [comment]
Thanks a lot Theo,

I will modify the rules so that the TMPDIR is set at the level of the rule that is using it.

**Comment by sunta3iouxos** [comment]
no worries, thank you, also, for the being active.

**Comment by katsikora** [comment]
Hi Theo, 

the new release 2.1.0 is now available. If you follow the repo you can choose to be notified only about the releases, by the way.

Best,
Katarzyna
