### ISSUE TITLE
suggestion: keep defaults.yaml after updating via conda

### ISSUE THREAD

**Issue by AdrijaK** [maxplanck-ie/snakepipes#612]
When I update snakePipes via `conda update -n snakePipes -c mpi-ie -c bioconda -c conda-forge snakePipes`, I lose the old defaults.yaml settings. 

It would be great if this could be changed (or documentation updated) reminiding that defaults.yaml should be renewed after an update.

**Comment by katsikora** [comment]
This is now implemented in 2.1.0.
