### ISSUE TITLE
request (ChIP-seq 2.0.2): histoneHMM output as bed6

### ISSUE THREAD

**Issue by AdrijaK** [maxplanck-ie/snakepipes#613]
similar to issue https://github.com/maxplanck-ie/snakepipes/issues/611, it would be nice if the output of chromHMM would also be available in bed3 or bed6 format. 

Apart from that, it would be good if all start and end coordinates in .txt.gz  and .filtered.histoneHMM-em-posterior.txt.gz files would consist of numbers in integer format (currently part of coordinates is in scientific number format) : 

```bash
zcat /localhome/inst/usr123/analysis/02_MLL/data/chip-seq/DNA-mapping/histoneHMM/H3K27me3-veh-rep2.filtered.histoneHMM.txt.gz | cut -d$'\t' -f1-3 | tail -n +2 | grep + | head 
```

```
chr1	299251	3e+05
chr1	599251	6e+05
chr1	899251	9e+05
chr1	2999251	3e+06
chr1	5999251	6e+06
chr1	8999251	9e+06
chr1	11999251	1.2e+07
chr1	14999251	1.5e+07
chr1	17999251	1.8e+07
chr1	20999251	2.1e+07
```

**Comment by katsikora** [comment]
This looks ugly, thanks for reporting.
We will think about the bed formats for the future, but not yet in the upcoming release.

**Comment by katsikora** [comment]
This was implemented on the side of pyGenomeTracks.
