### ISSUE TITLE
Updating from snakePipes 2.0.2 to 2.1.0

### ISSUE THREAD

**Issue by AdrijaK** [maxplanck-ie/snakepipes#619]
Hi all, 

I am trying to upgrade to snakePIpes via conda. 

If the previous snakePipes version was 2.0.2, using `conda update -n snakePipes -c mpi-ie -c bioconda -c conda-forge snakePipes` results in getting  snakePipes version 2.0.2 but not higher.

```bash
snakePipes version
```
```
version 2.0.2
```

```bash
conda update --yes -n snakePipes -c mpi-ie -c bioconda -c conda-forge snakePipes
snakePipes version
```

```
version 2.0.2
```

downloading snakePipes in a new environment works with a warning:
```bash
conda create --yes -n snakePipes.2.1.0 -c mpi-ie -c bioconda -c conda-forge snakePipes
conda activate snakePipes.2.1.0 
snakePipes version
```
```
/localhome/inst/usr123/analysis/software/anaconda3/envs/snakePipes.2.1.0/lib/python3.7/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
version 2.1.0 
```

**Comment by katsikora** [comment]
Hi Adrija,

I can reproduce this issue.
This warning is not related to the conda update  issue.

**Comment by katsikora** [comment]
This is probably an issue on the conda side (conda solver). Updating from e.g. snakePipes 2.0.0 or 2.0.2 to 2.1.1 works (tested with conda 4.8.0).
