### ISSUE TITLE
ATAC-seq (and ChIP?) diff peak analysis reversed

### ISSUE THREAD

**Issue by moritzschaefer** [maxplanck-ie/snakepipes#621]
When running an ATAC-seq differential peak analysis, my up- and down- peak annotations are "reversed". 

The documentation (https://snakepipes.readthedocs.io/en/latest/content/workflows/ATAC-seq.htm) states the following:

> For comparison between two conditions, the name you assign to "condition" is not relevant, but rather the order is. The group mentioned first (in the above case "wild-type") would be used as a "control" and the group mentioned later would be used as "test".

I would expect now that if a given gene region is enriched in my test/mutant, it would appear as an UP-region in the analysis.

However, when I compare my WT against my mutant using the following sample sheet:

```
name    condition
WT_1    wt
WT_2    wt
Mutant_1 mutant
Mutant_2 mutant
```

and examine several of the UP peaks in the resulting file AnnotatedResults_MACS2_mutant, I see that they are up in my WT/control rather than in my mutant/test. 

I attached a screenshot of the bigwig-files for one of the peaks. 
![image](https://user-images.githubusercontent.com/2714540/79324459-f501e300-7f0f-11ea-9c08-82966331b8c9.png)

Also when looking at the generated heatmap for the UP peaks, the WT peaks are stronger than the Mutant ones, which is the contrary of what I would have expected:
![CSAW UP cov heatmap](https://user-images.githubusercontent.com/2714540/79325101-dd772a00-7f10-11ea-8454-df1387597202.png)

Is my understanding of the comparison wrong or does the pipeline do something unexpected? Thanks for any help.

**Comment by katsikora** [comment]
Hi Moritz,

which snakePipes version are you running?
We've just fixed a similar issue in 2.1.0.

Best,

Katarzyna

**Comment by moritzschaefer** [comment]
- snakepipes=2.0.2=py_0

That means I did the upgrad 2 days too early, what a pitty. 
Do you recommend to rerun the whole DNA and ATAC-seq pipeline after upgrading again or is it enough to upgrade the differential peak analysis part?

Thank you for the quick response.

**Comment by katsikora** [comment]
I think it will be enough to just rerun the differential binding analysis. 
The original issue was reported here: https://github.com/maxplanck-ie/snakepipes/issues/609

**Comment by moritzschaefer** [comment]
2.1.0 indeed fixes this issue. Thank you!
