### ISSUE TITLE
General question about removal of optical duplicates

### ISSUE THREAD

**Issue by AdrijaK** [maxplanck-ie/snakepipes#627]
Hi all, 

I am a bit confused about which clumpify settings need to be adjusted depending on the sequencer and flow cell type I use. 

**Example 1: NovaSeq 6000 with NOT patterned flowcell:**
- Add only `--optDedupDist 12000`

```bash
preprocessing -i $PWD/rawfastq -o $PWD/preprocessing_optDedup --sampleSheet $PWD/preprocessing_sampleSheet.tsv --optDedupDist 12000
```

**Example 2: NextSeq with NOT patterned flowcell:**
- Add `--optDedupDist 40`

- Add `spany=t adjacent=t` to default settings `--clumpifyOptions dupesubs=0 qin=33 markduplicates=t optical=t`

```bash
preprocessing -i $PWD/rawfastq -o $PWD/preprocessing_optDedup --sampleSheet $PWD/preprocessing_sampleSheet.tsv --optDedupDist 40 --clumpifyOptions 'dupesubs=0 qin=33 markduplicates=t optical=t spany=t adjacent=t' 
```

Is this correct? Thanks!

**Comment by dpryan79** [comment]
We have a typo in the documentation, a value of 0 is only used on non-patterned flowcells (HiSeq 2500 and older).  NovaSeqs always use patterned flow cells (I think all recent Illumina machines use patterned flow cells). Yes, those settings look correct for a NovaSeq and NextSeq, respectively.

**Comment by AdrijaK** [comment]
Thanks, now it is much clearer :)
