### ISSUE TITLE
[Chip-seq] active motif spike-ins

### ISSUE THREAD

**Issue by sunta3iouxos** [maxplanck-ie/snakepipes#630]
Hi all,
Can your pipeline handle any spike in from active motif (drosophila chromatin)?

Best
Theo

**Comment by katsikora** [comment]
Hi Theo,

what would you need your spike in for in the analysis?

If you just want to detect it and obtain bigwig tracks, you can create a hybrid genome (concatenate fasta files from your main organism and your spike in organism) and use that as reference for alignment and the downstream steps.

You can then lookup the tracks on the spike-in organism chromosomes.

**Comment by dpryan79** [comment]
I assume Theo wants the spike-in genome for normalization to allow measuring global signal shifts. That's not directly supported in snakePipes, though you could use snakePipes to perform most of the processing needed for it.

**Comment by sunta3iouxos** [comment]
Hello to you both,
Now my thinking was to be able to use the pipe to
A. map to Dm reference genome, clean up the reads, calculate unique reads number -> fill a table find minimum divide all samples min/samplesUniqueReads
B. do the same for the ex hg19 reference genome, -> create a bedgraph, multiply all reads with the ratio from above.
I believe this is the underling strategy (please correct me if I am wrong) that is not that difficult, also Dm reference genome can be trimmed down to only the necessary so the downtime will be low. and this could be implemented with a --spike TRUE/FALSE statment.

Apart from that what I want to do is use then the normalized bedraph/bigwig to call peaks (narrow or broad) and use the output to call differential binding sites (If you have a hint on how to be done with deeptools please let me know). Usually I am using diffbind (biocinductor R package)



B.

**Comment by dpryan79** [comment]
You're correct on the basic workflow, though I would suggest computing DESeq2 scaling factors and scaling by them instead (you can use multiBamSummary for this). Calculating those and scaling you would have to do manually, but the results could be inserted back into the normal snakePipes workflow.

**Comment by sunta3iouxos** [comment]
Hi again,
would you mind if I continue a bit the normalization steps here? I got 2 questions
A. I got a bit confused. There is a difference between counting mapped reads and finding the ratio and computing the scalingFactor.
using` multiBamSummary bins` I got the following:

Sampling factor for the Dm spike in
> cat Kim_ChIP/multiBamSummar_Ratio_Dm.txt
```
sample  scalingFactor
scr_96H_H3K4me3_261019Dm  3.5566  
scr_96H_H3K4me3_121119Dm  2.8272  
shB_H3K4me3_261019Dm      0.1330     
shB_H3K4me3_121119Dm      0.6682
```
Sampling factor for the Human mapped fragment
> cat Kim_ChIP/multiBamSummar_Ratio.txt
```
sample  scalingFactor
scr_96H_H3K4me3_261019  2.8925
scr_96H_H3K4me3_121119  2.4148
shB_H3K4me3_261019      0.2230
shB_H3K4me3_121119      0.6073
```

if I use the recommended scalling method from active motif (divide sample with lowest total reads to all others) I get:
  12087     scr_96H_H3K4me3_261019Dm    1
  18903     scr_96H_H3K4me3_121119Dm     0.64
535220   shB_H3K4me3_261019Dm             0.02 
  95273      shB_H3K4me3_121119Dm          0.13

B. where should I insert those scaling factors? where exactly in the pipeline, or even better which process will take advantage of that calculation.

**Comment by katsikora** [comment]
Hi Theo,

A)the difference in scaling factors obtained with different methods is expected. MultiBamSummary computes DESeq2-style size factors, see https://www.rdocumentation.org/packages/DESeq2/versions/1.12.3/topics/estimateSizeFactors for details (in this case, genomic bins are used instead of genes).
The third method uses sum of all reads to calculate size factors.

B)Do you intend to run differential binding analysis? This is where you could provide the size factors from deepTools. Or e.g. to bamCoverage to output rescaled coverage tracks.

The difference between the size factors you obtained with Dm vs Hs genomes is not that big.
But, note that you have an order of magnitude difference in size factors for the two sample groups. This might lead to faulty normalization.

We will test an extention to the pipeline to accomodate spikeins. This would most probably require the user to create indices for a hybrid genome and take care of chromosome renaming.

Best,

Katarzyna

**Comment by sunta3iouxos** [comment]
Hi Katarzyna,

Sorry for the late (late-late) reply,
as you noticed the particular examples exhibit "extreme differences between the cases" and in the light of that I finally convinced the lab team to repeat some part of it since any analysis as it stands should be taken with a grain of salt.

A. In case of the ChIP-seq, the second and third method (sum of all reads), appears is the best. I was wondering if the option to exclude the so called "black areas" should be always set (-blackListFileName) or using the -U in samtools view together with the -s 
A1. Also, why Activemotif (also in their published paper) suggests the usage of the division of the raw read counts?
(https://www.activemotif.com/documents/1977.pdf page 4
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0166438#sec012)
can you point advantages or disadvantages? might be also good for future reference if you decide to implement such an option.

B? yes I do 
So I am using the samtools -s , as mentioned above,
or will the bamCoverage --scaleFactor $scale (where scale is the cleaned up reads multiplied by the "size factor"

Thank you again for your time.

Best 
Theo

**Comment by katsikora** [comment]
We have now added support for ChIPseq with spikein in snakePipes 2.2.0.

You can create a hybrid genome with createIndicies, use it in DNA-mapping and later on in ChIPseq with --useSpikeInForNorm.
Alternatively, pass your bam files to ChIP-seq with --fromBAM, specify --useSpikeInForNorm and extention of spikein chromosomes with --spikeinExt. We assume the user names the spikein chromosomes by adding some suffix.

With this implementation we can reproduce https://www.sciencedirect.com/science/article/pii/S2211124714008729 (Orlando et al. 2014) Figure 3E.

**Comment by sunta3iouxos** [comment]
I am impressed. this tool is getting better and better.
Like the swish knife of the basic NGS analysis.
