### ISSUE TITLE
`-v` in ChIP-seq

### ISSUE THREAD

**Issue by LeilyR** [maxplanck-ie/snakepipes#634]
this cmd fails : 
`ChIP-seq -d output/ --fromBAM filtered_bam/ hg38 -v ChIPdict.yaml`
with this error: 
`miniconda3/envs/snkepipes-develop/bin/ChIP-seq: error: unrecognized arguments: ChIPdict.yaml`
However this one works: 
`ChIP-seq -d output/ -v --fromBAM filtered_bam/ hg38 ChIPdict.yaml`

**Comment by katsikora** [comment]
Hi Leily, I'll close this for lack of activity. Please reopen if needed.
