### ISSUE TITLE
Running specific pipelines steps ?

### ISSUE THREAD

**Issue by gtrichard** [maxplanck-ie/snakepipes#636]
Hi everyone,

I have a small question, what is the best way to relaunch specific parts of a pipeline? I looked quickly and didn't find any issue related to this.

I am using the WGBS pipeline and I was running into issues with Mbias and CHH.Mbias (output file was empty, it is something related to how our cluster is working when multiple jobs are trying to access the same fasta file). So I solved the issue by running the commands manually myself. Then I would like to relaunch specific parts of the pipeline, namely the randomCpG, genomeCov, flagstat, produceReport (QC) and everything after (methyl_extract, metilene, etc).

I found how to launch the methyl_extract and metilene by simply removing the MethylDackel folder. But even though some files are missing in QC_metrics (the report for instance), the commands related to the production of the report to do not relaunch themselves.

So is there a way to relaunch specific steps outside of removing files and hopping that snakemake will get what we want to relaunch 😄  ?

Otherwise I will just run them manually, thankfully I don't have so many samples.

Thank you!

**Comment by gtrichard** [comment]
Removing/renaming the .snakemake folder apparently helps snakemake to "force check" the missing files and relaunch the correct steps.

**Comment by katsikora** [comment]
Hi Gautier,

check out snakemake docs for what options you have to run jobs for a dag subset:

https://snakemake.readthedocs.io/en/stable/executing/cli.html

You can pass any of these to <code>--snakemakeOptions</code> in snakePipes.

In general, messing with the DAG is tricky.

Best,

Katarzyna
