### ISSUE TITLE
DNA-mapping error: NO samples found in dir

### ISSUE THREAD

**Issue by dingyingjie123** [maxplanck-ie/snakepipes#653]
Hi, I am trying to run a few single-end fastq samples through DNA-mapping, and I got this probelm:
```
---- This analysis has been done using snakePipes version 2.1.2 ----
SystemExit in line 39 of /home/zhengyandong/anaconda3/envs/snakepipes/lib/python3.7/site-packages/snakePipes/workflows/DNA-mapping/internals.snakefile:
1
  File "/home/zhengyandong/anaconda3/envs/snakepipes/lib/python3.7/site-packages/snakePipes/workflows/DNA-mapping/Snakefile", line 18, in <module>
  File "/home/zhengyandong/anaconda3/envs/snakepipes/lib/python3.7/site-packages/snakePipes/workflows/DNA-mapping/internals.snakefile", line 39, in <module>
  File "/home/zhengyandong/anaconda3/envs/snakepipes/lib/python3.7/_sitebuiltins.py", line 26, in __call__

  Error! NO samples found in dir /data4/zhengyandong/dingyingjie_20200706/ChIP-seq_test/DNA-mapping!!!
```
I am sure the single-end fastq files are in the right location, and it will run successfully if I use paired-end data.
Does anyone have idea about this?

**Comment by katsikora** [comment]
Hi,

do your files have the default extention "_R1.fastq.gz" ?

if not, either rename your files, or provide the '--reads' and '--ext' parameters to the pipeline.

Best,

Katarzyna

**Comment by dingyingjie123** [comment]
It is single-end fastq file and named "SRR10668707.fastq.gz", but DNA-mapping got error about it.
But when I test the DNA-mapping use paired-end file which named "SRR7690243_R1.fastq.gz" and  "SRR7690243_R2.fastq.gz", the DNA mapping run successfully.
Do I hava to rename the single-end file from "SRR10668707.fastq.gz" to "SRR10668707_R1.fastq.gz"?

**Comment by katsikora** [comment]
Yeah that's going to be the fastest fix

**Comment by dingyingjie123** [comment]
Thanks for your kindness.
