### ISSUE TITLE
[WGBS] posibility to only calculate conversion rate

### ISSUE THREAD

**Issue by sunta3iouxos** [maxplanck-ie/snakepipes#666]
Hi again,
is it possible to only calculate conversion rates for the pUC19 and labda phage? these are external DNA added to the main sample (human DNA) to calculate both conversion efficiency (fully methylated pUC19) and false positive conversion rate (unmethylated lambda phage)?

thank you

**Comment by LeilyR** [comment]
We don't directly support spike-ins but you can run the pipeline multiple time and use one reference genome at a time.

**Comment by sunta3iouxos** [comment]
Thank you.
