### ISSUE TITLE
Error when relaunching failed pipelines with snakemake >=5.20

### ISSUE THREAD

**Issue by gtrichard** [maxplanck-ie/snakepipes#667]
I found out that using snakemake 5.20 when relaunching a pipeline with failed jobs will yield the following error :

```
snakepipes ChildIOException:
File/directory is a child to another output: 
```

Using snakemake 5.10.0 for instance fixes the issue.

We are currently testing to solve the issue by changing the SnakePipes conda recipe requirements (with snakemake <= 5.10.0).

**Comment by WardDeb** [comment]
Thanks for reporting,

this is listed in #650 and will be fixed by changing the DAG, downgrading snakemake is a workaround for now.
