### ISSUE TITLE
createIndices --tools 

### ISSUE THREAD

**Issue by LeilyR** [maxplanck-ie/snakepipes#677]
If I add --tools before the gnoeme it fails and it has to be called after the genome. 
e.g.: 
`createIndices -o indices --genomeURL genome.fa --gtfURL /genes.gtf   --tools all  test_genome`
error: 
`snakePipes-2.1.2/bin/createIndices: error: argument --tools: invalid choice: 'test_genome' (choose from 'all', 'bowtie2', 'hisat2', 'bwa', 'bwameth', 'star', 'none')`
however this will work:
`createIndices -o indices --genomeURL genome.fa --gtfURL /genes.gtf   test_genome   --tools all`

**Comment by katsikora** [comment]
Hi Leily, I'll close this for lack of activity. Please reopen if needed.
