### ISSUE TITLE
Cut&Run support for the ChIPseq

### ISSUE THREAD

**Issue by sunta3iouxos** [maxplanck-ie/snakepipes#679]
Hi all,

will your ChIP seq pipeline handle the cut&run chipseq method?

Best
Theo

**Comment by katsikora** [comment]
Hi Theo,

I think the ChIPseq pipeline would handle cut&run data, if you run it with `--useSpikeInForNorm` etc. We also support ChIP-seq analysis without input.

You might want to consider passing some cut&run-related parameters to the "DNA-mapping" pipeline beforehand, e.g. mapq filter, deduplication, or ` --alignerOpts " --dovetail "  `, in case your fragments are very short.
