### ISSUE TITLE
Regarding your Rscript choise for D.A. on Chip-seq

### ISSUE THREAD

**Issue by sunta3iouxos** [maxplanck-ie/snakepipes#683]
Hi again,

I noticed that you are using CSAW to call differential picks. This one uses EdgeR to call the "differences".
Why have choose that one over:
DiffBind or chromstaR  
for diffBind people arguing of high high False Positive Rate but can use both DeSeq2 and EdgeR
chromstaR  uses EdgeR and people saying that has a lower FPR.

Any insights, comments?
Thank you again and again for your time.

Theo

**Comment by katsikora** [comment]
Hi Theo,

we chose CSAW some years ago based on this paper https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4797262/ .
We use TMM normalization from edgeR unless spike-in genome has been added.

EdgeR vs DESeq2 is a separate comparison, there are numerous benchmarks on this. EdgeR is supposed to control FDR somewhat better than DESeq2, but the result depends on the benchmark. Both are popular packages for count data.

ChromstaR looks rather like a peak caller based on HMM, with downstream chromatin state analysis.
We haven't tested it sofar.

We have a peak caller for broad marks in snakePipes - histoneHMM.

Best,

Katarzyna
