### ISSUE TITLE
BWAIndex missing

### ISSUE THREAD

**Issue by KrebsLab** [maxplanck-ie/snakepipes#688]
Thanks for your great work!

The GRCm38_gencode_release19/BWAIndex/genome.fa downloaded from [here](https://snakepipes.readthedocs.io/en/latest/content/setting_up.html#download-premade-indices) results as a broken symlink to /home/ryan/GRCm38_gencode_release19/genome_fasta/genome.fa, should I use the equivalent GRCm38_gencode_release19/genome_fasta/genome.fa as the bwa_index in the organosm configuration file?

**Comment by katsikora** [comment]
Hi There,

thanks for spotting that! 
It should be a relative link to <code>../genome_fasta/genome.fa</code> instead.

We will fix it.

**Comment by katsikora** [comment]
This is now fixed in the develop branch and on the latest doc version https://snakepipes.readthedocs.io/en/latest/content/setting_up.html , now pointing to https://zenodo.org/record/4020455 for GRCm38.

Best,

Katarzyna
