### ISSUE TITLE
Error in `extract_scale_counts` rule in 'Gruen' mode of `scRNAseq`

### ISSUE THREAD

**Issue by genomics-kl** [maxplanck-ie/snakepipes#692]
Hello,

I am getting an error when running `scRNAseq` with `--mode 'Gruen'`. The invocation of the `scRNAseq` wrapper and the relevant lines from the pipeline log and the rule-specific log files are also copied below.

This sample was prepped using the Sagar, ... and Gruen, 2018 (https://pubmed.ncbi.nlm.nih.gov/29605858/) protocol, so the 'Gruen' mode should be appropriate and I did confirm that the barcode and UMI positions on R1 were consistent between the protocol and the pipeline.

The weird thing is that I am getting an error only when I concatenate (`cat`) four technical replicates (single library prep split into 4 separate sequencing libraries with the only difference being the Illumina bar codes). When I run the pipeline for each tech rep separately, there are no errors for any of the four sets of fastqs.

Would appreciate any advice about how to troubleshoot this and can provide any additional information as needed.

Thanks!

**Invocation of `scRNAseq`**
```
scRNAseq -i 'raw_data_merged/' \
    -v \
    -o 'snakepipes_out/' \
    --mode 'Gruen' \
    --clusterConfigFile 'cluster.yaml' \
    --jobs 16 \
    --myKit 'CellSeq384' \
    --DAG \
    'dm6_BDGP6.28.100'
```

Below, `$software_dir` and `$project_dir` were manually pasted in to avoid showing the full path publicly.

**Relevant portion of `scRNAseq_run-1.log`:**
```
[Tue Sep  8 18:33:29 2020]
rule extract_scale_counts:
    input: Counts/Lib_merged_L000.raw_counts.txt
    output: Counts/Lib_merged_L000.corrected.txt, Counts/Lib_merged_L000.umis.txt, Counts/Lib_merged_L000.reads.txt
    log: Counts/logs/extract_counts.Lib_merged_L000.out, Counts/logs/extract_counts.Lib_merged_L000.err
    jobid: 10
    wildcards: sample=Lib_merged_L000


        $software_dir/miniconda3/envs/snakePipes-2.1.2/lib/python3.8/site-packages/snakePipes/shared/tools/correct_sc_counts.py --umiLength 6             Counts/Lib_merged_L000.raw_counts.txt Counts/Lib_merged_L000.reads.txt Counts/Lib_merged_L000.umis.txt Counts/Lib_merged_L000.corrected.txt > Counts/logs/extract_counts.Lib_merged_L000.out 2> Counts/logs/extract_counts.Lib_merged_L000.err

Submitted job 10 with external jobid '1037188.master.cm.cluster'.
[Tue Sep  8 18:34:08 2020]
Finished job 23.
24 of 34 steps (71%) done
[Tue Sep  8 18:53:19 2020]
Error in rule extract_scale_counts:
    jobid: 10
    output: Counts/Lib_merged_L000.corrected.txt, Counts/Lib_merged_L000.umis.txt, Counts/Lib_merged_L000.reads.txt
    log: Counts/logs/extract_counts.Lib_merged_L000.out, Counts/logs/extract_counts.Lib_merged_L000.err (check log file(s) for error message)
    conda-env: $software_dir/miniconda3/envs/76096405dbc0603b964faf027efca84b
    shell:

        $software_dir/miniconda3/envs/snakePipes-2.1.2/lib/python3.8/site-packages/snakePipes/shared/tools/correct_sc_counts.py --umiLength 6             Counts/Lib_merged_L000.raw_counts.txt Counts/Lib_merged_L000.reads.txt Counts/Lib_merged_L000.umis.txt Counts/Lib_merged_L000.corrected.txt > Counts/logs/extract_counts.Lib_merged_L000.out 2> Counts/logs/extract_counts.Lib_merged_L000.err

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    cluster_jobid: 1037188.master.cm.cluster

Error executing rule extract_scale_counts on cluster (jobid: 10, external: 1037188.master.cm.cluster, jobscript: $project_dir/snakepipes_gruen_merge_techreps/snakepipes_out/.snakemake/tmp.ohdgu2ia/snakejob.extract_scale_counts.10.sh). For error details see the cluster log and the log files of the involved rule(s).
Job failed, going on with independent jobs.
Exiting because a job execution failed. Look above for error message
Complete log: $project_dir/snakepipes_gruen_merge_techreps/snakepipes_out/.snakemake/log/2020-09-08T160509.199989.snakemake.log

```

**Relevant portion of `Counts/logs/extract_counts.Lib_merged_L000.out`:**
```
Traceback (most recent call last):
  File "$software_dir/miniconda3/envs/snakePipes-2.1.2/lib/python3.8/site-packages/snakePipes/shared/tools/correct_sc_counts.py", line 64, in <module>
    CorrectedCountsFile.write("\t{}".format(abs(-math.log(1.0 - float(cnt) / float(maxUMIs)) * maxUMIs)))  # The abs() prevents -0.0
ValueError: math domain error
```

**Comment by katsikora** [comment]
Hi,

in this paper, I believe they used 192 cell barcodes, not 384.
In that case, it would be correct to run the pipeline with `--myKit CellSeq192` . Unless you used 384 barcodes to generate your data. 

There is also a difference in cell barcode and UMI length between CellSeq192 and CellSeq384. The protocol in the paper uses 6nt for each, which again works with CellSeq192, while CellSeq384 is compatible with 7nt, each.

Can you confirm which is correct for your data?

**Comment by genomics-kl** [comment]
> Hi,
> 
> in this paper, I believe they used 192 cell barcodes, not 384.
> In that case, it would be correct to run the pipeline with `--myKit CellSeq192` . Unless you used 384 barcodes to generate your data.
> 
> There is also a difference in cell barcode and UMI length between CellSeq192 and CellSeq384. The protocol in the paper uses 6nt for each, which again works with CellSeq192, while CellSeq384 is compatible with 7nt, each.
> 
> Can you confirm which is correct for your data?

Sorry, I think I should be using 'CellSeq192' then. The collaborator told me they used the attached protocol which describes 6nt cell barcode and UMIs. However, the documentation seems to suggest that '--myKit' is only used for '--mode STARsolo'. Since I am running '--mode Gruen', does this parameter still matter?

**Comment by katsikora** [comment]
Hi again,

ah yes, sorry, my bad, `myKit` is indeed ignored with mode Gruen.

Is `cellBarcodeFile` and `cellBarcodePattern` in your scRNA-seq.config.yaml in the output folder defined?

**Comment by genomics-kl** [comment]
Yes, they are. See below. Note I have manually added in '$software_dir' as above.

`grep 'cellBarcode' scRNAseq.config.yaml`

```
cellBarcodeFile: $software_dir/miniconda3/envs/snakePipes-2.1.2/lib/python3.8/site-packages/snakePipes/workflows/scRNAseq/celseq_barcodes.192.txt
cellBarcodePattern: NNNNNNXXXXXX
```

**Comment by katsikora** [comment]
Ok, this looks good - you're setup for 192 barcodes and BC/UMI length of 6.
You can take out  `--myKit` from your command.

From the error you got, it looks like you received more than or exactly 4^6 counts for some gene - which is more than or exactly the maximum number of unique UMIs, given the UMI length of 6. This results in trying to get a log(0) or log of a negative number - hence the error.

This part of the code is somewhat buggy, as it will try to produce a log of a negative number  if you hit the UMI max number per gene.

<code>if(cnt >= maxUMIs):
                maxUMIs -= 0.5
            CorrectedCountsFile.write("\t{}".format(abs(-math.log(1.0 - float(cnt) / float(maxUMIs)) * maxUMIs))) </code>


We are going to deprecate mode `Gruen` towards the end of 2020/beginning 2021.

I'd propose you to run snakePipes with `--mode STARsolo --myKit CellSeq192`, this should be smooth. The resulting count matrices in "10X style"  you can further analyse with RaceID, if you prefer it over Seurat. Counting in mode STARsolo is less buggy and more reliable.

Otherwise, try running the technical replicates separately with `--mode Gruen`, and merge the corrected count matrices.

**Comment by genomics-kl** [comment]
Thanks for your suggestions! I ran STARsolo mode successfully for both the unmerged and merged fastq files.

For merging the Gruen mode count matrices, there is no good way to remove UMI duplicates created by merging/summing the counts across the four tech rep libraries, right?

**Comment by katsikora** [comment]
Hi,

glad to hear STARsolo worked for you.

Raw counts are before UMI deduplication and Poisson correction for hitting the UMI limit and would be a good choice for merging technical replicates.
