### ISSUE TITLE
snp_split error in single-end allelic RNA-seq

### ISSUE THREAD

**Issue by GuidoBarzaghi** [maxplanck-ie/snakepipes#698]
Good evening,

I am encountering the following error:

`Error in rule snp_split:
    jobid: 82
    output: STAR/C14rep2.sortedByName.bam, allelic_bams/C14rep2.allele_flagged.bam, allelic_bams/C14rep2.genome1.bam, allelic_bams/C14rep2.genome2.bam, allelic_bams/C14rep2.unassigned.
    log: allelic_bams/logs/C14rep2.snp_split.log (check log file(s) for error message)
    conda-env: /g/krebs/barzaghi/utilies/miniconda3/envs/4c0f0ebc56a8061115ec631154fe3e4a
    shell:
        SNPsplit  -o allelic_bams --snp_file snp_genome/all_CAST_EiJ_SNPs_C57BL_6NJ_reference.based_on_GRCm38_release93.txt STAR/C14rep2.bam 2> allelic_bams/logs/C14rep2.snp_split.log
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    cluster_jobid: Submitted batch job 3733030`

Accordingly, none of the output files are produced although the snp_split process appears to have succeeded based on the *.snp_split.log:

_____________
...
Processed 98000000 lines so far
Processed 99000000 lines so far

Allele-specific single-end sorting report
=========================================
Read alignments processed in total:             99140223
Reads were unassignable:                        81397239 (82.10%)
Reads were specific for genome 1:               9679144 (9.76%)
Reads were specific for genome 2:               8008194 (8.08%)
Reads contained conflicting SNP information:    55646 (0.06)

Sorting finished successfully

SNPsplit processing finished...
_____________
Could it be a problem of allocated memory? At the moment I am allowing 20G for the snp_split process.

**Comment by vivekbhr** [comment]
Hi @GuidoBarzaghi . Sometime memory can indeed become a problem. I usually assign 30G for mouse genome samples with decent depth (30Mil or more). If the sorting seems to be done, do you see any intermediate BAM files in the output folder?

Best,
Vivek

**Comment by GuidoBarzaghi** [comment]
Thanks for your reply @vivekbhr. I allocated 35G but that didn't solve the problem. Following is the error message to the latest execution of snp_split for one of my samples:

----
MissingOutputException in line 21 of /home/barzaghi/miniconda3/envs/snakePipes/lib/python3.8/site-packages/snakePipes/shared/rules/SNPsplit.snakefile:
Job completed successfully, but some output files are missing. Missing files after 1800 seconds:
STAR/C14rep3.sortedByName.bam
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
  File "/home/barzaghi/miniconda3/envs/snakePipes/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 544, in handle_job_success
  File "/home/barzaghi/miniconda3/envs/snakePipes/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 225, in handle_job_success
Removing output files of failed job snp_split since they might be corrupted:
allelic_bams/C14rep3.allele_flagged.bam, allelic_bams/C14rep3.genome1.bam, allelic_bams/C14rep3.genome2.bam, allelic_bams/C14rep3.unassigned.bam
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
----

It seems to me like the latency is not a likely cause since I increased it to 1800 sec (6x the default) without success.

The intermediate bam files are deleted from the STAR folder according to the error message above and only log files and reports are left in the allelic_bams folder.

**Comment by vivekbhr** [comment]
I checked this and it seems that the allele-splitting tool doesn't produce the `sortedbyName.bam` file in the single-end mode, but the workflow was still checking for it (even though it doesn't need it). 

We will fix it asap..

**Comment by vivekbhr** [comment]
@GuidoBarzaghi I just pushed a fix for this in the develop branch but haven't tested it on my side. If you could update your snakepipes from develop and run it without error that would be great.

**Comment by GuidoBarzaghi** [comment]
Great! Can't wait to test. Is there a way of updating from dev without having to reinstall the whole thing?

**Comment by vivekbhr** [comment]
yes, that would be `pip install git+https://github.com/maxplanck-ie/snakepipes.git@develop` from your current snakePipes env.

**Comment by GuidoBarzaghi** [comment]
Happy to report it worked! I have only one last question: how should I set the sampleSheet for allelic workflows? I tried 

name    condition
C14rep1 WT
C14rep2 WT
C14rep3 WT

name    condition
C14rep1_genome1 R
C14rep2_genome1 R
C14rep3_genome1 R
C14rep1_genome2 A
C14rep2_genome2 A
C14rep3_genome2 A

but neither worked..

**Comment by vivekbhr** [comment]
Great! :+1: 

For DE testing, do you want to test how 2 alleles respond between conditions (control vs treatment)? or simply the difference between 2 alleles in a single condition? For RNA-seq, we have it currently set-up for control vs treatment kind of situation (ChIP-seq allows both), and the first sample sheet would work (if you have 2 or more conditions). 

If you only have one condition you might have to run DESeq on your own from the count tables. In the count table, you will find 3 counts for each condition (`_all`, `_genome1`, `_genome2`), and you can compare `_genome1` with `_genome2` in your case

**Comment by vivekbhr** [comment]
Just realized that another workaround could be to ask for normal (not allelic) workflow from snakePipes and use the second samplesheet design :thinking:  this might actually work

**Comment by GuidoBarzaghi** [comment]
I just want to test for differences between alleles, no conditions. I'm confused: shouldn't it be sufficient to match the values from the name column in the sampleSheet to the columns names in the count tables (which is what I tried in the second case)? And wouldn't the workaround you suggested make the workflow process the data not in an allele-resolved fashion (thus skipping the snp_split part)? 
Do you think I could maybe change a few lines of code to allow for something like my second attempt of sampleSheet to work or am I oversimplifying?

**Comment by vivekbhr** [comment]
@GuidoBarzaghi I thought maybe the workflow could pick it up from the DESeq step if you run it in "alignment" mode in the same folder, but maybe it won't work.

An alternative would be to simply run our [DESeq2 R wrapper](https://github.com/maxplanck-ie/snakepipes/blob/master/snakePipes/shared/rscripts/DESeq2.R) with the second samplesheet. If you do snakePipes info, you can locate the R wrapper somewhere in `snakepipes/shared/rscripts/DEseq2.R`.

**Comment by GuidoBarzaghi** [comment]
For the moment I can run the DESeq2 wrapper independently as you suggested. However this seems to go against the principle of full automation that snakePipes otherwise provides so successfully. Is there a plan to implement this in the foreseeable future?

**Comment by vivekbhr** [comment]
I think we can add that :+1:
