### ISSUE TITLE
DNA mapping for single-end

### ISSUE THREAD

**Issue by pastaxingxin** [maxplanck-ie/snakepipes#703]
I want to do DNA mapping for single-end data.
My command line is this:
DNA-mapping -i  ./chip -o ./chip-out --mapq 5 -j 10 --dedup GRCh38_relase99.
My ./chip directory is like this:
![image](https://user-images.githubusercontent.com/17949301/95905531-fb5e0400-0d66-11eb-8958-419b69df571a.png)

According to your document. I don't know how to change yaml file for single-end data. So I used defaults yaml file. Expectedly, I got error messages like this;
![image](https://user-images.githubusercontent.com/17949301/95905827-51cb4280-0d67-11eb-820b-a71906965b24.png)

I suppose, your script could only handle paired-end data? Could you provide me with solutions to the situation?
Thank you in advance.

**Comment by LeilyR** [comment]
It can handle single end data. Please consider one of the following options:  
1. giving your files  a compatible name 
2. use a customized config yaml 
3. use --reads. 
The warning tells you exactly what you need to do.

**Comment by pastaxingxin** [comment]
Yes, the point is here. I tried a customized config yaml or --reads. However, your document doesn't mention how to change the yaml or --reads for single-end data. So I tried many times, such as make reads: [ , ], [_1], but all tries failed. Then I pinpoint the parserCommon.py and common_functions.py. I have read them throughly, so I haven't resolved the problem.

**Comment by katsikora** [comment]
Hi Pastaxingxin,

for single end reads, I'd recommend renaming your files to something like sample_R1.fastq.gz or sample_1.fastq.gz and modifying the `reads` value in the config to ['_1','_2'] in the latter case.

We don't support empty string in this entry (such as would be the case for sample.fastq.gz).

Best,

Katarzyna
