### ISSUE TITLE
DNA alignment with "bwa" aligner does not make use of alignment options

### ISSUE THREAD

**Issue by moritzschaefer** [maxplanck-ie/snakepipes#704]
I just had a look into the DNA-aligner snakefile for BWA and noticed that the parameter for custom BWA-arguments (alignerOpts) is not passed to the call of bwa-command: https://github.com/maxplanck-ie/snakepipes/blob/master/snakePipes/shared/rules/bwa.snakefile
Am I overseeing something? (If not, I can quickly do a PR if you will)

Besides, I wanted to ask if there is a specific reason that STAR is not supported for DNA-mapping. There are several publications claiming that (especially for paired-end sequencing and repetitive-elements) STAR is among the best aligners, also for DNA-mapping (e.g. https://doi.org/10.1186/s13100-019-0192-1)

**Comment by katsikora** [comment]
Hi Moritzschaefer,

Concerning STAR, we don't haven't really a use case for DNA mapping sofar. The paper you attached showcases mapping of repeat-derived reads with subsequent quantification. This looks more like an RNA-seq application - and we have this implemented in the noncoding-RNA-seq worflow (STAR + TEtranscripts).

Let me know if you had some other application in mind.

Best,

Katarzyna

**Comment by moritzschaefer** [comment]
Hey katsikora,

we are looking at ATAC-seq and cut&tag data while having transposable elements and other repetitive elements in the DNA in mind. 

I'm using bwa for now, which also seems to perform reasonably for this scenario.

I close this issue since the original issue has been resolved in the PR (thanks!) **.**
