### ISSUE TITLE
problem of snakePipes createEnvs 

### ISSUE THREAD

**Issue by smartgamer** [maxplanck-ie/snakepipes#715]
When I ran 'snakePipes createEnvs', I found there are many conda environments generated with some random long names. And I can't remove then using conda remove --name. How to get rid of these annoying environments?

**Comment by katsikora** [comment]
Hi there,

you need these environments to run snakePipes.
You can get more information about them with `snakePipes envInfo`.

Best,

Katarzyna

**Comment by smartgamer** [comment]
Thank you

Charles

On Oct 23, 2020, at 2:40 AM, Katarzyna Sikora <notifications@github.com> wrote:

﻿

Hi there,

you need these environments to run snakePipes.
You can get more information about them with snakePipes envInfo.

Best,

Katarzyna

**Comment by smartgamer** [comment]
What if I want to remove those environments eventually after using them? How to remove them?

Charles

On Oct 23, 2020, at 9:25 AM, Z Ji <htchd7ji@live.com> wrote:

﻿ Thank you

Charles

On Oct 23, 2020, at 2:40 AM, Katarzyna Sikora <notifications@github.com> wrote:

﻿

Hi there,

you need these environments to run snakePipes.
You can get more information about them with snakePipes envInfo.

Best,

Katarzyna

**Comment by smartgamer** [comment]
Hi Katarzyna,

Thanks for your quick response. But I couldn't find information about how to delete those environments generated by snakePipes. I tried conda remove, but it didn't work.

Best,
Charles

**Comment by katsikora** [comment]
Hi Charles,

did you try 'conda remove --prefix ' and giving on of the paths returned by 'snakePipes envInfo' as prefix path?

Best,

Katarzyna

**Comment by smartgamer** [comment]
Thank you
