### ISSUE TITLE
PeriodicWildcardError in line 7 of sambamba.snakefile

### ISSUE THREAD

**Issue by mvcakir** [maxplanck-ie/snakepipes#717]
Hello,

I'm having a strange error with the DNA-mapping. 

PeriodicWildcardError in line 7 of /home/cakir/miniconda3/envs/snakepipes_STaRAD/lib/python3.6/site-packages/snakePipes/shared/rules/sambamba.snakefile:
The value .sorted in wildcard sample is periodically repeated (SRR793064.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted.sorted). This would lead to an infinite recursion. To avoid this, e.g. restrict the wildcards in this rule to certain values.
Error: snakemake returned an error code of 1, so processing is incomplete!

I'm calling the pipeline from command line as follows:

$ DNA-mapping -i data/raw_data -o mapped --local --DAG GRCh38.v35

I already created the indices for genome GRCh38.v35, and I checked if indices are really created fine.
My samples are as follows:
SRR792992_R1.fastq.gz
SRR792992_R2.fastq.gz
SRR793038_R1.fastq.gz
SRR793038_R2.fastq.gz
SRR793056_R1.fastq.gz
SRR793056_R2.fastq.gz
SRR793064_R1.fastq.gz
SRR793064_R2.fastq.gz
SRR793105_R1.fastq.gz
SRR793105_R2.fastq.gz
SRR816276_R1.fastq.gz
SRR816276_R2.fastq.gz
SRR816277_R1.fastq.gz
SRR816277_R2.fastq.gz

I'm using bwa as mapper. And cutadapt as trimmer. These options I arranged in defaulst.yaml

################################################################################
## General/Snakemake parameters, only used/set by wrapper or in Snakemake cmdl, but not in Snakefile
pipeline: dna-mapping
outdir:
configFile:
clusterConfigFile:
local: False
maxJobs: 5
## directory with fastq files
indir:
## Value can be also path to your own genome config file!
genome:
## FASTQ file extension (default: ".fastq.gz")
ext: '.fastq.gz'
## paired-end read name extension (default: ['_R1', "_R2"])
reads: [_R1, _R2]
## mapping mode
mode: mapping
aligner: bwa
## Number of reads to downsample from each FASTQ file
downsample:
## Options for trimming
trim: true
trimmer: cutadapt
trimmerOptions:
## Bin size of output files in bigWig format
bwBinSize: 25
## Run FASTQC read quality control
fastqc: true
## Run computeGCBias quality control
GCBias: false
## Retain only de-duplicated reads/read pairs
dedup: false
## Retain only reads with at least the given mapping quality
mapq: 0
## Retain only reads mapping in proper pairs
properPairs: false
## (default "--fr" is appropriate for Illumina sequencing)
mateOrientation: --fr
## other Bowtie2 stuff
insertSizeMax: 1000
alignerOpts:
plotFormat: pdf
UMIBarcode: False
bcPattern: NNNNCCCCCCCC #default: 4 base umi barcode, 8 base cell barcode (eg. RELACS barcode)
UMIDedup: False
UMIDedupSep: "_"
UMIDedupOpts:
## Median/mean fragment length, only relevant for single-end data (default: 200)
fragmentLength: 200
qualimap: false
verbose: false

**Comment by katsikora** [comment]
Hi Mvcakir,

I cannot reproduce your error on our test data with snakePipes version 2.3.1.
Your reads and config look good.

Is your output folder empty to start with?

Best,

Katarzyna

**Comment by mvcakir** [comment]
Dear Katarzyna,

Thanks for fast response.
Yes output folder is empty. 

Just to be sure I updated the tool using:
conda update -c mpi-ie -c conda-forge -c bioconda --prune snakePipes

Now I have an unrelated error:
---- This analysis has been done using snakePipes version 2.0.2 ----
Traceback (most recent call last):
  File ".../lib/python3.6/site-packages/snakemake/__init__.py", line 743, in snakemake
    keepincomplete=keep_incomplete,
  File ".../lib/python3.6/site-packages/snakemake/workflow.py", line 666, in execute
    or delete_temp_output,
  File ".../lib/python3.6/site-packages/snakemake/persistence.py", line 72, in __init__
    os.makedirs(d, exist_ok=True)
  File ".../lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/.../lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File ".../lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/package'
Error: snakemake returned an error code of 1, so processing is incomplete!

And surprisingly it claims that analysis is done with "snakePipes version 2.0.2" even though I have the latest version.

**Comment by katsikora** [comment]
Dear Mvcakir,

perhaps you can unistall snakePipes as you have it and install a specific version with e.g.
`conda create -n snakePipes -c mpi-ie -c conda-forge -c bioconda snakePipes==2.3.1` .

The conda solver is sometimes giving issues and picking up outdated snakePipes version instead of the latest one.
After creating you conda env with snakePipes in it, you're going to need to `snakePipes config` and `snakePipes createEnvs` as described here https://snakepipes.readthedocs.io/en/latest/content/setting_up.html#modify-global-options .

Hope this helps,

Best,

Katarzyna

**Comment by mvcakir** [comment]
Dear Katarzyna,

I tried that and it worked up to some point. Now the pipeline works till bwa mapping, but somehow quits with an error message at mapping:

Error in rule bwa:
    jobid: 100
    output: bwa/SRR793056.bwa_summary.txt, bwa/SRR793056.sorted.bam
    log: bwa/logs/SRR793056.sort.log (check log file(s) for error message)
    conda-env: /home/cakir/miniconda3/envs/71c7ce96825f9a760b14d42464efde55
    shell:
        
            TMPDIR=/data/extended/
            MYTEMP=$(mktemp -d ${TMPDIR:-/tmp}/snakepipes.XXXXXXXXXX);
            bwa mem             -t 5             -R '@RG\tID:SRR793056\tDS:SRR793056\tPL:ILLUMINA\tSM:SRR793056'              /home/cakir/WORK/test/reference/indices/BWAIndex/genome.fa FASTQ_Cutadapt/SRR793056_R1.fastq.gz FASTQ_Cutadapt/SRR793056_R2.fastq.gz |             samtools view -Sb - |             samtools sort -m 2G -@ 2 -O bam - > bwa/SRR793056.sorted.bam 2> bwa/logs/SRR793056.sort.log;
            rm -rf $MYTEMP
            samtools flagstat bwa/SRR793056.sorted.bam > bwa/SRR793056.bwa_summary.txt
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Job failed, going on with independent jobs.
Exiting because a job execution failed. Look above for error message



The strange thing is when I try the commands separately they work, i.e. I can map and sort the reads the same way as in the command. I have no idea why it quits wit and error.

**Comment by mvcakir** [comment]
Ok the issue is solved.
The firs problem was as Katarzyna pointed with conda solver and snakepipes version. 
The second problem was with the python version, there was a conflict between python version and the version needed by snakepipes. Now I have 3.8.3. and it works fine.
The last problem was mistake in the tempDir (check 'snakePipes config' carefully).

All these problems generated different and seemingly unrelated errors to the source of problem, e.g. the first problem generated errors with sambamba package. 

Anyway, thanks a lot dear Katarzyna for your time and help.
