### ISSUE TITLE
HiC error

### ISSUE THREAD

**Issue by pastaxingxin** [maxplanck-ie/snakepipes#718]
Hi, I ran your HiC analysis pipeline.
At first, everything is going well. However, after 8 hours, some error messages produced:
"Error in rule build_matrix:
    jobid: 5
    output: HiC_matrices/k562-hic-ENCFF_bs10kb.cool, HiC_matrices/QCplots/k562-hic-ENCFF_QC/QC.log
    log: HiC_matrices/logs/k562-hic-ENCFF_bs10kb.out, HiC_matrices/logs/k562-hic-ENCFF_bs10kb.err (check log file(s) for error message)
    conda-env: /usr/local/anaconda3/envs/6d724933d4b9cbee3b1cecc928c0a087
    shell:
        hicBuildMatrix -s BWA/k562-hic-ENCFF_1.bam BWA/k562-hic-ENCFF_2.bam -bs 10000 -rs DpnII.bed --restrictionSequence GATC --danglingSequence GATC --minDistance
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    cluster_jobid: Job <413097> is submitted to queue <huang>.
When I checked HiC_matrices/logs/k562-hic-ENCFF_bs10kb.err. It's like this
"
![image](https://user-images.githubusercontent.com/17949301/97744336-688acc80-1abd-11eb-8156-ec586135c661.png)
"
I could not get any clue from this file. Do you have any suggestions for this error?
Thank you in advance.

**Comment by LeilyR** [comment]
Hi, 
We have noticed that error before. Unfortunately this is a bug in hicexporer, a tool which is used to build matrices, would you mind to use an older version snakepipes for now which relies on an older version of hicexplorer, before introducing this bug. We are working on solving this issue for the next version.

**Comment by pastaxingxin** [comment]
Thank you for your quick reply. Which snakepipes version I could use?

**Comment by LeilyR** [comment]
2.0.2 should be fine.

**Comment by pastaxingxin** [comment]
Thanks. I will check it out and see what happens.

**Comment by pastaxingxin** [comment]
Hello, it doesn't work as well. 
Here is what I did: I simply upgraded hicexplorer from 3.5.2 to the 3.5.3 in the existing snakePipes 2.3.0 environment. After running the command, I got almost the same error. So I am assuming I must downgrade hicexplorer 3.4 to avoid the error?

**Comment by pastaxingxin** [comment]
or if I just used your indices files (https://zenodo.org/record/2650763#.X50LUYhKhPY), then I could avoid this problem?

**Comment by pastaxingxin** [comment]
Hello, now the error becomes this:

![image](https://user-images.githubusercontent.com/17949301/97806899-f4bb0200-1c2b-11eb-922c-b0863c84483f.png)
![image](https://user-images.githubusercontent.com/17949301/97806907-fd133d00-1c2b-11eb-9bd9-cbf076819448.png)
Why I got this message? How to resolve it?

**Comment by LeilyR** [comment]
Indeed. This bug has been introduced in hicexplorer 3.5 so , if you use older version of snakepipes which is based on hicexplorer 3.4 it should be fine.

**Comment by katsikora** [comment]
Hi Leily and Pastaxingxin,

we've recently released snakePipes 2.3.1, which is using the latest hicexplorer version. Is that bug still persisting in this snakePipes/HiCexplorer version?

Best,

Katarzyna

**Comment by LeilyR** [comment]
Unfortunately it seems that the bug is still available in hicexplorer3.5.3. However it only fails if no restriction site is found on a chromosome. So one thing I would highly recommend you is to to be sure that you are giving it the right restriction enzyme. I have tried the pipeline on several test data and it actually worked fine on most of them and only failed on one of them where there was a contig with no cut site. 
My suggestion for now is to first be sure that you use the right restriction enzyme, second, use an older version of snakepipes wich is based on the hicexplorer3.4 until the bug is fixed.

**Comment by pastaxingxin** [comment]
Thanks for your suggestions. I'm sure it's the correct restriction enzyme. 
Is it okay if I insist on using snakePipes 2.3.0, but just downgrade hicexplorer from 3.5.3 to 3.4.0? 
Because I don't have some root permission, so it's will be difficult for me to install snakepipes and modify yaml setting.

**Comment by LeilyR** [comment]
I am afraid that, it is not enough. There is a slight change in the required arguments of hicBuildMatrix which you need to take care of.  However, I do not think that you need root permission to install another version of snakepipes. Please have a look at our documentation for the installation via conda and do not hesitate to ask questions if there was anything unclear.
Moreover, the bug of hicexplorer has been already fixed, is now available under its develop branch and soon to be released. So I can imagine that we will hopefully update the snakepipes before end of the week offering the new version of hicexplorer.

**Comment by pastaxingxin** [comment]
Thanks. I have some questions about hicBuildMatrix. 
Which RFResolution parameter I should choose, true or false?
I have two input bams, which are ~100G in total, however, I have limited memory, which is about 250G. Could you give me any suggestions to reduce memory usage?

**Comment by LeilyR** [comment]
If you generate low resolution matrices (large fixed bin size), you will indeed save memory comparing to restriction fragment size resolution. I do not know any number by heart though.  However if you have enough coverage and look for tads you may try something not so low.

**Comment by pastaxingxin** [comment]
Thank you! The problem resolved.
