### ISSUE TITLE
scRNAseq - changes to defaults.yaml STARsoloCoords have no effect

### ISSUE THREAD

**Issue by powellhd** [maxplanck-ie/snakepipes#722]
Since my UMIs are 8-mers I need to change the `STARsolo` `--soloUMIlen` setting from 7 to 8. This can be done by changing the `STARsoloCoords` from the default `["1","7","8","7"]` to `["1","8","8","8"]`, however this has no effect on the `--soloUMIlen` parameter passed to `STARsolo` and stays `--soloUMIlen 7`. I therefore getting the following error from `STARsolo`

EXITING because of FATAL ERROR in input CB whitelist file: scRNAseq/celseq_barcodes.384.1col.txt the total length of barcode sequence is 8 not equal to expected 0

**Comment by powellhd** [comment]
@dpryan79

**Comment by LeilyR** [comment]
From what I can see in the code, it should work. Could you please send us your command line and if possible running it with -v and send us the script which has been used for the start solo rule too.

**Comment by powellhd** [comment]
What do you mean by:
"Also from the error message you have shared, I wonder if the barcode length needs to be checked in your fastq files."

My commandline is:
`scRNAseq  -v --DAG --local --myKit CellSeq384 -i . -o ./output2 mm10`

Output:
--- Config ---------------------------------------------------------------------
config file: /home/ubuntu/MOUNText/fastq/output2/scRNAseq.config.yaml
BCwhiteList: None
STARsoloCoords: ['1', '8', '8', '8']
UMIBarcode: False
UMIDedup: False
UMIDedupOpts: --paired
UMIDedupSep: _
alevinLibraryType: ISR
alignerOptions:
baseDir: /home/ubuntu/bin/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes
bcPattern: NNNNCCCCCCCCC
bwBinSize: 10
cellBarcodeFile: /home/ubuntu/bin/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/workflows/scRNAseq/celseq_barcodes.192.txt
cellBarcodePattern: NNNNNNXXXXXX
cellFilterMetric: gene_universe
cellNames: None
clusterConfig: shared/cluster.yaml
clusterConfigFile: None
configFile: None
configMode: manual
createDAG: True
dnaContam: False
downsample: None
emailAddress: None
emailSender: None
expectCells: None
ext: .fastq.gz
filterGTF: -v -P 'decay|pseudogene'
genome: mm10
indir: /home/ubuntu/MOUNText/fastq
keepTemp: False
libraryType: 1
local: True
maxJobs: 5
mode: STARsolo
myKit: CellSeq384
oldConfig: None
onlySSL: False
organismsDir: /home/ubuntu/bin/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/shared/organisms
outdir: /home/ubuntu/MOUNText/fastq/output2
pipeline: scrna-seq
plotFormat: pdf
prepProtocol: celseq2
readLengthFrx: 0.2
reads: ['_R1', '_R2']
salmonIndexOptions: --type puff -k 31
skipRaceID: False
skipVelocyto: False
smtpPassword: None
smtpPort: 0
smtpServer: None
smtpUsername: None
snakemakeOptions:  --use-conda --conda-prefix /home/ubuntu/bin/miniconda3/envs
splitLib: False
tempDir: /tmp
toolsVersion: True
trim: False
trimmer: cutadapt
trimmerOptions: -a A{'30'}
verbose: True
workingdir: /home/ubuntu/MOUNText/fastq/output2
--------------------------------------------------------------------------------


--- Genome ---------------------------------------------------------------------
config file: /home/ubuntu/bin/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/shared/organisms/mm10.yaml
blacklist_bed: /home/ubuntu/MOUNText/data/snakePipes/GRCm38_gencode_release19/DKFZ/GRCm38_General_readAttractingRegions.UseThisOne.bed
bowtie2_index: /home/ubuntu/MOUNText/data/snakePipes/GRCm38_gencode_release19/BowtieIndex/genome
bwa_index: /home/ubuntu/MOUNText/data/snakePipes/GRCm38_gencode_release19/BWAindex/genome.fa
bwameth_index: /home/ubuntu/MOUNText/data/snakePipes/GRCm38_gencode_release19/BWAmethIndex/genome.fa
extended_coding_regions_gtf: /home/ubuntu/MOUNText/data/snakePipes/GRCm38_gencode_release19/annotation/genes.slop.gtf
genes_bed: /home/ubuntu/MOUNText/data/snakePipes/GRCm38_gencode_release19/annotation/genes.bed
genes_gtf: /home/ubuntu/MOUNText/data/snakePipes/GRCm38_gencode_release19/annotation/genes.gtf
genome_2bit: /home/ubuntu/MOUNText/data/snakePipes/GRCm38_gencode_release19/genome_fasta/genome.2bit
genome_fasta: /home/ubuntu/MOUNText/data/snakePipes/GRCm38_gencode_release19/genome_fasta/genome.fa
genome_index: /home/ubuntu/MOUNText/data/snakePipes/GRCm38_gencode_release19/genome_fasta/genome.fa.fai
genome_size: 2652783500
hisat2_index: /home/ubuntu/MOUNText/data/snakePipes/GRCm38_gencode_release19/HISAT2Index/genome
ignoreForNormalization: MT X Y JH584299.1 GL456233.1 JH584301.1 GL456211.1 GL456350.1 JH584293.1 GL456221.1 JH584297.1 JH584296.1 GL456354.1 JH584294.1 JH584298.1 JH584300.1 GL456219.1 GL456210.1 JH584303.1 JH584302.1 GL456212.1 JH584304.1 GL456379.1 GL456216.1 GL456393.1 GL456366.1 GL456367.1 GL456239.1 GL456213.1 GL456383.1 GL456385.1 GL456360.1 GL456378.1 GL456389.1 GL456372.1 GL456370.1 GL456381.1 GL456387.1 GL456390.1 GL456394.1 GL456392.1 GL456382.1 GL456359.1 GL456396.1 GL456368.1 JH584292.1 JH584295.1
known_splicesites: /home/ubuntu/MOUNText/data/snakePipes/GRCm38_gencode_release19/HISAT2/splice_sites.txt
rmsk_file: /home/ubuntu/MOUNText/data/snakePipes/GRCm38_gencode_release19/UCSC/mm10/rmsk.txt
star_index: /home/ubuntu/MOUNText/data/snakePipes/GRCm38_gencode_release19/STARIndex2
--------------------------------------------------------------------------------

--- Workflow parameter ---------------------------------------------------------
Input directory: /home/ubuntu/MOUNText/fastq
Input files: ['/home/ubuntu/MOUNText/fastq/sample3_R1.fastq.gz', '/home/ubuntu/MOUNText/fastq/sample3_R2.fastq.gz', '/home/ubuntu/MOUNText/fastq/sample4_R1.fastq.gz', '/home/ubuntu/MOUNText/fastq/sample4_R2.fastq.gz', '/home/ubuntu/MOUNText/fastq/sample7_R1.fastq.gz', '/home/ubuntu/MOUNText/fastq/sample7_R2.fastq.gz']
Samples: ['sample3', 'sample4', 'sample7']
Paired-end reads: False
Read extension: ['_R2', '_R1']
Genome: mm10
Downsample: None
Mode: STARsolo
Trimming: False
Input directory for mapping: originalFASTQ
Input directory for trimming: None
BigWig bin size: 10
Barcode pattern: NNNNNNXXXXXX
Barcode file: /home/ubuntu/bin/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/workflows/scRNAseq/celseq_barcodes.192.txt
UMI_LEN: 6
UMI_offset: 1
CELLI_LEN: 6
CELLI_offset: 7
--------------------------------------------------------------------------------

--- Environment ----------------------------------------------------------------
$TMPDIR:  /tmp
$HOSTNAME:
--------------------------------------------------------------------------------


 !!! ERROR in scRNAseq workflow! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Error: snakemake returned an error code of 1, so processing is incomplete!

**Comment by powellhd** [comment]
Sorry for the bold. Not sure what I did there.

**Comment by LeilyR** [comment]
From what I can see in the code barcodes' length were hardcoded for certain kits , those which we have the barcode white list of them available in our GitHub. However if you chose a different length you need mention that your are using a custom kit and also provide the path to where the white list is located. Maybe you can check these lines of the code if it makes it more clear: 
https://github.com/maxplanck-ie/snakepipes/blob/master/snakePipes/workflows/scRNAseq/internals.snakefile#L60

**Comment by powellhd** [comment]
OK. That makes sense. I will do that. Thank you.

**Comment by LeilyR** [comment]
my other question was that if the length of given barcode by you are not in agreement with what you actually have in your fastq file, but looking at details you have just shared, that is no more relevant. You can ignore it.

**Comment by katsikora** [comment]
As Leily said, the solution to this is to specify '--myKit Custom', as well as provide STARsoloCoords and BCwhiteList as appropriate.
Our preset kit configurations as set for precisely versioned kits and we do not support partially modifying them as this might lead to errors. 
You can still pass one of our barcode white lists that you can find under https://github.com/maxplanck-ie/snakepipes/tree/master/snakePipes/workflows/scRNAseq by downloading them and providing the path to your local copy.
