### ISSUE TITLE
DNAmapping Bowtie2 error

### ISSUE THREAD

**Issue by u-ferah** [maxplanck-ie/snakepipes#726]
Hi everyone,

I have been trying to run DNA-mapping on my school's HPC, using 
`source /mnt/local/python-venv/snakepipes/bin/activate
DNA-mapping -i /mnt/research/mpalopol/students/uferah/readData -o /mnt/research/mpalopol/students/uferah/snake/results \ -v --reads 'R1' 'R2' -j 12 --local --DAG --fastqc --qualimap dm6`

I get this error for every replicate when I try to run my script:

`Error in rule Bowtie2:
    jobid: 83
    output: Bowtie2/K1.Bowtie2_summary.txt, Bowtie2/K1.sorted.bam
    log: Bowtie2/logs/K1.sort.log (check log file(s) for error message)
    shell:
        
            TMPDIR=/mnt/hpc/tmp/$USER
            MYTEMP=$(mktemp -d ${TMPDIR:-/tmp}/snakepipes.XXXXXXXXXX);
            bowtie2             -X 1000             -x /data/repository/organisms/dm6_ensembl/BowtieIndex/genome -1 FASTQ/K1R1.fastq.gz -2 FASTQ/K1R2.fastq.gz              --fr             --rg-id K1             --rg DS:K1 --rg PL:ILLUMINA --rg SM:K1             -p 12             2> Bowtie2/K1.Bowtie2_summary.txt |             samtools view -Sb - |             samtools sort -m 2G -T $MYTEMP/K1 -@ 2 -O bam - > Bowtie2/K1.sorted.bam 2> Bowtie2/logs/K1.sort.log;
            rm -rf $MYTEMP
            
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job Bowtie2 since they might be corrupted:
Bowtie2/K1.Bowtie2_summary.txt, Bowtie2/K1.sorted.bam
Job failed, going on with independent jobs.
`
What are some of the reasons that might cause this error? 
I am using the latest version of snakepipes. I wrote my code in a bash script and ran it through qsub. When I look into {sample}.sort.log files, they all seem empty, so I am very lost and will appreciate any type of help. 

-Utku

**Comment by LeilyR** [comment]
What are the name of your input fastq files? Are they really called k1R1.fastq.gz and k1R2.fastq.gz? Did you mean to add something like  _R1, -R1 or .R1?

**Comment by u-ferah** [comment]
> What are the name of your input fastq files? Are they really called k1R1.fastq.gz and k1R2.fastq.gz? Did you mean to add something like _R1, -R1 or .R1?


Yes, they are named K1R1.fastq.gz, K1R2.fastq.gz, etc.

**Comment by LeilyR** [comment]
oh I think I figured out what went wrong here, check your reference genome

**Comment by u-ferah** [comment]
You are right! I called the default dm6 config file assuming that we already properly set it up. Pretty big mistake on my part, thanks for catching it!
