### ISSUE TITLE
SnakePipes on MacOS

### ISSUE THREAD

**Issue by vitaly001** [maxplanck-ie/snakepipes#730]
Hi,
I have one question, is it possible to use SnakePipes on MacOS 11 (Big Sur).
I used SnakePipes on Linux before. However, I want to use it on new MacBook Pro with M1 chip without Parallels and I do not know if SnakePipes will work using Rosetta 2.
Thank you,
Vitaly

**Comment by katsikora** [comment]
Hi Vitaly,

our snakePipes release builds are tested on whatever MS Azure is serving as macOS-latest, which is currently macOS X Catalina 10.15 for snakePipes 2.4.0/1. We don't test running parallel jobs.


Best,

Katarzyna

**Comment by vivekbhr** [comment]
I'd be surprised if all snakePipes' dependencies work with M1 chip using Rosetta2 without errors, but I am curious.

**Comment by dpryan79** [comment]
It would be surprising if there were any major issues. Rosetta 2 is a bit slow compared to running applications natively, but there have been few major reported issues as of yet (not that there's been much time for problems TO be reported).
