### ISSUE TITLE
RaceID not running with 384 well plates

### ISSUE THREAD

**Issue by powellhd** [maxplanck-ie/snakepipes#731]
Hi, 
I am trying to get the scRNAseq to run RaceID as well as velocyto after the initial analysis of 3 384-well plate samples. What is necessary settings must I set so all three of them are pooled for both RaceID and velocyto?

Cheers,
Sean

**Comment by powellhd** [comment]
@dpryan79

**Comment by katsikora** [comment]
Hi there,

are you trying to run scRNAseq with <code>--mode Gruen</code>? We've deprecated that from snakePipes 2.3.0 onwards.
Velocyto counts are output if you run scRNAseq with <code>--mode STARsolo</code>.

Separate plates are treated as separate samples/replicates. In either mode, the output would contain cells named after whatever the fastq files for the separate plates were named, with a numbered suffix (in your case 1..384). 

Best,

Katarzyna

**Comment by powellhd** [comment]
Hi Kasia,

No I am not running in `--mode Gruen` I am using the default `--mode STARsolo` but not implicitly. 

I do get the .loom file from velocyto but I do not get anything from RaceID.

Cheers,
Sean

**Comment by katsikora** [comment]
Hi Sean,

RaceID used to be part of <code>mode Gruen</code>. If you intend to run that, you might need to use an older snakePipes version for that. For 384 plate format, you'll have to pass the barcode whitelist with <code>--CellBarcodeFile file.txt</code> and the barcode pattern with <code--CellBarcodePattern NNNNNNNXXXXXXX></code>. You can download a copy of the 384 CelSeq2 barcode whitelist from our repo at https://github.com/maxplanck-ie/snakepipes/blob/master/snakePipes/workflows/scRNAseq/celseq_barcodes.384.txt .

Best,

Katarzyna
