### ISSUE TITLE
Multi-factors comparison on DESeq2 analysis

### ISSUE THREAD

**Issue by timothykoala** [maxplanck-ie/snakepipes#739]
Hi,
Currently I am running mRNA-seq workflow and I facing a problem on DESeq2. On the differential expression, if I supplied a sample sheet with more than 2 conditions, it showed error on running DESeq2. 

How can I make a multi-factors DE analysis run seamlessly?

Thanks,

**Comment by katsikora** [comment]
Hi Timothykoala,

what does your sample sheet look like?

Best,

Katarzyna

**Comment by timothykoala** [comment]
Hi Katarzyna,

My sample sheet is a time course experiment so i put multifactors (time) into the sample sheet ,it showed ERROR and didn't run DEseq2:

name	condition
RPE1WTb-0hr1	T0
RPE1WTb-0hr2	T0
RPE1WTb-0hr3	T0
RPE1WTb-2hr1	T2
RPE1WTb-2hr2	T2
RPE1WTb-2hr3	T2
RPE1WTb-10hr1	T10
RPE1WTb-10hr2	T10
RPE1WTb-10hr3	T10
RPE1WTb-18hr1	T18
RPE1WTb-18hr2	T18
RPE1WTb-18hr3	T18
RPE1WTb-30hr1	T30
RPE1WTb-30hr2	T30
RPE1WTb-30hr3	T30
RPE1WTb-48hr1	T48
RPE1WTb-48hr2	T48
RPE1WTb-48hr3	T48
RPE1WT1-0hr1	T0
RPE1WT1-0hr2	T0
RPE1WT1-0hr3	T0
RPE1WT1-2hr1	T2
RPE1WT1-2hr2	T2
RPE1WT1-2hr3	T2
RPE1WT1-10hr1	T10
RPE1WT1-10hr2	T10
RPE1WT1-10hr3	T10
RPE1WT1-18hr1	T18
RPE1WT1-18hr2	T18
RPE1WT1-18hr3	T18
RPE1WT1-30hr1	T30
RPE1WT1-30hr2	T30
RPE1WT1-30hr3	T30
RPE1WT1-48hr1	T48
RPE1WT1-48hr2	T48
RPE1WT1-48hr3	T48

However, when I changed the sample sheet into only two factors, the workflow run sucessfully:
name	condition
RPE1WTb-0hr1	WTb
RPE1WTb-0hr2	WTb
RPE1WTb-0hr3	WTb
RPE1WTb-2hr1	WTb
RPE1WTb-2hr2	WTb
RPE1WTb-2hr3	WTb
RPE1WTb-10hr1	WTb
RPE1WTb-10hr2	WTb
RPE1WTb-10hr3	WTb
RPE1WTb-18hr1	WTb
RPE1WTb-18hr2	WTb
RPE1WTb-18hr3	WTb
RPE1WTb-30hr1	WTb
RPE1WTb-30hr2	WTb
RPE1WTb-30hr3	WTb
RPE1WTb-48hr1	WTb
RPE1WTb-48hr2	WTb
RPE1WTb-48hr3	WTb
RPE1WT1-0hr1	WTc
RPE1WT1-0hr2	WTc
RPE1WT1-0hr3	WTc
RPE1WT1-2hr1	WTc
RPE1WT1-2hr2	WTc
RPE1WT1-2hr3	WTc
RPE1WT1-10hr1	WTc
RPE1WT1-10hr2	WTc
RPE1WT1-10hr3	WTc
RPE1WT1-18hr1	WTc
RPE1WT1-18hr2	WTc
RPE1WT1-18hr3	WTc
RPE1WT1-30hr1	WTc
RPE1WT1-30hr2	WTc
RPE1WT1-30hr3	WTc
RPE1WT1-48hr1	WTc
RPE1WT1-48hr2	WTc
RPE1WT1-48hr3	WTc

**Comment by katsikora** [comment]
Hi Timothykoala,

indeed, DESeq2 default workflow works only with 2 comparison groups, e.g. Control and Treatment.

snakePipes supports multiple comparison groups, if you add a "group" column after the condition column. In this "group" column, you can specify comparison groups, e.g. Group1, Group2, etc. Remember to specify two conditions for each group in the "condition" column.

This will split your original sample sheet into groups, and run one DESeq2 instance (with pairwise comparison between the two conditions) for each group.

Is this what you are after?

Best,

Katarzyna

**Comment by timothykoala** [comment]
Hi Katarzyna,

My question for the grouping is for me I need to use 0hr for each group comparison, can I assign multiple groups for a subset for samples ? (in my example 0hr sample)

Best,
Timothy

**Comment by katsikora** [comment]
Hi Timothy,

in that case, put "All" in the "group" column - this will cause these samples to be added to all comparison groups.

Best,

Katarzyna

**Comment by timothykoala** [comment]
Thanks!
