### ISSUE TITLE
--filterBAM option

### ISSUE THREAD

**Issue by vivekbhr** [maxplanck-ie/snakepipes#74]
In discusions it emerged that --filterBAM options would be good to have to filter the mapped bam additionally for some regions, like chromosome configs and blacklisted sites. This might be useful for DNA mapping and other DNA workflows : ChIP-Seq, ATAC-seq and Hi-C.. Maybe we can discuss this ..

**Comment by dpryan79** [comment]
The following might be relevant: https://github.com/deeptools/deepTools/issues/628

**Comment by vivekbhr** [comment]
PR #92 implemented this
