### ISSUE TITLE
DNA mapping Name Error  'ignoreForNormalization' is not defined

### ISSUE THREAD

**Issue by timothykoala** [maxplanck-ie/snakepipes#740]
Hi,
I have 8 single-end ChIP seq FASTQ.gz file which i renamed them all with suffix '_R1'

It showed this error when I ran DNA-mapping workflow:

```
NameError in line 13 of /anaconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/shared/rules/deepTools_qc.snakefile:
name 'ignoreForNormalization' is not defined
File "/anaconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/workflows/DNA-mapping/Snakefile", line 47, in <module>
  File "/anaconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/shared/rules/deepTools_qc.snakefile", line 13, in <module>
Error: snakemake returned an error code of 1, so processing is incomplete!
```
May I know what can I do for this? Thank you.

**Comment by katsikora** [comment]
Hi Timothykoala,

this looks like a bug in our code, I'll have a look.

Best,

Katarzyna

**Comment by katsikora** [comment]
Hi again,

I cannot reproduce your error with our single end testdata and snakePipes 2.4.2.
Could you post your commandline?

Best,

Katarzyna

**Comment by timothykoala** [comment]
Hi karsikora,

Here is my commandline:
`DNA-mapping -i /media/txpn/input/rpe1_chipseq/ -o /home/txpn/output/rpe1_chipseq/ -j 5 --local --dedup --mapq 5 hg38`

I just realize I am still running on 2.4.1, let me update snakePipes first.

**Comment by LeilyR** [comment]
check your hg38.yaml file. I am afraid `ignoreForNormalization` is missing there

**Comment by timothykoala** [comment]
Hi @LeilyR and @katsikora 
Thanks! I change `ignore_forNorm` into `ignoreForNormalization` in hg38.yaml and problem solved.
