### ISSUE TITLE
set trimming program default to be the same between workflows

### ISSUE THREAD

**Issue by katsikora** [maxplanck-ie/snakepipes#743]
Apparently some workflows have fastp as default, some cutadapt. This gives different results for reads with very low adapter contamination (2-3%). E.g. noncoding-RNA-seq and mRNA-seq.

**Comment by sunta3iouxos** [comment]
Hi there, in your experience is any of them more reliable? I tend to like
more fastp, because it can try to correct paired end reads, but there are
some complains (in GitHub) that it fails to properly remove Gs or other
artifacts.
Thank you

**Comment by sunta3iouxos** [comment]
Hi there, I am reopening this ticket to share my experience with adapters.
I had a sample, rnaseq, that no other trimmer but bbduk could correctly
trim it.
Without bbduk, star aligner was complaining on unmapped small size reads,
or so.
