### ISSUE TITLE
how to set PBS cluster?

### ISSUE THREAD

**Issue by sextuplev** [maxplanck-ie/snakepipes#744]
I noticed that snakePipes is very powerful to do mics analyses including ChIP-seq, RNA-seq, Bisulfite-seq, ATAC-seq, Hi-C and seRNA-seq. Abosutely, IT is a badly REQUIRED program in big biodata era. 

Recently, I installed snakePipes and however, I met a problem on cluster setting 
snakemake_cluster_cmd: qsub -N {rule}.snakemake -q batch -l pmem=10G -l walltime=20:00:00 -l nodes=1:ppn=5 -o {snakePipes_cluster_logDir}/{rule}.\$PBS_JOBID.out -e {snakePipes_cluster_logDir}/{rule}.\$PBS_JOBID.err
snakePipes_cluster_logDir: logs
Using the setting, the following error occurred: 
Error executing rule HISAT2 on cluster (jobid: 83, external: 41458.mu01

cat HISAT2.41458.mu01.err 
---- This analysis has been done using snakePipes version 2.4.2 ----
Sample sheet found and header is ok!
localrules directive specifies rules that are not present in the Snakefile:
	Salmon_wasabi
	sleuth_Salmon

Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 24
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	HISAT2
	1

[Thu Jan 21 17:40:00 2021]
rule HISAT2:
    input: FASTQ/SRR2096208_1.fastq.gz, FASTQ/SRR2096208_2.fastq.gz
    output: HISAT2/SRR2096208.HISAT2_summary.txt, HISAT2/SRR2096208.sorted.bam, HISAT2/SRR2096208/splice_sites.txt, HISAT2/SRR2096208/metrics.txt
    log: HISAT2/logs/SRR2096208.sort.log
    jobid: 0
    benchmark: HISAT2/.benchmark/HISAT2.SRR2096208.benchmark
    wildcards: sample=SRR2096208
    threads: 10

[Thu Jan 21 17:40:00 2021]
Error in rule HISAT2:
    jobid: 0
    output: HISAT2/SRR2096208.HISAT2_summary.txt, HISAT2/SRR2096208.sorted.bam, HISAT2/SRR2096208/splice_sites.txt, HISAT2/SRR2096208/metrics.txt
    log: HISAT2/logs/SRR2096208.sort.log (check log file(s) for error message)
    conda-env: /Data/wwwu/miniconda3/envs/84a7bff1c9671ca12632408009ab8d7a
           
     TMPDIR=/Data/wwwu/tmp/
     MYTEMP=$(mktemp -d ${TMPDIR:-/tmp}/snakepipes.XXXXXXXXXX);
                hisat2 -p 10                      --rna-strandness RF -x /Data/database/genomes/GRCm38_gencode_release19/HISAT2Index/genome                     --known-splicesite-infile /Data/database/genomes/GRCm38_gencode_release19/HISAT2Index/splice_sites.txt                     -1 FASTQ/SRR2096208_1.fastq.gz -2 FASTQ/SRR2096208_2.fastq.gz                     --novel-splicesite-outfile HISAT2/SRR2096208/splice_sites.txt                     --met-file HISAT2/SRR2096208/metrics.txt 2> HISAT2/SRR2096208.HISAT2_summary.txt                 | samtools sort -m 2G -T $MYTEMP/SRR2096208 -@ 10 -O bam -o HISAT2/SRR2096208.sorted.bam - 2> HISAT2/logs/SRR2096208.sort.log;
                rm -rf $MYTEMP
                
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

However, it worked on local running.
Can you be kind to give advice on how to solve it? Here is my cluster info: PBS scheduler controlling 4 nodes, and each node sharing 24 processors and 128G mem. 

Many thanks for your time. 
Best wishes,
Wenwu Wu

**Comment by LeilyR** [comment]
could you please share with us your command line and the error message that you have got in your cluster log?

**Comment by sextuplev** [comment]
The commond line is:
mRNA-seq --sampleSheet sampleSheet.csv --DAG -i . -o cluster/ -j 6 mm10 &

The error message such as, HISAT2.41461.mu01.err with contents:

---- This analysis has been done using snakePipes version 2.4.2 ----
Sample sheet found and header is ok!
localrules directive specifies rules that are not present in the Snakefile:
	sleuth_Salmon
	Salmon_wasabi

Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 24
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	HISAT2
	1

[Thu Jan 21 17:33:40 2021]
rule HISAT2:
    input: FASTQ/SRR2096206_1.fastq.gz, FASTQ/SRR2096206_2.fastq.gz
    output: HISAT2/SRR2096206.HISAT2_summary.txt, HISAT2/SRR2096206.sorted.bam, HISAT2/SRR2096206/splice_sites.txt, HISAT2/SRR2096206/metrics.txt
    log: HISAT2/logs/SRR2096206.sort.log
    jobid: 0
    benchmark: HISAT2/.benchmark/HISAT2.SRR2096206.benchmark
    wildcards: sample=SRR2096206
    threads: 10

[Thu Jan 21 17:33:40 2021]
Error in rule HISAT2:
    jobid: 0
    output: HISAT2/SRR2096206.HISAT2_summary.txt, HISAT2/SRR2096206.sorted.bam, HISAT2/SRR2096206/splice_sites.txt, HISAT2/SRR2096206/metrics.txt
    log: HISAT2/logs/SRR2096206.sort.log (check log file(s) for error message)
    conda-env: /Data/wwwu/miniconda3/envs/84a7bff1c9671ca12632408009ab8d7a
    shell:
        
                TMPDIR=/Data/wwwu/tmp/
                MYTEMP=$(mktemp -d ${TMPDIR:-/tmp}/snakepipes.XXXXXXXXXX);
                hisat2 -p 10                      --rna-strandness RF -x /Data/database/genomes/GRCm38_gencode_release19/HISAT2Index/genome                     --known-splicesite-infile /Data/database/genomes/GRCm38_gencode_release19/HISAT2Index/splice_sites.txt                     -1 FASTQ/SRR2096206_1.fastq.gz -2 FASTQ/SRR2096206_2.fastq.gz                     --novel-splicesite-outfile HISAT2/SRR2096206/splice_sites.txt                     --met-file HISAT2/SRR2096206/metrics.txt 2> HISAT2/SRR2096206.HISAT2_summary.txt                 | samtools sort -m 2G -T $MYTEMP/SRR2096206 -@ 10 -O bam -o HISAT2/SRR2096206.sorted.bam - 2> HISAT2/logs/SRR2096206.sort.log;
                rm -rf $MYTEMP
                
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message



> could you please share with us your command line and the error message that you have got in your cluster log?

**Comment by sextuplev** [comment]
Actually, If I used STAR instead, the same erro occurred.

**Comment by LeilyR** [comment]
which version are you using? The command you shared should not generate the DAG you have sent.  First thing, please update your version to the latest one and re-run the pipeline.

Also what can help is to look at the log under HISAT2/logs folder, or even share the error message in it with us.

**Comment by sextuplev** [comment]
> which version are you using? The command you shared should not generate the DAG you have sent. First thing, please update your version to the latest one and re-run the pipeline.
> 
> Also what can help is to look at the log under HISAT2/logs folder, or even share the error message in it with us.

Yes, I used the version 2.4.2 and here is HISAT2/logs folder:
![image](https://user-images.githubusercontent.com/22436936/105354411-79b22800-5c2b-11eb-9619-d1ef6ebb7db9.png)
As you see, the log files are all empty.

**Comment by sextuplev** [comment]
> which version are you using? The command you shared should not generate the DAG you have sent. First thing, please update your version to the latest one and re-run the pipeline.
> 
> Also what can help is to look at the log under HISAT2/logs folder, or even share the error message in it with us.

Dear LeilyR, Is the following cluster setting OK ?

**snakemake_cluster_cmd: qsub -N {rule}.snakemake -q batch -l pmem=10G -l walltime=20:00:00 -l nodes=1:ppn=5 -o {snakePipes_cluster_logDir}/{rule}.$PBS_JOBID.out -e {snakePipes_cluster_logDir}/{rule}.$PBS_JOBID.err**

**Comment by LeilyR** [comment]
But this cannot be. 2.4.2 uses STAR by default and the command you have sent should not have HISAT in the dag.

**Comment by sextuplev** [comment]
THANKS for your reponse. 

I have tried both HISAT2 and STAR and both worked fine. 
I guessed the problem may be the cluster setting or similar envirioment setting, the following is some infor:

![image](https://user-images.githubusercontent.com/22436936/105357454-d3b4ec80-5c2f-11eb-8fd8-4013acb8c1a6.png)

![image](https://user-images.githubusercontent.com/22436936/105357763-3f975500-5c30-11eb-98df-d8bee106d00d.png)

![image](https://user-images.githubusercontent.com/22436936/105357650-14146a80-5c30-11eb-88dd-f7a2980877f4.png)





> But this cannot be. 2.4.2 uses STAR by default and the command you have sent should not have HISAT in the dag unless your local installation has been modified.
> Can you submit the HISAT command stand alone on your cluster? Also why your jobid is 0 while it is 41461 in your cluster log?

**Comment by sextuplev** [comment]
> But this cannot be. 2.4.2 uses STAR by default and the command you have sent should not have HISAT in the dag unless your local installation has been modified.
> Can you submit the HISAT command stand alone on your cluster? Also why your jobid is 0 while it is 41461 in your cluster log?

Hi LeilyR, today, I used the createIndices to create the genome index and  run the command on node 2 (one of the cluster): createIndices -o outdir --genome `pwd`/genome.fa.gz --gtf `pwd`/genes.gtf.gz --ignoreForNormalization ignore.txt --local smv1.0 
it run OK as well as on the manager node. 
However, when I run the commond on manager node without the parameter --local,  that is,createIndices -o outdir --genome `pwd`/genome.fa.gz --gtf `pwd`/genes.gtf.gz --ignoreForNormalization ignore.txt smv1.0, the error occurred again. 

Here are some errors:
![image](https://user-images.githubusercontent.com/22436936/105462900-483c6980-5cca-11eb-8a12-fef948d41f8a.png)
![image](https://user-images.githubusercontent.com/22436936/105462963-5e4a2a00-5cca-11eb-9905-e3b06ef03c54.png)

![image](https://user-images.githubusercontent.com/22436936/105463076-7fab1600-5cca-11eb-9a58-2bf779d503e4.png)
![image](https://user-images.githubusercontent.com/22436936/105463171-a2d5c580-5cca-11eb-94db-59e04b214ad2.png)

**Comment by LeilyR** [comment]
have you tried your qub command outside snakepipes? Maybe just the shell script of one of the failed rules.
Also can you send us the log files from your qub submission?

**Comment by sextuplev** [comment]
Of course, I have run qsub for many many times outside of snakepipes. 
Pls see the attachment for the log file from qsub submission. 



wenwu_wu@aliyun.com
 
From: LeilyR
Date: 2021-01-22 16:17
To: maxplanck-ie/snakepipes
CC: Walden; Author
Subject: Re: [maxplanck-ie/snakepipes] how to set PBS cluster? (#744)
have you tried your qub command outside snakepipes? Maybe just the shell script of one of the failed rules.
Also can you send us the log files from your qub submission?

**Comment by sextuplev** [comment]
Dear authors, 

I found the problem that the enviroment setting of the cluster nodes for snakePipes is not the same as management node, and now it is solved. 

Thanks very much for your time and patience.

Best wishes,
Wenwu Wu



wenwu_wu@aliyun.com
 
From: LeilyR
Date: 2021-01-22 16:17
To: maxplanck-ie/snakepipes
CC: Walden; Author
Subject: Re: [maxplanck-ie/snakepipes] how to set PBS cluster? (#744)
have you tried your qub command outside snakepipes? Maybe just the shell script of one of the failed rules.
Also can you send us the log files from your qub submission?
