### ISSUE TITLE
Premade indices Mouse (GRCm38/mm10, Gencode release m19) did not work

### ISSUE THREAD

**Issue by timothykoala** [maxplanck-ie/snakepipes#746]
I downloaded the premade indice for mm10 (https://zenodo.org/record/4020455#.YA84RdYo8aw) and modified the provided YAML file, however my mRNA-seq workflow showed error below:

```
EXITING because of FATAL ERROR: Genome version: 20201 is INCOMPATIBLE with running STAR version: 2.7.4a
SOLUTION: please re-generate genome from scratch with running version of STAR, or with version: 2.7.4a
```

When I tried to createIndices with command, it showed:
```
```
rule createGenomeFasta:
    output: /home/.../mm10new/genome_fasta/genome.fa
    jobid: 1

/bin/sh: 1: module: not found
sbatch: error: s_p_parse_file: unable to status file /etc/slurm-llnl/slurm.conf: No such file or directory, retrying in 1sec up to 60sec
sbatch: fatal: Unable to process configuration file
Error submitting jobscript (exit code 1):

Job failed, going on with independent jobs.

rule downloadGTF:
    output: /home/.../mm10new/annotation/genes.gtf
    jobid: 5

/bin/sh: 1: module: not found
sbatch: error: s_p_parse_file: unable to status file /etc/slurm-llnl/slurm.conf: No such file or directory, retrying in 1sec up to 60sec
sbatch: fatal: Unable to process configuration file
Error submitting jobscript (exit code 1):

Job failed, going on with independent jobs.
Exiting because a job execution failed. Look above for error message
Complete log: /home/.../mm10new/.snakemake/log/2021-01-26T004129.277336.snakemake.log
```

 !!! ERROR in index creation workflow! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

How can I deal with it? Thanks.

**Comment by katsikora** [comment]
Hi Timothy,

the first error is related to the STAR index file for mm10 being generated with an older STAR version. We will fix it on zenodo and update the link.

The second error: it looks like your cluster configuration is incorrect. Do you have a slurm cluster such as ours? How do you access the binaries - I guess not via module, as in our preset ? 
You will need to adjust  "snakemake_cluster_cmd" in cluster.yaml to what's appropriate for your environment, and then run snakePipes config providing the modified cluster file.

Best,

Katarzyna

**Comment by timothykoala** [comment]
Hi Katarzyna,

First, Thanks for the coming update.
For the second error, You reminded me I should add '--local' in command.

Best,
Timothy

**Comment by katsikora** [comment]
Premade indices working with STAR 2.7.4a are now available on zenodo. Links in the _latest_  documentation version are now pointing to these.
