### ISSUE TITLE
createIndices - bowtie2

### ISSUE THREAD

**Issue by acpooth** [maxplanck-ie/snakepipes#752]
Hi there,

First of all, I want to tell you that I love snakePipes. Thank you for all your work!

This error occurred when the createIndices pipeline was executed. Specifically, at the creation of Bowtie2 indices:

> /home/anaconda/miniconda3/envs/817ac651f235b9eb9d9bd644de6e03d7/bin/bowtie2-build-s: error while loading shared libraries: libtbb.so.2: cannot open shared object file: No such file or directory
[Wed Mar 10 16:00:35 2021]
Error in rule bowtie2Index:
    jobid: 9
    output: /home/anaconda/data/snakePipes/GRCm39_rel103/BowtieIndex/genome.rev.2.bt2
    log: logs/bowtie2Index.log (check log file(s) for error message)
    conda-env: /home/anaconda/miniconda3/envs/817ac651f235b9eb9d9bd644de6e03d7
    shell:
        ln -s /home/anaconda/data/snakePipes/GRCm39_rel103/genome_fasta/genome.fa /home/anaconda/data/snakePipes/GRCm39_rel103/BowtieIndex/genome.fa
        bowtie2-build -t 10 /home/anaconda/data/snakePipes/GRCm39_rel103/BowtieIndex/genome.fa /home/anaconda/data/snakePipes/GRCm39_rel103/BowtieIndex/genome
        if [[ -f BowtieIndex/genome.rev.2.bt2l ]]; then ln -s genome.rev.2.bt2l /home/anaconda/data/snakePipes/GRCm39_rel103/BowtieIndex/genome.rev.2.bt2 ; fi
        2> logs/bowtie2Index.log
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
Job failed, going on with independent jobs.
[Wed Mar 10 16:00:46 2021]

It appears to be related to tbb libraries. The installed version in the corresponding virtual env was 2021.1.1.

It is a fresh installation of snakePipes (2.4.3).

I fixed the error installing tbb=2019.1 at the virtual env 817ac651f235b9eb9d9bd644de6e03d7 (the one that produced the error). This action downgrades Bowtie2 and tbb.

At the moment, this action does not produce further errors.

I hope this information to be useful and maybe you can tell me if there is any better solution.

Best regards.

**Comment by LeilyR** [comment]
Hey,
This seems to be an issue occured after an tbb update in conda-forge few days ago.
For now installing the tbb-2020.2 in the same environment resolves the problem. 
We consider adding it into our env.yaml files and tag a new release asap.

**Comment by acpooth** [comment]
Thank you!

This fix the problem.
