### ISSUE TITLE
mRNA-seq --sampleSheet works for rMats, but not for DESeq2

### ISSUE THREAD

**Issue by mirax87** [maxplanck-ie/snakepipes#756]
Hi,

I am running snakePipes 2.4.3 ` mRNA-seq [...] --rMats --samplesheet <tsv>`. This triggers rMats and DESeq2 to be run. However, the sample names were accepted for rMats, but not for DESeq2. rMats finished succesfully.

My expectation is that one samplesheet should work for rMats and one for DEseq2. 

In addition, for the RTD, I didn't find the rMats folder in the output directory tree. Would be nice to have it there. 

------
DEseq2 error log:

```
[...]
Error! Count table column names and setup table names do NOT match!
[1] "Count table : "
[...]
[10] "heads_w1118_R1_input"   
[...]
[1] "Setup table : "
[1] "heads_w1118_R1_input.pooled"  
[...]
```

PS: I trimmed it down to the mismatching filenames. 

-----

I did some investigations on the samplesheets:

My problematic bam files are as following: `<name_part1>.<name_part2>.filtered.bam` (some are actually just `<name>.filtered.bam` - these are fine).

The problem is in the construction of the `counts.tsv`, input for DESeq2. The `counts.tsv` is produced from `snakePipes/shared/rscripts/merge_count_tables.R`, which assumes the sample name to be before the first dot '.'. This reduces the sample name to `<name_part1>`, instead of  `<name_part1>.<name_part2>`. However, in the sample sheet I put `<name_part1>.<name_part2>` - as expected by the rMats rule.

For rMats, the '.filtered.bam' is explicitly trimmed off to extract the sample name, so that part is working as expected. `https://github.com/maxplanck-ie/snakepipes/blob/master/snakePipes/shared/rules/rMats.snakefile` rule `createInputcsv`.

My suggestion would be to let `merge_count_table.R` trim off '.filtered.bam' explicitly, instead of taking the prefix before the first dot '.'.

Cheers,
-Michael

**Comment by katsikora** [comment]
Hi Michael,

I think this relates to your other issue #789 

I'll close this one and we'll handle it there.

Best,
Katarzyna
