### ISSUE TITLE
Feature Request: Input accessions from SRA

### ISSUE THREAD

**Issue by millerh1** [maxplanck-ie/snakepipes#758]
Thank you for making this amazing tool! I have a use case where I find myself mining public sequencing datasets fairly often and I've gotten in the habit of writing custom snakemake workflows to do this. I would like to use `snakePipes` but it doesn't currently support using accessions from SRA/GEO instead of a file directory. Is this a feature that you are interested in implementing?

**Comment by WardDeb** [comment]
Hi,

Thanks for the feedback. 
We'll have a look to implement accession lists as input for the next release.

Kind regards,

Ward

**Comment by katsikora** [comment]
Hi Both,

I think we decided against using SRA accessions directly already a while ago. One reason behind it is that the files are often malformatted, or the metadata incomplete. There is parallel fast-dump that you can use to speed up file download. 

Do you agree @WardDeb ?

Best,
Katarzyna
