### ISSUE TITLE
setting max # threads for cluster?

### ISSUE THREAD

**Issue by kmattioli** [maxplanck-ie/snakepipes#761]
Hello! Thank you for all of your work on snakePipes -- it has been super useful for me so far.

One question that I can't seem to figure out: is there a way to set a maximum number of threads / cores for your cluster? The max # for all of my slurm partitions is 20, so rules that request 24 threads (so far `Bowtie` and some `deeptools` ones like `plotCoverage`) are erroring out. I have been fixing these by hard-coding the `threads: 24` line down to 20 in each of the `snakemake` files, but wondering if there's a more efficient way.

**Comment by LeilyR** [comment]
Hey, Thank you for the feedback!
You are right, there is no global cap and you need to set them per rule, as you did. We are thinking of adding a max cap to be adjusted by users in similar cases as yours. To our experience, it can get tricky with some tools, if a user set a very low cap (e.g, Sambamba). We will do our best to provide warning messages where needed. Keep an eye on the next release and let us know how it worked for you. Cheers!
