### ISSUE TITLE
questions about histoneHMM

### ISSUE THREAD

**Issue by kmattioli** [maxplanck-ie/snakepipes#766]
Hello,

It seems like the histoneHMM outputs in the ChIP-seq pipeline are based solely on the `filtered.bam` ChIP samples, and any input controls (if they exist) are ignored. (I have reached this conclusion by looking at the `histoneHMM_call_regions.R` script and the `histoneHMM.snakefile` code).

Just a few questions; not sure if you all are equipped to answer but the histoneHMM repo seems less active so figured I would try here first to see if anyone can help me out:
1) Is the above understanding correct that no input is considered when calling histoneHMM peaks? If not, please ignore question 2 below.
2) Would it be advisable to do differential peak calling between histoneHMM regions on each ChIP sample and its corresponding input control? This is more I guess a question of best practice -- I am analyzing H3K27me3 data that is quite noisy, and this pipeline + histoneHMM seem to work better than other tools I've tried, but now I am a bit concerned that the inputs are being ignored.

Thank you in advance for any insight!

**Comment by WardDeb** [comment]
Hi,

For the first question, you are correct. histoneHMM is ran on the filtered.bam. Perhaps on the histoneHMM repo they could give you better information.
I'm not sure if running differential peaks versus input would help that much, but what could give some insight is run histoneHMM on the input alone, and after comparing both peak sets (e.g. if the input contains some well defined broad regions) subtract the input peaks from the ChIP. 

Hope this helps you a bit,

Kind regards,

Ward
