### ISSUE TITLE
setting up number of threads 

### ISSUE THREAD

**Issue by ANDdna1991** [maxplanck-ie/snakepipes#767]
Hello, SnakePipes looks great!! I'm just trying to set up snakePipes in a Slurm HPC and I'd need so support, I hope anyone can help me. I'm just running createIndices and I got this error:

"Some of your processes may have been killed by the cgroup out-of-memory handler."

The problem is I'm asking for the wrong number of threads. I increased the memory from 20G to 60G, but that doesn't solve the issue. Each of my cluster cores has 3420 MiB of memory so I need to ask for the proper number of cores in each rule to allow the right memory. This is my cluster config file:

snakemake_cluster_cmd: module load slurm; sbatch --ntasks-per-node=1
   -c {threads} -J {rule}.snakemake --mem-per-cpu={cluster.memory}
   -A XXXX -p XXXX -o {snakePipes_cluster_logDir}/{rule}.%j.out
   -e {snakePipes_cluster_logDir}/{rule}.%j.err
snakePipes_cluster_logDir: cluster_logs
snakemake_latency_wait: 300
__default__:
    memory: 1G
createGenomeFasta:
    memory: 60G    

How do I define the number of cores per rules?? Could someone help me with this?? 

Thanks a lot! I really appreciate it!
Andres

**Comment by LeilyR** [comment]
At the moment the numebr of cores can be set per rule and are hard coded into each rule. Find the rule which you need to change the number of threads for it and modify it inside the rule.

**Comment by ANDdna1991** [comment]
Hi Thanks LeilyR! I did  so!

What about time, I don't see how snakePipes defines the time per each rule and some of my jobs are been killed too soon.  Is time set by default for all rules or it's specifically defined by each rule?  I  guess I could increase the time for all the submissions in the cluster configuration file ( "--time= 02:00:00"), or add a variable for each rule to refer to ("--time={resources.time}"), but in the latter I'd have to modify all the rules. what do you recommend??  Or if there is a better solution I'd be glad to hear.

Thank you very much!!
Andres

**Comment by ANDdna1991** [comment]
Hi, I tried to increase the number of threads in the rule but I got an error:

rule bowtie2Index:
    input: /rds/project/rds-XUr6B1Jhndg/ah2192_backup/annotations/Hybrid_genome/genome_fasta/genome.fa
    output: /rds/project/rds-XUr6B1Jhndg/ah2192_backup/annotations/Hybrid_genome/BowtieIndex/genome.rev.2.bt2
    log: logs/bowtie2Index.log
    jobid: 10
    threads: 20

sbatch: error: Batch job submission failed: Requested node configuration is not available
Error submitting jobscript (exit code 1):

Job failed, going on with independent jobs.

Probably it's a problem of cluster configuration, but I don't know how to fix it. 

Any input is more than welcome
Thanks
Andres

**Comment by LeilyR** [comment]
I assume you do not have the resource you have requested. The combination of memory which you may have set in the cluster.yaml and this 20 threads seem to not be available.
