### ISSUE TITLE
Jobs submission

### ISSUE THREAD

**Issue by ANDdna1991** [maxplanck-ie/snakepipes#769]
Hi all, 

I'm experiencing some issue with the jobs submission with snakePipes. At the moment, some jobs are submitted but not all of them, I guess snakePipes is waiting to submit the rest but finally the pipe breaks and not all the jobs are submitted. Is this how  snakePipes usually works? 

this is my queue:

 JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
          41091556    cclake filter_r   ah2192 PD       0:00      1 (None)
          41091558    cclake bamCover   ah2192 PD       0:00      1 (None)
          41091559    cclake estimate   ah2192 PD       0:00      1 (None)

I see the jobs don't have “(dependency)” tag, they have “(none)”. could be that the problem? 

The point is after a while, snakepipes doesn't submit more jobs and I have to resubmit (several times) the script to complete all the rules. What could be the problem and how could I fix it??

Thanks a lot in advance,
Andres

**Comment by WardDeb** [comment]
Hi Andres,

By default snakePipes will execute at most 5 jobs in parallel, this can be configured by using the -j / --jobs flag in your submission. 

In your queue example, it seems like you have 3 jobs that are submitted, but are waiting to be executed (PD status, without a reason). This implies that the requested resources are available, but the jobs are stalled for some other reason. My guess is this would be slurm specific, could you double check with your sysadmin what specific restrictions for job submission there are ?

Kind regards,

Ward

**Comment by ANDdna1991** [comment]
Great, I will ask my sysadmin and I will come back here.

Best,
Andres
