### ISSUE TITLE
bamCompare_subtract in ChIP-seq doesn't run

### ISSUE THREAD

**Issue by ANDdna1991** [maxplanck-ie/snakepipes#770]
Hi, 

I ran ChIP-seq (with spikeIn) script and it ran successfully, however, it omitted the bamCompare_subtract rule, although I explicitly gave the option "--bigWigType "both"". I'm trying to figure out how bamCompare_subtract rule is called, but I still didn't find it. Has anyone experienced the same issue? I'm using snakePipes version 2.4.3. 

Thanks,
Andres

**Comment by LeilyR** [comment]
Hi You are right. I see that calling bamCompare for chip data with spike-in has been commented out. The fastest solution for you would be to uncomment those lines from here:
https://github.com/maxplanck-ie/snakepipes/blob/2.4.3/snakePipes/workflows/ChIP-seq/Snakefile#L115
We will take care of that in the next release.

**Comment by ANDdna1991** [comment]
Ok, thank you very much!^^

Andres
