### ISSUE TITLE
prebuilt GRCh38 (gencode, release 29) indices

### ISSUE THREAD

**Issue by EasyPiPi** [maxplanck-ie/snakepipes#779]
Hi,

I'm a new user of snakePipes and find it's a very handy tool! Thanks a lot for making it available!

When following the tutorial, I understand we need genome indices to run the pipeline. I downloaded the mouse one from Zenodo without any problems. However, when I tried the human one (https://zenodo.org/record/4471116#.YO9fHHVKhH4), I cannot successfully download it.  Every time it stops at around 10 to 20GB, but the whole file is more than 40GB.

I have tried different OS (windows, linux), different tools (wget, curl or just using brower) and even different networks (via VPN) but still no luck.

I'm wondering if it's only a specific problem for me, or is there any issues for this particular file on Zenodo?

I also download other tutorial files like fastq files without any problem. So just the human indices don't work for me.

It will be great if the authors can let me know what might be happening.

Thanks again for making this tool and look forward to your reply!

Best,
Yixin

**Comment by vitaly001** [comment]
Hi Yixin,
I used wget on Mac OS recently and it worked just fine.
Best

**Comment by EasyPiPi** [comment]
Thanks for the prompt reply! It's good to know it works for you.

Then I will try again and see if it's just some random network issues.

Best,
Yixin

**Comment by EasyPiPi** [comment]
I've successfully downloaded the files I need.

Thanks again for making this great tool!

Yixin
