### ISSUE TITLE
localrules directive specifies rules that are not present in the Snakefile: 	Salmon_wasabi 	sleuth_Salmon

### ISSUE THREAD

**Issue by Dnarnas** [maxplanck-ie/snakepipes#780]
How can I check the presence of Salmon_wasabi and sleuth_Salmon?

I run test files locally and got next message:

mRNA-seq -i /Volumes/HD2/Exp1_dedup_data/C_48H -o /Volumes/HD2/Exp1_dedup_data/C_48H --local --sampleSheet '/Volumes/HD2/Exp1_dedup_data/C_48H/48H.tsv' --DAG  hg38
Sample sheet found and header is ok!

---- This analysis has been done using snakePipes version 2.5.1 ----
Sample sheet found and header is ok!
localrules directive specifies rules that are not present in the Snakefile:
	Salmon_wasabi
	sleuth_Salmon

Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 5
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	DESeq2
	6	FASTQ1
	6	FASTQ2
	6	STAR
	1	all
	6	bamCoverage_RPKM
	6	bamCoverage_raw
	6	bamCoverage_scaleFactors
	6	bamCoverage_unique_mappings
	1	bamPE_fragment_size
	6	convert_flagstat_output
	6	estimateReadFiltering
	6	featureCounts
	1	filter_gtf
	6	filter_reads
	1	gtf_to_files
	1	merge_featureCounts
	1	multiBamSummary_bed
	1	multiBigwigSummary_bed
	1	multiQC
	6	origFASTQ1
	6	origFASTQ2
	1	plotCorr_bed_pearson
	1	plotCorr_bed_spearman
	1	plotEnrichment
	1	plotPCA
	1	qc_report_all
	1	report_flagstat_all_data
	6	sambamba_flagstat
	6	sambamba_markdup
	6	samtools_index_filtered
	111
After running for a while I got next error:

Finished job 153.
301 of 303 steps (99%) done
Exiting because a job execution failed. Look above for error message
Complete log: /Volumes/HD2/Exp1_dedup_data/C_48H/.snakemake/log/2021-07-26T120210.619378.snakemake.log

 !!! ERROR in RNA-seq workflow! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Error: snakemake returned an error code of 1, so processing is incomplete!

**Comment by LeilyR** [comment]
That warning message is harmless, The error is coming from somewhere else, please check your log file for where error happened

**Comment by Dnarnas** [comment]
I had an impression that subsequent errors came from the initial one. 
Below please find the  description of error from log file.


Activating conda environment: /Users/work/miniconda3/envs/268a0fcd39cf85aa91ac168c8c05230f

[Tue Jul 27 14:13:43 2021]
Error in rule DESeq2:
    jobid: 22
    output: DESeq2_48H/DESeq2.session_info.txt
    log: DESeq2_48H/logs/DESeq2.out, DESeq2_48H/logs/DESeq2.err (check log file(s) for error message)
    conda-env: /Users/work/miniconda3/envs/268a0fcd39cf85aa91ac168c8c05230f
    shell:
        cd DESeq2_48H && Rscript /Users/work/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/shared/rscripts/DESeq2.R /Volumes/HD2/Exp1_dedup_data/C_48H/48H.tsv ../featureCounts/counts.tsv 0.05 ../Annotation/genes.filtered.symbol /Users/work/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/shared/rscripts/DE_functions.R FALSE NA /Users/work/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/shared/rscripts/DESeq2Report.Rmd  > ../DESeq2_48H/logs/DESeq2.out 2> ../DESeq2_48H/logs/DESeq2.err
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Job failed, going on with independent jobs.


**Log file show next message:**


Warning message:
package ‘rmarkdown’ was built under R version 3.6.3 
Warning message:
package ‘knitcitations’ was built under R version 3.6.3 
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Users/vbalan/miniconda3/envs/268a0fcd39cf85aa91ac168c8c05230f/lib/R/library/DESeq2/libs/DESeq2.dylib':
  dlopen(/Users/vbalan/miniconda3/envs/268a0fcd39cf85aa91ac168c8c05230f/lib/R/library/DESeq2/libs/DESeq2.dylib, 6): Library not loaded: @rpath/libopenblasp-r0.3.7.dylib
  Referenced from: /Users/vbalan/miniconda3/envs/268a0fcd39cf85aa91ac168c8c05230f/lib/R/library/DESeq2/libs/DESeq2.dylib
  Reason: image not found
Calls: DESeq_basic ... getNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted

**Comment by LeilyR** [comment]
it seems that `libopenblasp` is missing in your conda env. You had a similar issue a while ago. Have you tried to make the environments again then? If you did that and you still get this error, could you please let us know. Otherwise please try it.
For now, if you have already tried to force creating environments again and it did not work for you, just install `libopenblasp` in the env that requires it.

**Comment by Dnarnas** [comment]
I already tried to create environment again and it didn't work. Could you please tell me how I can install libopenblasp in the env?

**Comment by Dnarnas** [comment]
I tried to install libopenblasp using:  
conda install -c conda-forge opencv --override-channels

environment location: /Users/work/miniconda3/envs/snakePipes

  added / updated specs:
    - opencv


The following packages will be downloaded:
package                    |            build
    ---------------------------|-----------------
    ffmpeg-4.3.2               |       h4dad6da_0        49.3 MB  conda-forge
    gnutls-3.6.13              |       h756fd2b_1         2.0 MB  conda-forge
    hdf5-1.10.6                |nompi_h34ad4e8_1111         3.0 MB  conda-forge
    jasper-1.900.1             |    h636a363_1006         283 KB  conda-forge
    krb5-1.19.2                |       hcfbf3a7_0         1.3 MB  conda-forge
    lame-3.100                 |    h35c211d_1001         521 KB  conda-forge
    libblas-3.9.0              |           10_mkl          12 KB  conda-forge
    libcblas-3.9.0             |           10_mkl          11 KB  conda-forge
    libcurl-7.78.0             |       hf45b732_0         316 KB  conda-forge
    libgfortran-4.0.0          |7_5_0_h1a10cd1_23          19 KB  conda-forge
    libgfortran4-7.5.0         |      h1a10cd1_23         1.1 MB  conda-forge
    liblapack-3.9.0            |           10_mkl          11 KB  conda-forge
    liblapacke-3.9.0           |           10_mkl          11 KB  conda-forge
    libopenblas-0.3.10         |openmp_h63d9170_3         8.2 MB  conda-forge
    libopencv-4.5.1            |   py39h2677ad0_0        29.3 MB  conda-forge
    nettle-3.6                 |       hedd7734_0         1.2 MB  conda-forge
    openblas-0.3.10            |openmp_h4693e9e_3         9.2 MB  conda-forge
    opencv-4.5.1               |   py39h6e9494a_0          21 KB  conda-forge
    openh264-2.1.1             |       hfd3ada9_0         1.5 MB  conda-forge
    py-opencv-4.5.1            |   py39h71a6800_0         1.1 MB  conda-forge
    x264-1!161.3030            |       h0d85af4_1         2.5 MB  conda-forge
    ------------------------------------------------------------
                                           Total:       110.7 MB

The following NEW packages will be INSTALLED:

  ffmpeg             conda-forge/osx-64::ffmpeg-4.3.2-h4dad6da_0
  gmp                conda-forge/osx-64::gmp-6.2.1-h2e338ed_0
  gnutls             conda-forge/osx-64::gnutls-3.6.13-h756fd2b_1
  hdf5               conda-forge/osx-64::hdf5-1.10.6-nompi_h34ad4e8_1111
  jasper             conda-forge/osx-64::jasper-1.900.1-h636a363_1006
  krb5               conda-forge/osx-64::krb5-1.19.2-hcfbf3a7_0
  lame               conda-forge/osx-64::lame-3.100-h35c211d_1001
  libblas            conda-forge/osx-64::libblas-3.9.0-10_mkl
  libcblas           conda-forge/osx-64::libcblas-3.9.0-10_mkl
  libcurl            conda-forge/osx-64::libcurl-7.78.0-hf45b732_0
  libedit            conda-forge/osx-64::libedit-3.1.20191231-h0678c8f_2
  libev              conda-forge/osx-64::libev-4.33-haf1e3a3_1
  libgfortran4       conda-forge/osx-64::libgfortran4-7.5.0-h1a10cd1_23
  liblapack          conda-forge/osx-64::liblapack-3.9.0-10_mkl
  liblapacke         conda-forge/osx-64::liblapacke-3.9.0-10_mkl
  libnghttp2         conda-forge/osx-64::libnghttp2-1.43.0-h07e645a_0
  **libopenblas        conda-forge/osx-64::libopenblas-0.3.10-openmp_h63d9170_3**
  libopencv          conda-forge/osx-64::libopencv-4.5.1-py39h2677ad0_0
  libssh2            conda-forge/osx-64::libssh2-1.9.0-h52ee1ee_6
  nettle             conda-forge/osx-64::nettle-3.6-hedd7734_0
  opencv             conda-forge/osx-64::opencv-4.5.1-py39h6e9494a_0
  openh264           conda-forge/osx-64::openh264-2.1.1-hfd3ada9_0
  py-opencv          conda-forge/osx-64::py-opencv-4.5.1-py39h71a6800_0
  x264               conda-forge/osx-64::x264-1!161.3030-h0d85af4_1

After running mRNA-seq  I got same message:

Warning message:
package ‘rmarkdown’ was built under R version 3.6.3 
Warning message:
package ‘knitcitations’ was built under R version 3.6.3 
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Users/work/miniconda3/envs/268a0fcd39cf85aa91ac168c8c05230f/lib/R/library/DESeq2/libs/DESeq2.dylib':
  dlopen(/Users/work/miniconda3/envs/268a0fcd39cf85aa91ac168c8c05230f/lib/R/library/DESeq2/libs/DESeq2.dylib, 6): Library not loaded: @rpath/libopenblasp-r0.3.7.dylib
  Referenced from: /Users/work/miniconda3/envs/268a0fcd39cf85aa91ac168c8c05230f/lib/R/library/DESeq2/libs/DESeq2.dylib
  Reason: image not found
Calls: DESeq_basic ... getNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted

Since **libopenblas        conda-forge/osx-64::libopenblas-0.3.10-openmp_h63d9170_3** was installed I don't understand why it is require previous version r0.3.7

**Comment by LeilyR** [comment]
you should have installed in the same environment as your deseq.
