### ISSUE TITLE
Open for pull requests outside epigenomics?

### ISSUE THREAD

**Issue by acesnik** [maxplanck-ie/snakepipes#782]
Hi there,

I'm wondering how wide the scope is for this repository. I have a [snakemake pipeline with an associated commandline tool](https://github.com/smith-chem-wisc/Spritz) (similar to how this repository is structured) that was published this year for the construction of proteogenomic databases from NGS data. The databases are intended to be used for sample-specific or patient-specific MS proteomic data analysis. 

Do you envision this repository as place for such tools beyond epigenomics? I was pointed here as an alternative repository to `bioconda` for such pipeline/tool combinations. https://github.com/bioconda/bioconda-recipes/pull/29875

I also have a lncRNA discovery pipeline written in Snakemake that might also be interesting to consider for implementing here. https://github.com/acesnik/LncRNADiscovery

Best regards,

Anthony

**Comment by thomasmanke** [comment]
Dear Anthony,
Thank you for your interest. We do not consider snakePipes a generic repository for all Snakemake workflows, but we do not limit ourselves to epigenomics either. We will incorporate only workflows that we actually use and can assess. Spritz does not fit this bill, but "lncRNA" maybe of interest in the future - we have not yet looked at it in detail. Naturally we are happy for any help, but to this end you would need to fork snakePipes and write a respective module with documentation. I'm not sure if this is feasible or in your interest.  Best wishes, Thomas

**Comment by acesnik** [comment]
Okay, thanks for the response!
