### ISSUE TITLE
mRNA-seq DESeq2 - sample names with dot are truncated

### ISSUE THREAD

**Issue by mirax87** [maxplanck-ie/snakepipes#789]
Bug report: 

Sample names in `featureCounts/counts.tsv` contain the prefix up to the first dot in the file name. That means, if your sample names natively contains a dot, it may become truncated and the sample sheets for DESeq2 will fail. 

Would it be possible to allow for sample names with dots? I guess, this will be found somewhere in the script that collects the `featureCounts/*.txt`

My guess is the following line requires and update:

https://github.com/maxplanck-ie/snakepipes/blob/master/snakePipes/shared/rscripts/merge_featureCounts.R#L18

**Comment by katsikora** [comment]
Hi Michael,

I'm not sure we support dots in sample names. These might cause issues also in R or be transformed to something that will indeed fail. 
Would you have an example to test on?

Best,
Katarzyna
