### ISSUE TITLE
confusing name to fix in chip pipelien when spike in

### ISSUE THREAD

**Issue by LeilyR** [maxplanck-ie/snakepipes#791]
in `.host.seq_depth_norm.BYspikein.bw ` there is no seq_depth normalisation

**Comment by katsikora** [comment]
Hi Leily,

does this issue still persist?

**Comment by LeilyR** [comment]
if no one else fixed it, it should still be the case. Sorry somehow i missed your comment here.

**Comment by katsikora** [comment]
thanks Leily, I'll reopen. I think this suffix is present in most bigwig file names, I'll have to double-check if there is a reason, or it's just a copy-paste mistake.

**Comment by katsikora** [comment]
Hi Leily,
so these names are for bamcoverage tracks generated for the host genome *normalized* using scaling factors from different options (spike in whole genome, spike in signal around TSS, or spike in signal from the matching input). In that sense, they are normalised, but by 'depth' of the spike in genome.

How about this, I'll update the names to match the files generated by the bamcompare command to something like this `.host_scaled.BYspikein.bw` ?

Best,
Katarzyna
