### ISSUE TITLE
Error in CreateEnvs

### ISSUE THREAD

**Issue by Leif78** [maxplanck-ie/snakepipes#799]
Dear all,
I try to set up snakePipes on a newly installed ubuntu 18.04 and ubuntu 20.04. With both Ubuntus, Creating Environmnets halt in the middle of the set up and do not finnish. I paste in the log. Do anyone has any idea what to do?
 
(snakePipes) leif@leif-OptiPlex-9020:~/Desktop$ snakePipes createEnvs
Creating environment from /home/leif/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/shared/rules/envs/shared.yaml in /home/leif/miniconda3/envs
Creating environment from /home/leif/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/shared/rules/envs/createIndices.yaml in /home/leif/miniconda3/envs
Creating environment from /home/leif/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/shared/rules/envs/rna_seq.yaml in /home/leif/miniconda3/envs
Creating environment from /home/leif/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/shared/rules/envs/rMats.yaml in /home/leif/miniconda3/envs
Creating environment from /home/leif/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/shared/rules/envs/sc_rna_seq.yaml in /home/leif/miniconda3/envs
Creating environment from /home/leif/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/shared/rules/envs/sc_rna_seq_seurat3.yaml in /home/leif/miniconda3/envs
Creating environment from /home/leif/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/shared/rules/envs/sc_rna_seq_loompy.yaml in /home/leif/miniconda3/envs
Creating environment from /home/leif/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/shared/rules/envs/sc_rna_seq_alevinqc.yaml in /home/leif/miniconda3/envs
Creating environment from /home/leif/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/shared/rules/envs/sc_rna_seq_eisaR.yaml in /home/leif/miniconda3/envs
Creating environment from /home/leif/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/shared/rules/envs/dna_mapping.yaml in /home/leif/miniconda3/envs
Creating environment from /home/leif/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/shared/rules/envs/chip_seq.yaml in /home/leif/miniconda3/envs
Creating environment from /home/leif/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/shared/rules/envs/atac_seq.yaml in /home/leif/miniconda3/envs
Creating environment from /home/leif/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/shared/rules/envs/hic.yaml in /home/leif/miniconda3/envs
Creating environment from /home/leif/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/shared/rules/envs/wgbs.yaml in /home/leif/miniconda3/envs
Creating environment from /home/leif/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/shared/rules/envs/rmarkdown.yaml in /home/leif/miniconda3/envs
Creating environment from /home/leif/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/shared/rules/envs/preprocessing.yaml in /home/leif/miniconda3/envs
Creating environment from /home/leif/miniconda3/envs/snakePipes/lib/python3.9/site-packages/snakePipes/shared/rules/envs/noncoding.yaml in /home/leif/miniconda3/envs
Collecting package metadata (repodata.json): done
Solving environment: 

Thanks for help

**Comment by LeilyR** [comment]
how did you install the snakepipes and which version?

**Comment by Leif78** [comment]
I did as described here, version 2.4.3: https://snakepipes.readthedocs.io/en/latest/content/setting_up.html

**Comment by LeilyR** [comment]
please try our latest version `2.5.2`.

**Comment by adRn-s** [comment]
I am able to reproduce this using `2.4.3`, my command is unable to solve the environment for `noncoding.yaml` too. This might be an infinite recursive 'bug' from upstream (`conda`).

@Leif78 : please let us know if you had any issues with the latest version, `2.5.2`.

**Comment by Leif78** [comment]
Hi,
I installed 2.5.2, and the createEnvs has now runned in 21h without finishing.

**Comment by Leif78** [comment]
Thanks for answers. CreateEnvs on version 2.5.2 is not working. It can not solve environment for noncoding.yaml as described before.

**Comment by adRn-s** [comment]
Please try with the new version, `2.5.3`

**Comment by Leif78** [comment]
createEnvs now works. Thanks for help!
