### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by LeilyR** [maxplanck-ie/snakepipes#80]
Hi, sorry for bringing up some native issues but since I am very new in using the snakemake workflows I had some issues in their documentation. For example for ChIP-seq pipeline I couldn't find anywhere which has been mentioned that the directory of the input bam files and the Chip bam files should be the same. I figured it out by looking at the python code after getting error while running the pipeline. Maybe one can even change the naming format which has been written in the code, but if not necessary just explaining it in the ChIP-seq documentation would be fine.  Another one I have noticed was the explanation of how to use  snakemake options(It is correct when running -h just there are dashes missing in snakepipe documentation.)

**Comment by dpryan79** [comment]
The dashes thing is a sphinx issue that affects a lot of packages I think (I'll eventually have time to find a fix for it).
