### ISSUE TITLE
Software versions?

### ISSUE THREAD

**Issue by ANDdna1991** [maxplanck-ie/snakepipes#803]
Hi all, 

SnakePipes is fantastic, great job!! I would just like to know if there is a quick way to check the software versions my SnakePipes uses, I don't mean SnakePipes version, but Bowtie2, cutadapt, etc. I know I can check the logs and so on, but it takes a while. Is there an "environment" list, where I can easily check the version of each software (I know that SnakePipes does not uses an unique environment). I would like to state SnakePipes and Software versions in M&M. 

Thanks!
Andrés

**Comment by LeilyR** [comment]
Hey, yes we do have that already being implemented. it is called `toolsVersion`

**Comment by ANDdna1991** [comment]
Hi LeilyR,

Found it! that's fabulous, thanks! 

Andrés
