### ISSUE TITLE
ATAC-seq fragment size

### ISSUE THREAD

**Issue by sunta3iouxos** [maxplanck-ie/snakepipes#806]
I noticed that you are filtering your bam files with the "alignmentSieve" from deeptools. In the default options, if I am not mistaken you are only using reads <150. So nucleosome free areas.
What is the reason behind this choice? Aren't mononucleosomes and polynucleosomes important?

**Comment by WardDeb** [comment]
Hi,

We indeed use fragments from nucleosome free regions, the idea is to get a sharper/better peak signal around regions of interest. Fragments representing mono- and poly nucleosomes could be important if you're interested in e.g. nucleosome positioning, but this is a bit out of scope of the pipeline.

Hope this helps!
