### ISSUE TITLE
cutntag peak calling

### ISSUE THREAD

**Issue by LeilyR** [maxplanck-ie/snakepipes#808]
bamtobed and peak calling on bed files

**Comment by katsikora** [comment]
Hi Leily, is this a feature you are working on?

Best,

Katarzyna

**Comment by LeilyR** [comment]
no, I am not. I meant to but I never had time for that. Go ahead if you want to take care of it. Althought keep in mind that macs3 might have already taken care of paired end data in a better way, so it might be unnecessary.

**Comment by katsikora** [comment]
I'll just tag it as enhancement then, for the time being. Thanks!
