### ISSUE TITLE
UCSC genome and deseq incompatibility

### ISSUE THREAD

**Issue by LeilyR** [maxplanck-ie/snakepipes#810]
annotation.symbol is empty

**Comment by katsikora** [comment]
hi Leily, we never supported UCSC genome or annotation format - everything is set to work with `ensembl` format. Did you try creating your own indices with your custom ucsc genome and including a matching annotation?

**Comment by LeilyR** [comment]
it was not me who was testing it be a user who brought it up to me, they had all the indices in palce but i am not sure if they were made manually or through our pipline. There was an issue in the filter genome rule as far as i can recall but one need to look deeper into it.

**Comment by katsikora** [comment]
I see. For custom indices, the responsibility lies with the user ... If we could have the error and the files that caused it, I could have a look. Otherwise, I'd prefer to keep `ensembl` as the default annotation format.
