### ISSUE TITLE
Difference between documentation and outcome - featureCounts on 'alignment-free' mode

### ISSUE THREAD

**Issue by FerallOut** [maxplanck-ie/snakepipes#811]
The documentation says: 'featureCounts: (not produced in mode alignment-free) This would contain the gene-level counts (output of featureCounts), on the filtered GTF files, that can be used for differential expression analysis.'

But when actually running the code with '-m alignment-free,deepTools_qc', I get the expected folders + featureCounts. 

So, is the documentation wrong or is the featureCounts running though it should not be?

**Comment by katsikora** [comment]
Hi FerallOut,

this is because you are calling the additional mode `deepTools_qc` - this triggers parts of the `alignment` mode that deepTools qc uses as input, including featureCounts.

Best,
Katarzyna
