### ISSUE TITLE
Adding bwa-mem2?

### ISSUE THREAD

**Issue by jelber2** [maxplanck-ie/snakepipes#817]
Hi,

I was wondering if you might add native support for `bwa-mem2` as that is available through `bioconda`. I added it to my installation, but I guess it would be nice for others? Maybe if I have time, I will make a pull request, but I am not sure if my installation is working for the DNA-mapping pipeline, maybe just the createIndices and Hi-C pipelines. EDIT: I also made it so that bwa-mem1 was replaced by bwa-mem2, so that might not be desirable for all users.

Best,
Jean

**Comment by katsikora** [comment]
Hi Jean,

yes, this sounds like a good idea,
Best,
Katarzyna

**Comment by katsikora** [comment]
implemented in release 2.6.0
