### ISSUE TITLE
modify config file while singularity container

### ISSUE THREAD

**Issue by MarineBergot** [maxplanck-ie/snakepipes#828]
Hi! 
I would like to know if you could help me, i would like to run the pipeline on server but for several reasons i can't install it with conda directly (too many conflicts) and i would like to use container (singularity)
i created singularity container locally and it run perfectly on server but i have trouble with config files. of course all config files are related to pathway i don't have on server, especially the defaults.yaml
I tried to use 
/soft/c7/singularity/3.5.3/bin/singularity exec -e snakePipes.sif HiC -i /work/gad/shared/analyse/HiC/data/C1829A_LR51/fastq -o ./out -c config.yaml hg38

i put that in the beginning :
## General/Snakemake parameters, only used/set by wrapper or in Snakemake cmdl, but not in Snakefile
pipeline: hic
outdir: /work/gad/shared/analyse/HiC/snakePipes
configFile: /work/gad/shared/analyse/HiC/snakePipes/defaults.yaml
clusterConfigFile: /work/gad/shared/analyse/HiC/snakePipes/cluster.yaml
#set to true if running locally
...

and in the defaults.yaml:

clusterConfig: cluster.yaml
configMode: manual
emailSender: null
max_thread: 25
oldConfig: null
onlySSL: false
organismsDir: /work/gad/shared/analyse/HiC/snakePipes/GRCh38_ensembl
smtpPassword: null
smtpPort: 0
smtpServer: null
smtpUsername: null
snakemakeOptions: ' --use-conda --conda-prefix /home/marine/miniconda3/envs '
tempDir:
toolsVersion: true

i wanted to change de defaults.yaml but it pointed in location which doesn't exist in server of course then i can't.. do you have any idea to fix my problem? 

/soft/c7/singularity/3.5.3/bin/singularity exec -e snakePipes.sif HiC -i /work/gad/shared/analyse/HiC/data/C1829A_LR51/fastq -o ./out -c config.yaml hg38

---- This analysis has been done using snakePipes version 2.5.3 ----
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/snakemake/__init__.py", line 730, in snakemake
    success = workflow.execute(
  File "/usr/local/lib/python3.9/site-packages/snakemake/workflow.py", line 683, in execute
    self.persistence = Persistence(
  File "/usr/local/lib/python3.9/site-packages/snakemake/persistence.py", line 98, in __init__
    os.makedirs(d, exist_ok=True)
  File "/usr/local/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/package'
Error: snakemake returned an error code of 1, so processing is incomplete!

thanks a lot for your help!

Marine

**Comment by adRn-s** [comment]
I'm inclined to think this is a duplicate to #745, and not related to singularity itself.

Also, you say that before going with singularity, you had some errors using `conda`. Were you following [this](https://snakepipes.readthedocs.io/en/latest/content/setting_up.html#installing-conda-mamba) instructions? Would you care to retry?

**Comment by MarineBergot** [comment]
yes indeed it's related to the fact that everything in pointed not in the right place but i don't know how to fixe it. If i'm passing defaults.yaml instead of config.yaml i have now this problem : 

/soft/c7/singularity/3.5.3/bin/singularity exec -e snakePipes.sif HiC -i /work/gad/shared/analyse/HiC/data/C1829A_LR51/fastq -o ./out -c defaults.yaml hg38

---- This analysis has been done using snakePipes version 2.5.3 ----
Warning! C1829A_LR51_R1_001 does not have ['_R1', '_R2'] as its name suffix. Either change it or modify the 'reads' in the config.yaml to your deired ones.
Warning! C1829A_LR51_R2_001 does not have ['_R1', '_R2'] as its name suffix. Either change it or modify the 'reads' in the config.yaml to your deired ones.
SystemExit in line 96 of /usr/local/lib/python3.9/site-packages/snakePipes/workflows/HiC/internals.snakefile:
Error! No sample has the right read suffix (['_R1', '_R2']). Please modify them or update the config.yaml with your desired suffix.
  File "/usr/local/lib/python3.9/site-packages/snakePipes/workflows/HiC/Snakefile", line 19, in <module>
  File "/usr/local/lib/python3.9/site-packages/snakePipes/workflows/HiC/internals.snakefile", line 96, in <module>
  File "/usr/local/lib/python3.9/site-packages/snakePipes/common_functions.py", line 155, in get_sample_names
Error: snakemake returned an error code of 1, so processing is incomplete!

is there a way i can pass 2 files ? config.yaml AND defaults.yaml? or to make one  point on the other one? thanks!

i followed recommandation as in the other post and change conda-path but i didn't change, everything still pointed on my env 3.9 in my local installation

**Comment by MarineBergot** [comment]
i finally downolad sources and installed them with build.sh but i still have problems, i really don't know what is wrong 
in my folder i have :
ls
azure-pipelines.yml  build     cluster.yaml  config.yaml  GRCh38_ensembl  LICENSE      out         record.txt        setup.py    snakePipes.egg-info
bin                  build.sh  conda-recipe  docs         hg38.yaml       MANIFEST.in  README.rst  requirements.txt  snakePipes  tmp

if i'm trying : ./HiC -i /work/gad/shared/analyse/HiC/data/C1829A_LR51/fastq -o out ../../hg38.yaml 
/bin/sh: /beegfs/data/work/gad/shared/analyse/HiC/software/snakepipes-2.5.3/build/scripts-3.6/snakemake: Aucun fichier ou dossier de ce type
Error: snakemake returned an error code of 127, so processing is incomplete!

/beegfs/data/work/gad/shared/analyse/HiC/software/snakepipes-2.5.3/build/scripts-3.6/snakemake: this path doesn't exists then i don't know where it came from.. if you have some clues for me, thanks!

**Comment by adRn-s** [comment]
> Were you following [this](https://snakepipes.readthedocs.io/en/latest/content/setting_up.html#installing-conda-mamba) instructions? Would you care to retry?

I'm having difficulties to see if you answered these two questions, and I believe you are yet to follow our official documentation.

**Comment by MarineBergot** [comment]
yeah of course i tried:

conda activate dev (as i'm working on server of course i don't have any rights and most of the conda packages are locked)

conda install mamba -c conda-forge
...
...

Downloading and Extracting Packages
setuptools-63.4.2    | 1.4 MB    | ################################################################################################################################################################ | 100% 
zstd-1.5.2           | 450 KB    | ################################################################################################################################################################ | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done


(dev) XXXXXXXX :mamba
Traceback (most recent call last):
  File "/work/gad/shared/bin/miniconda3/envs/dev/bin/mamba", line 4, in <module>
    import re
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/re.py", line 123, in <module>
    import sre_compile
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/sre_compile.py", line 17, in <module>
    assert _sre.MAGIC == MAGIC, "SRE module mismatch"
AssertionError: SRE module mismatch

**Comment by adRn-s** [comment]
You shouldn't install mamba in your dev environment. Or any other. Only in base. Thats the issue.

I'm afraid you're not following our docs strictly. The aforementioned link to our instructions adhere to official mamba documentation too.

Good luck!
