### ISSUE TITLE
Error invalid literal for int() with base 10 when creating indices

### ISSUE THREAD

**Issue by jhkamstra** [maxplanck-ie/snakepipes#832]
Hi, when creating indices at the very end I receive an error message:

ValueError in line 148 of /home/edctox/miniconda3/envs/snakePipes/lib/python3.10/site-packages/snakePipes/workflows/createIndices/Snakefile:
invalid literal for int() with base 10: '2,94585e+09'
  File "/home/edctox/miniconda3/envs/snakePipes/lib/python3.10/site-packages/snakePipes/workflows/createIndices/Snakefile", line 148, in __onsuccess
Error: snakemake returned an error code of 1, so processing is incomplete!

It seems all indices are made, but the corresponding YAML file in organisms is not created, as far as I can see. any advice? Does it have something to do with a wrong format of the genome size? Normally, I am quite creative in finding a solution, but in this case it goes beyond my knowledge...

**Comment by jhkamstra** [comment]
Update:
I tried it now with UCSC fasta/gft files, with a similar error message. Everything seems to work fine, up to the very last stage.
Installed miniconda with python 3.9
Followed the instruction to install Snakepipes via mamba and its Envs the point with no error messages given.

**Comment by jhkamstra** [comment]
Well did my analysis now the old-fashioned way with STAR. Would be nice to get this working. I have made it work in the past

**Comment by katsikora** [comment]
Hi Jhkamstra,

thanks for your comments, we will look into this. Which snakePipes version did cause the error for you?

Best,
Katarzyna

**Comment by jhkamstra** [comment]
Hi Katarzyna,

Installed version is 2.5.4.

**Comment by katsikora** [comment]
Thanks, I'm looking into it.

**Comment by katsikora** [comment]
I cannot reproduce your issue with `snakePipes 2.5.4`. I've run:
```createIndices -o $output_dir/GRCh38_g31_2.7.4a --tools star --genomeURL $repo/GRCh38_ensembl/genome_fasta/genome.fa --gtfURL $repo/GRCh38_ensembl/gencode/release_31/genes.gtf --userYAML  GRCh38_g31``` and this produced a valid organims yaml file with the genome size properly formatted as `genome_size: 2913022398` .

**Comment by katsikora** [comment]
The conversion of the genome size from float into an integer by the python interpreter failed.
I'm not sure why it's working for me here and not working for you.
It looks like you've correctly installed snakePipes with python 3.10.  

I can add an explicit conversion from float to integer that should fix it.

**Comment by jhkamstra** [comment]
> I cannot reproduce your issue with `snakePipes 2.5.4`. I've run: `createIndices -o $output_dir/GRCh38_g31_2.7.4a --tools star --genomeURL $repo/GRCh38_ensembl/genome_fasta/genome.fa --gtfURL $repo/GRCh38_ensembl/gencode/release_31/genes.gtf --userYAML GRCh38_g31` and this produced a valid organims yaml file with the genome size properly formatted as `genome_size: 2913022398` .

Interesting, I thought something similar. I am sure I am doing something wrong. I installed it also on my laptop at home, exactly the same error. By the way, I used exactly the same commandline, only with --local and only --tools star (to speed up the process).

**Comment by jhkamstra** [comment]
> The conversion of the genome size from float into an integer by the python interpreter failed. I'm not sure why it's working for me here and not working for you. It looks like you've correctly installed snakePipes with python 3.10.
> 
> I can add an explicit conversion from float to integer that should fix it.

Thanks so much! Let me know when it's fixed. Nevertheless, it is a medicine, not curing the problem at my PC. I would really like to know what kind of action I could perform to not get this error. Maybe a missing dependency somewhere?

**Comment by katsikora** [comment]
Right, so what OS is your PC running? I've tested on CentOS 7 here.
In my hands, snakePipes 2.5.4 is running with python 3.10.5 with the build tag h582c2e5_0_cpython  from  conda-forge.

**Comment by jhkamstra** [comment]
Ubuntu 22.04 clean install, with miniconda - Python 3.9 shell script downloaded from the miniconda website. Checked the hash and installed it with bash. During installation, selected yes for default installation. 

Thereafter followed the instructions on the snakePipes documentation to the point. No errors to that point.

Then creating the indices with the only thing that the location for generating the indices are on another internal HDD. (the system HDD is an SSD of only 128GB...

**Comment by katsikora** [comment]
implemented in release 2.6.0

**Comment by jhkamstra** [comment]
Dear Katarzyna,

Super nice that you implemented it! Much appreciated, I will have another go at it.

Best wishes,
Jorke
