### ISSUE TITLE
Check for valid fastq files before workflow execution

### ISSUE THREAD

**Issue by WardDeb** [maxplanck-ie/snakepipes#881]
'empty' or corrupt fastq files only trigger a pipeline failure very late in mRNA-seq stage (~bamCoverage rules). Perhaps an initial check (no unexpected EOF, at least x reads present) could be done before pipeline execution ?

**Comment by katsikora** [comment]
Ideally I would put the responsibility on the user, but if it's a fast check, why not having it. Is this by any chance an issue with SRA-derived files?

**Comment by WardDeb** [comment]
Done in #899
