### ISSUE TITLE
createEnvs fails when channel_priority set to 'strict'

### ISSUE THREAD

**Issue by isaacvock** [maxplanck-ie/snakepipes#884]
Hello all,

First off, thank you for an incredibly useful collection of easy to use pipelines.

I wanted to flag what seems like a minor bug in the `snakePipes createEnvs` function. When trying to build the whole genome bisfulfite sequencing environment (stored in wgbs.yaml), I got the following error:

`package bioconductor-biomart-2.38.0-r351_0 requires r-base >=3.5.1,<3.5.2.0a0, but none of the providers can be installed`

This is the same error discussed in #874 (which was eventually solved with a complete reinstall). I was able to resolve the problem without a reinstall by setting my [channel priority](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-channels.html) to flexible with:

`conda config --set channel_priority flexible` 

I downloaded the wgbs.yaml file from this repo and played around with trying to create the environment manually with mamba to see if I could resolve the issue with strict channel priority, but nothing I tried worked. Since conda's own documentation states "We recommend setting channel priority to "strict" when possible", it may be worth including a statement in snakePipe's documentation that strict channel priority won't work with createEnvs (if my assessment is correct). 

## System details
Tested on two systems

System 1:

HPC
Interactive execution
Redhat Linux 8.5
snakePipes 2.7.2
conda 22.11.1
mamba 1.2.0

System 2 (only tested creation of particular environment):

Windows subsystem for linux
conda 22.11.1
mamba 1.1.0

**Comment by isaacvock** [comment]
Update: removing mpi-ie from the list of channels in wgbs.yaml can resolve the issue.

**Comment by katsikora** [comment]
Hi Issacvock,

the issue is known and we have a fix down the line. 
I'd definitely stick to 'strict' channel priorities for creating snakePipes environments.

Thanks for reporting it and suggesting a fix ,

Best,

Katarzyna
