### ISSUE TITLE
3primeseq question

### ISSUE THREAD

**Issue by sunta3iouxos** [maxplanck-ie/snakepipes#894]
Dear all,
where is that module applicable?
I am asking because there are various 3'prime RNA-seq protocols there (quant-seq, NEBNext Single Cell/Low Input RNA , the illumina 3'-Seq, Ovation SoLo). Each one of those site on their site specific trimming and mapping details.
Would it be possible to provide an overview of the method and for which RNA/library preperation applies?

Thank you

**Comment by katsikora** [comment]
Hi sunta3iouxos,

the 3'prime RNA-seq mode has been tested with the Lexogen 3'Seq/ Illumina.
We may be able to test it with other prep kits in the future and adjust as applicable.
Trimming and mapping parameters can be controlled with `--trimmerOptions` and `-alignerOptions` in any case.

Best wishes,

Katarzyna
