### ISSUE TITLE
CI dag test 

### ISSUE THREAD

**Issue by WardDeb** [maxplanck-ie/snakepipes#901]
Using -q / --quiet on top of a dryrun would make parsing the proposed number of rules more straight forward and easier to replicate with changing versions of snakemake. (which would be a preferred metric over a linecount if I understand correctly)

**Comment by katsikora** [comment]
It would be good to test this in parallel to the line count, and deprecate over time, I think.
Also, perhaps [snakemake's unit tests](https://snakemake.readthedocs.io/en/stable/snakefiles/testing.html) could be useful, and some sort of checks on the wildcards.
