### ISSUE TITLE
setting for cutandrun

### ISSUE THREAD

**Issue by sunta3iouxos** [maxplanck-ie/snakepipes#909]
Hi all,
How am I setting specific commands for the cut and Run in the ChIP-seq pipeline? the cut and tag is specific for the tn5 transposase that adjusts the fragments for +5/-7 (if I recall correctly) but MNAse is a bit different?
Thank you

**Comment by katsikora** [comment]
Hi sunta3iouxos,

you can run both `DNA-mapping` and `ChIP-seq` workflows with the `--cutntag` flag. This will adjust mapping and peak calling settings, accordingly. Also, if you've got spikein in your samples, you might want to map to a hybrid genome (that can be generated with `createIndices`) and the pass `--useSpikeInForNorm` in the `ChIP-seq` workflow.

We don't do any adjustments on the mapped fragment positions as is. 

Best wishes,

Katarzyna

**Comment by sunta3iouxos** [comment]
Hi Katarzyna,
so no necessary adjustments for the cut&run protocol.
thank you!
