### ISSUE TITLE
difference in conda env hashes between snakePipes and snakemake

### ISSUE THREAD

**Issue by katsikora** [maxplanck-ie/snakepipes#914]
For rna_seq.yaml:
name: snakepipes_RNAseq_environment_2.0
channels:
 - conda-forge
 - bioconda
dependencies:
# - python >= 3
 - bedtools = 2.30.0
 - samtools = 1.15.1
 - subread = 2.0.1
 - hisat2 = 2.2.1
 - star = 2.7.10b
 - salmon = 1.10.1
 - r-base = 4.1.3
 - r-wasabi
 - r-dplyr
 - r-ggplot2
 - r-pheatmap
 - r-rmarkdown
 - r-knitr
 - pandoc
 - r-dt
 - r-rcolorbrewer
 - bioconductor-deseq2
 - bioconductor-tximport
 - r-knitcitations
 - bioconductor-apeglm
 - tbb
# - rmats = 4.1.0

snakemake calculates the hash `29176e8931ebf4e5c530cdaeeea4c2b4_`, while snakePipes createEnvs `1894f9150863005367d36e19714f936e` .

**Comment by WardDeb** [comment]
These were most likely due to trailing slashes in the conda path. Should be fixed in #1041
