### ISSUE TITLE
noncoding-RNA-seq test data

### ISSUE THREAD

**Issue by roddypr** [maxplanck-ie/snakepipes#915]
Hi,
The test data for noncoding-RNA-seq seems to link to a zenodo repo that is not public.
https://zenodo.org/deposit/3707749

This is not an important issue, but I thought I would flag it up.
Thanks

**Comment by katsikora** [comment]
Hi,

thanks for raising the issue. The data is available at https://zenodo.org/record/3707749 .
Where did you find the `deposit` link? Somewhere in the documentation?

Best wishes,

Katarzyna

**Comment by roddypr** [comment]
Hi, the link is on the test datasets in the documentation here:
https://snakepipes.readthedocs.io/en/latest/content/setting_up.html#test-data

But I just checked again and the data is now visible and downloadable. So maybe the problem was with zenodo yesterday, and not on your end...

Thank you for your help!
