### ISSUE TITLE
possibility to have readable envs?

### ISSUE THREAD

**Issue by sunta3iouxos** [maxplanck-ie/snakepipes#918]
to use some environments for custom work, for example bedtools in DNA mapping I need to run the `snakePipes envInfo` command to find the appropriate environment. `mamba env list` provides no usable information
```bash
envs/shared.yaml is in:
    mambaforge/envs/27f2773ffdbc97941318f72b021070d6
envs/createIndices.yaml is in:
    mambaforge/envs/12f227c63319d49227b7c24df8b9f896
envs/rna_seq.yaml is in:
    mambaforge/envs/b4493075523163bb007302e91dbab003
```

**Comment by katsikora** [comment]
What would you like to obtain? 
E.g. if  you're after the list of packages inside each env, you  can run `mamba list -p $PATH_TO_ENV`, the path to the environment being what's returned by `snakePipes envInfo`. You can then `mamba activate  $PATH_TO_ENV` and use the env for any custom work.
If you want to read the env yamls to see what's specified in there, the paths should be return by `snakePipes info`.

Hope this helps,

Best,

Katarzyna
