### ISSUE TITLE
WorkflowError in line 187

### ISSUE THREAD

**Issue by sunta3iouxos** [maxplanck-ie/snakepipes#919]
Finished job 0.
29 of 29 steps (100%) done
Complete log: .snakemake/log/2023-08-16T172747.055033.snakemake.log

---- This analysis has been done using snakePipes version 2.7.3 ---

WorkflowError in line 187 of mambaforge/envs/snakePipes/lib/python3.11/site-packages/snakePipes/workflows/DNA-mapping/Snakefile:
Resource _nodes is of type int but global resource constraint defines <class 'str'> with value 6. Resources with the same name need to have the same types (int, float, or str are allowed).

This error was generated after the successful DNA-mapping

**Comment by katsikora** [comment]
Hi Sunta3iouxos,

did you run the `DNA-mapping` workflow with `--DAG` and `--local` ? 
I've seen this happening before with this combination of flags. It will possibly go away once we update the snakemake version we are building snakePipes with.

Best wishes,

Katarzyna

**Comment by sunta3iouxos** [comment]
Yes, I am running the pipeline locally (--local) and wanted to also create a diagram of processes (--DAG).
So, it will be solved. 
Thank you
