### ISSUE TITLE
reason: Missing output files

### ISSUE THREAD

**Issue by sunta3iouxos** [maxplanck-ie/snakepipes#920]
What this message implies?
It is a bit confusing.

**Comment by katsikora** [comment]
Hi Sunta3iouxos,

snakemake lists reasons for executing of each rule, at least since a couple of versions. "Missing output files" is one of the reasons a rule would be executed. 

Hope this helps,

Best,

Katarzyna

**Comment by sunta3iouxos** [comment]
Now I understand.
This is a rule that will check if the expected output is there. If it is  it will skip this step.
It is a check that will resume the process if it fails for any reason.
Thank you.
