### ISSUE TITLE
Question regarding spikeIns

### ISSUE THREAD

**Issue by sunta3iouxos** [maxplanck-ie/snakepipes#925]
Hi all,
you are mentioning:

> Scale factors can be obtained either from whole spikein genome in the ChIP samples, from windows centered on TSS in the spikein genome in the ChIP samples, or from whole spikein genome in the input samples

I am using the genome option for CUT&RUN, and I assume that this is the correct option for the method. Is my assumption correct?
Input is used if we have added inputs to our experiment, like in a ChIP-seq. What about the TSS?
Thank you in advance

**Comment by katsikora** [comment]
Hi,

TSS-centered regions can be used instead of whole spikein genome if the spikein has been added prior to the IP and is expected to be pulled down by the antibody. AFAIK, some people prefer this for e.g. Pol2 ChIPs. 

HTH,

Katarzyna
