### ISSUE TITLE
blackelist in DNA mapping

### ISSUE THREAD

**Issue by sunta3iouxos** [maxplanck-ie/snakepipes#930]
Does the DNA pipeline takes into account, in any step, the blacklisted areas, if they are stated in the genome.yalm?
Or the blacklisted areas are used only in, for example the ChIP-seq pipelines?
There is a new publication that provides an updated black-list file, by analysing negative CUT&RUN experiments, that due to the nature of the experiment the black-listed areas are far fewer and narrower. So, if it is possible, I would like to perform again the ChIP-seq part without repeating the DNA-mapping.

**Comment by katsikora** [comment]
Hi,

the blacklist is used by  `deeptools`  in DNA-mapping, mRNA-seq, ChIP-seq and ATAC-seq workflows. Reads falling into the blacklist regions are substracted from the total read number used for normalization of coverage tracks, see [here](https://deeptools.readthedocs.io/en/develop/content/feature/blacklist.html) for details.
In the DNA-mapping workflow, bam coverage tracks are computed, in the ChIP-seq workfow - fold changes between ChIP and input. It's slightly more complicated in case of running with `--useSpikeInForNorm`, where bam coverage tracks are recalculated in the ChIP-seq workflow after splitting the bam file into "host" and "spikein".

Mapping in the DNA-mapping workflow is not affected by the blacklist.

Hope this helps,
Best,
Katarzyna

**Comment by sunta3iouxos** [comment]
thank you
