### ISSUE TITLE
genome.fa from URL

### ISSUE THREAD

**Issue by hanrong498** [maxplanck-ie/snakepipes#933]
Hi!

Thanks for the option to use reference genome directly from URL as input in `createIndices`. However, I had an issue with this: 

On the first trial, I used a wrong URL and therefore the indexing steps cannot start properly. After realising this, I updated the URL link, and the `createIndices.config.yaml` was updated accordingly.

However, when I tried to re-submit the job, `genome_fasta/genome.fa` was not updated. My solution is to delete the folder `genome_fasta`; then the snakemake pipeline will re-create such file.

I am writing this in case anyone has the similar issues, and to report a potential bug.

**Comment by katsikora** [comment]
Hi @hanrong498 ,

thanks for sharing your issue. This has to do with how snakemake labels rules as completed. I'd expect the rule output (genome fasta) to be updated when you update the input (genome url).
It remains to be tested if this behaviour persists when we upgrade the snakemake version. 
The worflow config.yaml is updated by our wrapper script, it doesn't depend on snakemake.

Best regards,
Katarzyna
