### ISSUE TITLE
ChIP-seq CSAW group

### ISSUE THREAD

**Issue by sunta3iouxos** [maxplanck-ie/snakepipes#947]
Hi again,
I noticed that in the RNA-seq pipeline there is an implimentation of group field in the samplesheet, so that the pipeline can do multiple pairwise comparisons based on the group (ex group1, group2 etc)
Is it possible to implement this for the ChIP-seq pipeline?
Thank you!

**Comment by katsikora** [comment]
This is now implemented in snakePipes 2.8.0 and 2.8.1.
