### ISSUE TITLE
[request] implemantation of SEACR

### ISSUE THREAD

**Issue by sunta3iouxos** [maxplanck-ie/snakepipes#951]
Hi again,
is it possible to add the SEACR tool for cut&run analysis?
Thank you.
it appears that at the moment the de facto peak-caller for CUT&RUN (I am unsure on the CUT&TAG, since ATAC-seq optimised callers like Genrich could be better) is SEACR. The generated output is quite simple (bed format) and can be parsed to downstream analysis, like CSAW or motif analysis etc.
The input requires bedgraph that is already produced from snakePipes.

Thank you
EDIT: fixed grammar, for it to make sense.

**Comment by katsikora** [comment]
This is now available in snakePipes 2.8.0 and 2.8.1.
